O objetivo é criar uma consulta de ações no yahoo finance com o objetivo de armazenar as informações em um banco de dados local, criando um histórico de consulta que pode ser utilizado para análises futuras e que poderá ser atualizado periodicamente para manter os dados atualizados. Para isso, podemos utilizar a biblioteca `yfinance` em Python, que facilita a obtenção de dados financeiros do Yahoo Finance.

In [1]:
import yfinance as yf
from datetime import datetime, timedelta
import pandas as pd

### Datas das consultas

In [2]:
# Data de início para coleta de dados
data_marco = '2023-01-01'

# Data atual para a coleta de dados
data_atual = datetime.now().strftime('%Y-%m-%d')

### Tratamento da consulta de ações (tickers) para transformar em um json para consulta

#### Função para carregar dados de empresas e setores da B3

In [3]:
import pandas as pd

def gerar_df_b3_empresas_setor(caminho_arquivo: str, 
                                    planilha: str = 'Setor', 
                                    colunas_intervalo: str = 'B:H', 
                                    pula_linhas: int = 2, 
                                    numero_linhas: int = 370) -> pd.DataFrame:
    """
    Carrega e retorna um DataFrame com as informações de empresas e setores da B3.
    
    Esta função lê um arquivo Excel contendo dados de empresas listadas na Bolsa
    de Valores do Brasil (B3), com informações sobre setores econômicos,
    subsetores, segmentos de negociação e outros dados estruturais.
    
    Parâmetros
    ----------
    caminho_arquivo : str
        Caminho completo ou relativo do arquivo Excel contendo dados das empresas e setores.
        Exemplo: '../utils/gera_tikers/B3_Empresas_Setor_20260206.xlsx'
    
    planilha : str, optional
        Nome da aba/planilha no arquivo Excel (padrão: 'Setor').
        A planilha deve conter uma coluna chamada 'CÓDIGO' que será usada como índice.
    
    colunas_intervalo : str, optional
        Intervalo de colunas a ler no formato Excel (padrão: 'B:H').
        Exemplos válidos: 'A:E', 'B:H', 'C:F'.
    
    pula_linhas : int, optional
        Número de linhas iniciais a pular na leitura (padrão: 2).
        Útil para ignorar cabeçalhos ou informações adicionais no início do arquivo.
    
    numero_linhas : int, optional
        Número máximo de linhas de dados a ler (padrão: 370).
        Se o arquivo tiver menos linhas, todas serão lidas.
    
    Retorno
    -------
    pd.DataFrame
        DataFrame com a coluna 'CÓDIGO' definida como índice, contendo as seguintes
        informações estruturais:
        - BEEST (ou similar)
        - SETOR ECONÔMICO
        - SUBSETOR
        - SEGMENTO
        - NOME DE PREGÃO
        - SEGMENTO DE NEGOCIAÇÃO
        
        O índice do DataFrame conterá os códigos das empresas (ex: 'PETR', 'VALE', 'ITUB').
    """
    try:
        # Ler o arquivo Excel com os parâmetros especificados
        df_b3_empresas_setor = pd.read_excel(
            io=caminho_arquivo,
            sheet_name=planilha,
            usecols=colunas_intervalo,
            skiprows=pula_linhas,
            nrows=numero_linhas,
            index_col='CÓDIGO'  # Definir a coluna 'CÓDIGO' como índice do DataFrame
        )
        
        return df_b3_empresas_setor
    
    # Tratamento de exceções para garantir que erros sejam informativos
    except FileNotFoundError:
        raise FileNotFoundError(f"Arquivo não encontrado: {caminho_arquivo}")
    except ValueError as e:
        raise ValueError(f"Erro ao ler o arquivo Excel: {str(e)}")
    except Exception as e:
        raise Exception(f"Erro inesperado ao processar o arquivo: {str(e)}")

In [4]:
# Exemplo de uso: Carregar o DataFrame de empresas e setores da B3
caminho_arquivo_b3 = "../utils/gera_tikers/B3_Empresas_Setor_20260206.xlsx"

df_b3_empresas_setor = gerar_df_b3_empresas_setor(
    caminho_arquivo=caminho_arquivo_b3,
    planilha='Setor',
    colunas_intervalo='B:H',
    pula_linhas=2,
    numero_linhas=370
)

print("=" * 70)
print("DataFrame de Empresas e Setores da B3")
print("=" * 70)
print(f"\nDimensões do DataFrame: {df_b3_empresas_setor.shape}")
print(f"Linhas: {df_b3_empresas_setor.shape[0]} | Colunas: {df_b3_empresas_setor.shape[1]}")
print(f"\nColunas disponíveis:\n{df_b3_empresas_setor.columns.tolist()}")
print(f"\nÍndice (Códigos das Empresas):\n{df_b3_empresas_setor.index.tolist()[:10]}...")
print(f"\nPrimeiras linhas do DataFrame:")
print(df_b3_empresas_setor.head())
print("=" * 70)

======================================================================
DataFrame de Empresas e Setores da B3
======================================================================

Dimensões do DataFrame: (369, 6)
Linhas: 369 | Colunas: 6

Colunas disponíveis:
['BEEST', 'SETOR ECONÔMICO', 'SUBSETOR', 'SEGMENTO', 'NOME DE PREGÃO', 'SEGMENTO DE NEGOCIAÇÃO']

Índice (Códigos das Empresas):
['AZTE', 'BRAV', 'CSAN', 'RPMG', 'PETR', 'RECV', 'PRIO', 'RAIZ', 'UGPA', 'LUPA']...

Primeiras linhas do DataFrame:
            BEEST                  SETOR ECONÔMICO  \
CÓDIGO
AZTE        Outra  Petróleo, Gás e Biocombustíveis
BRAV        Outra  Petróleo, Gás e Biocombustíveis
CSAN        Outra  Petróleo, Gás e Biocombustíveis
RPMG        Outra  Petróleo, Gás e Biocombustíveis
PETR    Escolhida  Petróleo, Gás e Biocombustíveis

                               SUBSETOR                           SEGMENTO  \
CÓDIGO
AZTE    Petróleo, Gás e Biocombustíveis  Exploração, Refino e Distribuição
BRAV    Petróleo, Gás e Biocombustíveis  Exploração, Refino e Distribuição
CSAN    Petróleo, Gás e Biocombustíveis  Exploração, Refino e Distribuição
RPMG    Petróleo, Gás e Biocombustíveis  Exploração, Refino e Distribuição
PETR    Petróleo, Gás e Biocombustíveis  Exploração, Refino e Distribuição

       NOME DE PREGÃO SEGMENTO DE NEGOCIAÇÃO
CÓDIGO
AZTE      AZT ENERGIA           Básico Bolsa
BRAV            BRAVA           Novo Mercado
CSAN            COSAN           Novo Mercado
RPMG     PET MANGUINH           Básico Bolsa
PETR        PETROBRAS                Nível 2
======================================================================

In [5]:
"""
# Arquivo Excel de origem da relação de papéis e setores
arquivo = "../utils/gera_tikers/B3_Empresas_Setor_20260206.xlsx"

# Planilha e aba onde estão os papéis e setores
planilha = 'Setor'
colunas_intervalo = 'B:H'
pula_linhas = 2
numero_linhas = 370

# DataFrame para armazenar os dados coletados
df_b3_empresas_setor = pd.read_excel(
                        io=arquivo, 
                        sheet_name=planilha,
                        usecols=colunas_intervalo,
                        skiprows=pula_linhas,
                        nrows=numero_linhas,
                        index_col='CÓDIGO' # Definir a coluna 'CÓDIGO' como índice do DataFrame
                        )

# Exibir o DataFrame para verificar os dados coletados
df_b3_empresas_setor.head()
"""

'\n# Arquivo Excel de origem da relação de papéis e setores\narquivo = "../utils/gera_tikers/B3_Empresas_Setor_20260206.xlsx"\n\n# Planilha e aba onde estão os papéis e setores\nplanilha = \'Setor\'\ncolunas_intervalo = \'B:H\'\npula_linhas = 2\nnumero_linhas = 370\n\n# DataFrame para armazenar os dados coletados\ndf_b3_empresas_setor = pd.read_excel(\n                        io=arquivo, \n                        sheet_name=planilha,\n                        usecols=colunas_intervalo,\n                        skiprows=pula_linhas,\n                        nrows=numero_linhas,\n                        index_col=\'CÓDIGO\' # Definir a coluna \'CÓDIGO\' como índice do DataFrame\n                        )\n\n# Exibir o DataFrame para verificar os dados coletados\ndf_b3_empresas_setor.head()\n'

In [6]:
# Extrair os nomes das colunas do DataFrame
colunas = df_b3_empresas_setor.columns.tolist()

# Exibir os nomes das colunas para verificar a estrutura do DataFrame
print(colunas)

['BEEST', 'SETOR ECONÔMICO', 'SUBSETOR', 'SEGMENTO', 'NOME DE PREGÃO', 'SEGMENTO DE NEGOCIAÇÃO']

In [7]:
# Símbolos base dos papais negociado na B3
simbolos_base = df_b3_empresas_setor.index.tolist()

# Exibir os símbolos base para verificar os dados coletados
print(simbolos_base)

['AZTE', 'BRAV', 'CSAN', 'RPMG', 'PETR', 'RECV', 'PRIO', 'RAIZ', 'UGPA', 'LUPA', 'OPCT', 'OSXB', 'VBBR', 'AURA', 'BRAP', 'CBAV', 'CMIN', 'LTEL', 'LTLA', 'VALE', 'FESA', 'GGBR', 'GOAU', 'CSNA', 'USIM', 'HAGA', 'MGEL', 'PATI', 'TKNO', 'PMAM', 'BRKM', 'DEXP', 'FHER', 'NUTR', 'VITT', 'CRPG', 'UNIP', 'DXCO', 'EUCA', 'KLBN', 'MSPA', 'NEMO', 'SUZB', 'RANI', 'SNSY', 'ETER', 'PTBL', 'AZEV', 'SOND', 'ARML', 'MILS', 'PRNR', 'EMBJ', 'FRAS', 'POMO', 'RAPT', 'RCSL', 'RSUL', 'TUPY', 'MWET', 'SHUL', 'WEGE', 'EALT', 'AERI', 'BDLL', 'INEP', 'KEPL', 'FRIO', 'PTCA', 'ROMI', 'MTSA', 'TASA', 'AZUL', 'GOLL', 'VSPT', 'MRSA', 'RAIL', 'HBSA', 'LOGN', 'LUXM', 'JSLG', 'SEQL', 'TGMA', 'CRTE', 'ECOR', 'MOTV', 'TPIS', 'AGRU', 'HMOB', 'IVPR', 'PSVM', 'BBML', 'CTAX', 'DTCY', 'ALPK', 'GGPS', 'VLID', 'MMAQ', 'RBNS', 'WLMM', 'TTEN', 'AGXY', 'APTI', 'SOJA', 'AGRO', 'CTCA', 'EGGY', 'SLCE', 'LAND', 'JALL', 'SMTO', 'BAUH', 'FICT', 'JBSS', 'MBRF', 'BEEF', 'MNPR', 'CAML', 'JOPA', 'MDIA', 'ODER', 'ABEV', 'ESPA', 'NATU', 'BOBR', 'ASAI', 'GMAT', 'PCAR', 'AZZA', 'CEAB', 'CGRA', 'AMAR', 'LREN', 'RIAA', 'VSTE', 'ALLD', 'BHIA', 'MGLU', 'AMER', 'SBFG', 'LLBI', 'AUAU', 'LJQQ', 'AVLL', 'CALI', 'CURY', 'CYRE', 'DIRR', 'EVEN', 'EZTC', 'FIEI', 'GFSA', 'HBOR', 'INNC', 'JHSF', 'JFEN', 'KLAS', 'LAVV', 'MELK', 'MTRE', 'MDNE', 'MRVE', 'PDGR', 'PLPL', 'CCTY', 'RSID', 'TCSA', 'TEND', 'TRIS', 'VIVR', 'CEDO', 'DOHL', 'CATA', 'CTKA', 'PTNT', 'CTSA', 'TXRX', 'TFCO', 'ALPA', 'CAMB', 'GRND', 'VULC', 'MNDL', 'TECN', 'VIVA', 'WHRL', 'TOKY', 'UCAS', 'WEST', 'HETA', 'AMOB', 'MYPK', 'LEVE', 'PLAS', 'HOOT', 'MEAL', 'BMKS', 'ESTR', 'RVEE', 'AHEB', 'SHOW', 'CVCB', 'SMFT', 'ANIM', 'ATED', 'BIED', 'COGN', 'CSED', 'SALT', 'OBTC', 'SEER', 'VTRU', 'YDUQ', 'RENT', 'MOVI', 'VAMO', 'DOTZ', 'BIOM', 'OFSA', 'AALR', 'DASA', 'FLRY', 'HAPV', 'MATD', 'ODPV', 'ONCO', 'QUAL', 'RDOR', 'BALM', 'LMED', 'BLAU', 'DMVF', 'PNVL', 'EUFA', 'HYPE', 'PGMN', 'PFRM', 'RADL', 'VVEO', 'INTB', 'MLAS', 'POSI', 'BMOB', 'BRQB', 'ENJU', 'IFCM', 'LWSA', 'CASH', 'NGRD', 'PDTC', 'QUSW', 'TRAD', 'TOTS', 'WDCN', 'BRST', 'DESK', 'OIBR', 'TELB', 'VIVT', 'TIMS', 'FIQE', 'AESO', 'AFLT', 'ALUP', 'CBEE', 'AURE', 'AXIA', 'CEBR', 'CEED', 'CLSC', 'GPAR', 'CMIG', 'CEEB', 'COCE', 'COMR', 'CPLE', 'CPFE', 'EKTR', 'EMAE', 'ENGI', 'ENMT', 'ENEV', 'EGIE', 'EQPA', 'EQMA', 'EQTL', 'GEPA', 'ISAE', 'LIGH', 'LIGT', 'NEOE', 'PRMN', 'REDE', 'RNEW', 'RIOS', 'TAEE', 'AMBP', 'CASN', 'CSMG', 'IGSN', 'ORVR', 'SBSP', 'SAPR', 'CEGR', 'CGAS', 'PASS', 'ABCB', 'RPAD', 'BAZA', 'BMGB', 'BGIP', 'BEES', 'BPAR', 'BRSR', 'BRBI', 'BBDC', 'BBAS', 'BSLI', 'BPAC', 'INBR', 'ITUB', 'BMIN', 'BMEB', 'BNBR', 'PINE', 'SANB', 'MERC', 'FIGE', 'BSCS', 'RBRA', 'PLSC', 'G2DI', 'PPLA', 'B3SA', 'CSUD', 'BBSE', 'CXSE', 'PSSA', 'IRBR', 'WIZC', 'ALOS', 'GSHP', 'HBTS', 'HBRE', 'IGTI', 'LOGG', 'MULT', 'NORD', 'PEAB', 'SCAR', 'SYNE', 'LPSB', 'NEXP', 'ARND', 'EPAR', 'ITSA', 'SIMH', 'ADMF', 'CTBA', 'MCRJ', 'PMSP', 'QVQP', 'BETP', 'MAPT', 'OPGM', 'PPAR', 'PRPT', 'OPSE', 'OPTS']

In [8]:
# Consulta na API do Yahoo Finance quais são os tickers correspondentes aos símbolos base
tickers = []
for simbolo in simbolos_base:
    ticker = yf.Ticker(simbolo + '.SA')  # Adiciona o sufixo '.SA' para ações da B3
    tickers.append(ticker)
# Exibir os tickers para verificar os dados coletados
print(tickers)

[yfinance.Ticker object <AZTE.SA>, yfinance.Ticker object <BRAV.SA>, yfinance.Ticker object <CSAN.SA>, yfinance.Ticker object <RPMG.SA>, yfinance.Ticker object <PETR.SA>, yfinance.Ticker object <RECV.SA>, yfinance.Ticker object <PRIO.SA>, yfinance.Ticker object <RAIZ.SA>, yfinance.Ticker object <UGPA.SA>, yfinance.Ticker object <LUPA.SA>, yfinance.Ticker object <OPCT.SA>, yfinance.Ticker object <OSXB.SA>, yfinance.Ticker object <VBBR.SA>, yfinance.Ticker object <AURA.SA>, yfinance.Ticker object <BRAP.SA>, yfinance.Ticker object <CBAV.SA>, yfinance.Ticker object <CMIN.SA>, yfinance.Ticker object <LTEL.SA>, yfinance.Ticker object <LTLA.SA>, yfinance.Ticker object <VALE.SA>, yfinance.Ticker object <FESA.SA>, yfinance.Ticker object <GGBR.SA>, yfinance.Ticker object <GOAU.SA>, yfinance.Ticker object <CSNA.SA>, yfinance.Ticker object <USIM.SA>, yfinance.Ticker object <HAGA.SA>, yfinance.Ticker object <MGEL.SA>, yfinance.Ticker object <PATI.SA>, yfinance.Ticker object <TKNO.SA>, yfinance.Ticker object <PMAM.SA>, yfinance.Ticker object <BRKM.SA>, yfinance.Ticker object <DEXP.SA>, yfinance.Ticker object <FHER.SA>, yfinance.Ticker object <NUTR.SA>, yfinance.Ticker object <VITT.SA>, yfinance.Ticker object <CRPG.SA>, yfinance.Ticker object <UNIP.SA>, yfinance.Ticker object <DXCO.SA>, yfinance.Ticker object <EUCA.SA>, yfinance.Ticker object <KLBN.SA>, yfinance.Ticker object <MSPA.SA>, yfinance.Ticker object <NEMO.SA>, yfinance.Ticker object <SUZB.SA>, yfinance.Ticker object <RANI.SA>, yfinance.Ticker object <SNSY.SA>, yfinance.Ticker object <ETER.SA>, yfinance.Ticker object <PTBL.SA>, yfinance.Ticker object <AZEV.SA>, yfinance.Ticker object <SOND.SA>, yfinance.Ticker object <ARML.SA>, yfinance.Ticker object <MILS.SA>, yfinance.Ticker object <PRNR.SA>, yfinance.Ticker object <EMBJ.SA>, yfinance.Ticker object <FRAS.SA>, yfinance.Ticker object <POMO.SA>, yfinance.Ticker object <RAPT.SA>, yfinance.Ticker object <RCSL.SA>, yfinance.Ticker object <RSUL.SA>, yfinance.Ticker object <TUPY.SA>, yfinance.Ticker object <MWET.SA>, yfinance.Ticker object <SHUL.SA>, yfinance.Ticker object <WEGE.SA>, yfinance.Ticker object <EALT.SA>, yfinance.Ticker object <AERI.SA>, yfinance.Ticker object <BDLL.SA>, yfinance.Ticker object <INEP.SA>, yfinance.Ticker object <KEPL.SA>, yfinance.Ticker object <FRIO.SA>, yfinance.Ticker object <PTCA.SA>, yfinance.Ticker object <ROMI.SA>, yfinance.Ticker object <MTSA.SA>, yfinance.Ticker object <TASA.SA>, yfinance.Ticker object <AZUL.SA>, yfinance.Ticker object <GOLL.SA>, yfinance.Ticker object <VSPT.SA>, yfinance.Ticker object <MRSA.SA>, yfinance.Ticker object <RAIL.SA>, yfinance.Ticker object <HBSA.SA>, yfinance.Ticker object <LOGN.SA>, yfinance.Ticker object <LUXM.SA>, yfinance.Ticker object <JSLG.SA>, yfinance.Ticker object <SEQL.SA>, yfinance.Ticker object <TGMA.SA>, yfinance.Ticker object <CRTE.SA>, yfinance.Ticker object <ECOR.SA>, yfinance.Ticker object <MOTV.SA>, yfinance.Ticker object <TPIS.SA>, yfinance.Ticker object <AGRU.SA>, yfinance.Ticker object <HMOB.SA>, yfinance.Ticker object <IVPR.SA>, yfinance.Ticker object <PSVM.SA>, yfinance.Ticker object <BBML.SA>, yfinance.Ticker object <CTAX.SA>, yfinance.Ticker object <DTCY.SA>, yfinance.Ticker object <ALPK.SA>, yfinance.Ticker object <GGPS.SA>, yfinance.Ticker object <VLID.SA>, yfinance.Ticker object <MMAQ.SA>, yfinance.Ticker object <RBNS.SA>, yfinance.Ticker object <WLMM.SA>, yfinance.Ticker object <TTEN.SA>, yfinance.Ticker object <AGXY.SA>, yfinance.Ticker object <APTI.SA>, yfinance.Ticker object <SOJA.SA>, yfinance.Ticker object <AGRO.SA>, yfinance.Ticker object <CTCA.SA>, yfinance.Ticker object <EGGY.SA>, yfinance.Ticker object <SLCE.SA>, yfinance.Ticker object <LAND.SA>, yfinance.Ticker object <JALL.SA>, yfinance.Ticker object <SMTO.SA>, yfinance.Ticker object <BAUH.SA>, yfinance.Ticker object <FICT.SA>, yfinance.Ticker object <JBSS.SA>, yfinance.Ticker object <MBRF.SA>, yfinance.Ticker object <BEEF.SA>, yfinance.Ticker object <MNPR.SA>, yfinance.Ticker object <CAML.SA>, yfinance.Ticker object <JOPA.SA>, yfinance.Ticker object <MDIA.SA>, yfinance.Ticker object <ODER.SA>, yfinance.Ticker object <ABEV.SA>, yfinance.Ticker object <ESPA.SA>, yfinance.Ticker object <NATU.SA>, yfinance.Ticker object <BOBR.SA>, yfinance.Ticker object <ASAI.SA>, yfinance.Ticker object <GMAT.SA>, yfinance.Ticker object <PCAR.SA>, yfinance.Ticker object <AZZA.SA>, yfinance.Ticker object <CEAB.SA>, yfinance.Ticker object <CGRA.SA>, yfinance.Ticker object <AMAR.SA>, yfinance.Ticker object <LREN.SA>, yfinance.Ticker object <RIAA.SA>, yfinance.Ticker object <VSTE.SA>, yfinance.Ticker object <ALLD.SA>, yfinance.Ticker object <BHIA.SA>, yfinance.Ticker object <MGLU.SA>, yfinance.Ticker object <AMER.SA>, yfinance.Ticker object <SBFG.SA>, yfinance.Ticker object <LLBI.SA>, yfinance.Ticker object <AUAU.SA>, yfinance.Ticker object <LJQQ.SA>, yfinance.Ticker object <AVLL.SA>, yfinance.Ticker object <CALI.SA>, yfinance.Ticker object <CURY.SA>, yfinance.Ticker object <CYRE.SA>, yfinance.Ticker object <DIRR.SA>, yfinance.Ticker object <EVEN.SA>, yfinance.Ticker object <EZTC.SA>, yfinance.Ticker object <FIEI.SA>, yfinance.Ticker object <GFSA.SA>, yfinance.Ticker object <HBOR.SA>, yfinance.Ticker object <INNC.SA>, yfinance.Ticker object <JHSF.SA>, yfinance.Ticker object <JFEN.SA>, yfinance.Ticker object <KLAS.SA>, yfinance.Ticker object <LAVV.SA>, yfinance.Ticker object <MELK.SA>, yfinance.Ticker object <MTRE.SA>, yfinance.Ticker object <MDNE.SA>, yfinance.Ticker object <MRVE.SA>, yfinance.Ticker object <PDGR.SA>, yfinance.Ticker object <PLPL.SA>, yfinance.Ticker object <CCTY.SA>, yfinance.Ticker object <RSID.SA>, yfinance.Ticker object <TCSA.SA>, yfinance.Ticker object <TEND.SA>, yfinance.Ticker object <TRIS.SA>, yfinance.Ticker object <VIVR.SA>, yfinance.Ticker object <CEDO.SA>, yfinance.Ticker object <DOHL.SA>, yfinance.Ticker object <CATA.SA>, yfinance.Ticker object <CTKA.SA>, yfinance.Ticker object <PTNT.SA>, yfinance.Ticker object <CTSA.SA>, yfinance.Ticker object <TXRX.SA>, yfinance.Ticker object <TFCO.SA>, yfinance.Ticker object <ALPA.SA>, yfinance.Ticker object <CAMB.SA>, yfinance.Ticker object <GRND.SA>, yfinance.Ticker object <VULC.SA>, yfinance.Ticker object <MNDL.SA>, yfinance.Ticker object <TECN.SA>, yfinance.Ticker object <VIVA.SA>, yfinance.Ticker object <WHRL.SA>, yfinance.Ticker object <TOKY.SA>, yfinance.Ticker object <UCAS.SA>, yfinance.Ticker object <WEST.SA>, yfinance.Ticker object <HETA.SA>, yfinance.Ticker object <AMOB.SA>, yfinance.Ticker object <MYPK.SA>, yfinance.Ticker object <LEVE.SA>, yfinance.Ticker object <PLAS.SA>, yfinance.Ticker object <HOOT.SA>, yfinance.Ticker object <MEAL.SA>, yfinance.Ticker object <BMKS.SA>, yfinance.Ticker object <ESTR.SA>, yfinance.Ticker object <RVEE.SA>, yfinance.Ticker object <AHEB.SA>, yfinance.Ticker object <SHOW.SA>, yfinance.Ticker object <CVCB.SA>, yfinance.Ticker object <SMFT.SA>, yfinance.Ticker object <ANIM.SA>, yfinance.Ticker object <ATED.SA>, yfinance.Ticker object <BIED.SA>, yfinance.Ticker object <COGN.SA>, yfinance.Ticker object <CSED.SA>, yfinance.Ticker object <SALT.SA>, yfinance.Ticker object <OBTC.SA>, yfinance.Ticker object <SEER.SA>, yfinance.Ticker object <VTRU.SA>, yfinance.Ticker object <YDUQ.SA>, yfinance.Ticker object <RENT.SA>, yfinance.Ticker object <MOVI.SA>, yfinance.Ticker object <VAMO.SA>, yfinance.Ticker object <DOTZ.SA>, yfinance.Ticker object <BIOM.SA>, yfinance.Ticker object <OFSA.SA>, yfinance.Ticker object <AALR.SA>, yfinance.Ticker object <DASA.SA>, yfinance.Ticker object <FLRY.SA>, yfinance.Ticker object <HAPV.SA>, yfinance.Ticker object <MATD.SA>, yfinance.Ticker object <ODPV.SA>, yfinance.Ticker object <ONCO.SA>, yfinance.Ticker object <QUAL.SA>, yfinance.Ticker object <RDOR.SA>, yfinance.Ticker object <BALM.SA>, yfinance.Ticker object <LMED.SA>, yfinance.Ticker object <BLAU.SA>, yfinance.Ticker object <DMVF.SA>, yfinance.Ticker object <PNVL.SA>, yfinance.Ticker object <EUFA.SA>, yfinance.Ticker object <HYPE.SA>, yfinance.Ticker object <PGMN.SA>, yfinance.Ticker object <PFRM.SA>, yfinance.Ticker object <RADL.SA>, yfinance.Ticker object <VVEO.SA>, yfinance.Ticker object <INTB.SA>, yfinance.Ticker object <MLAS.SA>, yfinance.Ticker object <POSI.SA>, yfinance.Ticker object <BMOB.SA>, yfinance.Ticker object <BRQB.SA>, yfinance.Ticker object <ENJU.SA>, yfinance.Ticker object <IFCM.SA>, yfinance.Ticker object <LWSA.SA>, yfinance.Ticker object <CASH.SA>, yfinance.Ticker object <NGRD.SA>, yfinance.Ticker object <PDTC.SA>, yfinance.Ticker object <QUSW.SA>, yfinance.Ticker object <TRAD.SA>, yfinance.Ticker object <TOTS.SA>, yfinance.Ticker object <WDCN.SA>, yfinance.Ticker object <BRST.SA>, yfinance.Ticker object <DESK.SA>, yfinance.Ticker object <OIBR.SA>, yfinance.Ticker object <TELB.SA>, yfinance.Ticker object <VIVT.SA>, yfinance.Ticker object <TIMS.SA>, yfinance.Ticker object <FIQE.SA>, yfinance.Ticker object <AESO.SA>, yfinance.Ticker object <AFLT.SA>, yfinance.Ticker object <ALUP.SA>, yfinance.Ticker object <CBEE.SA>, yfinance.Ticker object <AURE.SA>, yfinance.Ticker object <AXIA.SA>, yfinance.Ticker object <CEBR.SA>, yfinance.Ticker object <CEED.SA>, yfinance.Ticker object <CLSC.SA>, yfinance.Ticker object <GPAR.SA>, yfinance.Ticker object <CMIG.SA>, yfinance.Ticker object <CEEB.SA>, yfinance.Ticker object <COCE.SA>, yfinance.Ticker object <COMR.SA>, yfinance.Ticker object <CPLE.SA>, yfinance.Ticker object <CPFE.SA>, yfinance.Ticker object <EKTR.SA>, yfinance.Ticker object <EMAE.SA>, yfinance.Ticker object <ENGI.SA>, yfinance.Ticker object <ENMT.SA>, yfinance.Ticker object <ENEV.SA>, yfinance.Ticker object <EGIE.SA>, yfinance.Ticker object <EQPA.SA>, yfinance.Ticker object <EQMA.SA>, yfinance.Ticker object <EQTL.SA>, yfinance.Ticker object <GEPA.SA>, yfinance.Ticker object <ISAE.SA>, yfinance.Ticker object <LIGH.SA>, yfinance.Ticker object <LIGT.SA>, yfinance.Ticker object <NEOE.SA>, yfinance.Ticker object <PRMN.SA>, yfinance.Ticker object <REDE.SA>, yfinance.Ticker object <RNEW.SA>, yfinance.Ticker object <RIOS.SA>, yfinance.Ticker object <TAEE.SA>, yfinance.Ticker object <AMBP.SA>, yfinance.Ticker object <CASN.SA>, yfinance.Ticker object <CSMG.SA>, yfinance.Ticker object <IGSN.SA>, yfinance.Ticker object <ORVR.SA>, yfinance.Ticker object <SBSP.SA>, yfinance.Ticker object <SAPR.SA>, yfinance.Ticker object <CEGR.SA>, yfinance.Ticker object <CGAS.SA>, yfinance.Ticker object <PASS.SA>, yfinance.Ticker object <ABCB.SA>, yfinance.Ticker object <RPAD.SA>, yfinance.Ticker object <BAZA.SA>, yfinance.Ticker object <BMGB.SA>, yfinance.Ticker object <BGIP.SA>, yfinance.Ticker object <BEES.SA>, yfinance.Ticker object <BPAR.SA>, yfinance.Ticker object <BRSR.SA>, yfinance.Ticker object <BRBI.SA>, yfinance.Ticker object <BBDC.SA>, yfinance.Ticker object <BBAS.SA>, yfinance.Ticker object <BSLI.SA>, yfinance.Ticker object <BPAC.SA>, yfinance.Ticker object <INBR.SA>, yfinance.Ticker object <ITUB.SA>, yfinance.Ticker object <BMIN.SA>, yfinance.Ticker object <BMEB.SA>, yfinance.Ticker object <BNBR.SA>, yfinance.Ticker object <PINE.SA>, yfinance.Ticker object <SANB.SA>, yfinance.Ticker object <MERC.SA>, yfinance.Ticker object <FIGE.SA>, yfinance.Ticker object <BSCS.SA>, yfinance.Ticker object <RBRA.SA>, yfinance.Ticker object <PLSC.SA>, yfinance.Ticker object <G2DI.SA>, yfinance.Ticker object <PPLA.SA>, yfinance.Ticker object <B3SA.SA>, yfinance.Ticker object <CSUD.SA>, yfinance.Ticker object <BBSE.SA>, yfinance.Ticker object <CXSE.SA>, yfinance.Ticker object <PSSA.SA>, yfinance.Ticker object <IRBR.SA>, yfinance.Ticker object <WIZC.SA>, yfinance.Ticker object <ALOS.SA>, yfinance.Ticker object <GSHP.SA>, yfinance.Ticker object <HBTS.SA>, yfinance.Ticker object <HBRE.SA>, yfinance.Ticker object <IGTI.SA>, yfinance.Ticker object <LOGG.SA>, yfinance.Ticker object <MULT.SA>, yfinance.Ticker object <NORD.SA>, yfinance.Ticker object <PEAB.SA>, yfinance.Ticker object <SCAR.SA>, yfinance.Ticker object <SYNE.SA>, yfinance.Ticker object <LPSB.SA>, yfinance.Ticker object <NEXP.SA>, yfinance.Ticker object <ARND.SA>, yfinance.Ticker object <EPAR.SA>, yfinance.Ticker object <ITSA.SA>, yfinance.Ticker object <SIMH.SA>, yfinance.Ticker object <ADMF.SA>, yfinance.Ticker object <CTBA.SA>, yfinance.Ticker object <MCRJ.SA>, yfinance.Ticker object <PMSP.SA>, yfinance.Ticker object <QVQP.SA>, yfinance.Ticker object <BETP.SA>, yfinance.Ticker object <MAPT.SA>, yfinance.Ticker object <OPGM.SA>, yfinance.Ticker object <PPAR.SA>, yfinance.Ticker object <PRPT.SA>, yfinance.Ticker object <OPSE.SA>, yfinance.Ticker object <OPTS.SA>]

In [9]:
# Consulta na API do Yahoo Finance os dados históricos de um ticker específico
ticker_exemplo = 'PETR4.SA'  # Exemplo com o primeiro ticker da lista

dados_historicos = yf.download(ticker_exemplo, start=data_marco, end=data_atual)

dados_historicos.head()  # Exibir os dados históricos para verificar a coleta

[*********************100%***********************]  1 of 1 completed

Price           Close       High        Low       Open     Volume
Ticker       PETR4.SA   PETR4.SA   PETR4.SA   PETR4.SA   PETR4.SA
Date
2023-01-02  12.971099  13.474776  12.903187  13.321976   78424700
2023-01-03  12.642861  13.072968  12.524016  12.982419   96750300
2023-01-04  13.044669  13.350271  12.354236  12.427806  129504000
2023-01-05  13.514389  13.604939  13.101261  13.208788   73886000
2023-01-06  13.435160  13.763399  13.327633  13.548346   51851500

In [10]:
# Consulta na API do Yahoo Finance as informações gerais de um ticker específico
ticker_info = 'PETR11.SA'

yf.Ticker(ticker_exemplo).info

{'address1': 'Avenida Henrique Valadares, 28',
 'city': 'Rio De Janeiro',
 'state': 'RJ',
 'zip': '20231-030',
 'country': 'Brazil',
 'phone': '55 21 3224 2401',
 'website': 'https://petrobras.com.br',
 'industry': 'Oil & Gas Integrated',
 'industryKey': 'oil-gas-integrated',
 'industryDisp': 'Oil & Gas Integrated',
 'sector': 'Energy',
 'sectorKey': 'energy',
 'sectorDisp': 'Energy',
 'longBusinessSummary': 'Petróleo Brasileiro S.A. - Petrobras explores, produces, and sells oil and gas in Brazil and internationally. It operates through three segments: Exploration and Production; Refining, Transportation & Marketing; and Gas & Low Carbon Energies. The Exploration and Production segment explores, develops, and produces crude oil, natural gas liquids, and natural gas primarily for supplies to the domestic refineries. The Refining, Transportation and Marketing segment engages in the refining, logistics, transport, acquisition, and export of crude oil; trading of oil products; and production of fertilizers, as well as holding interests in petrochemical companies. The Gas and Low Carbon Energies segment is involved in the logistic and trading of natural gas and electricity; transportation and trading of liquefied natural gas; generation of electricity through thermoelectric power plants; renewable energy business; low carbon business; and natural gas processing business, as well as production of biodiesel and its co-products. The company also engages in prospecting, drilling, refining, processing, trading, and transporting crude oil from producing onshore and offshore oil fields, and shale or other rocks, as well as oil products, natural gas, and other liquid hydrocarbons. In addition, it engages in the research, development, production, transportation, distribution, and trading of energy. The company was incorporated in 1953 and is headquartered in Rio de Janeiro, Brazil.',
 'fullTimeEmployees': 41778,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Ms. Magda Maria de Regina Chambriard',
   'title': 'CEO, Member of Executive Board & Non-Independent Director',
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Clarice  Coppetti',
   'age': 61,
   'title': 'Interim President, Chief Corporate Affairs Officer & Member of Executive Board',
   'yearBorn': 1964,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Fernando Sabbi Melgarejo',
   'title': 'Chief Financial Officer & Chief Investor Relations Officer and Member of Executive Board',
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Claudio Romeo Schlosser',
   'age': 61,
   'title': 'Chief Logistics, Commercialization & Markets Officer and Member of Executive Board',
   'yearBorn': 1964,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. William Franca da Silva',
   'age': 65,
   'title': 'Chief Industrial Processes, Products Officer and Member of Executive Board',
   'yearBorn': 1960,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Renata  Baruzzi',
   'title': 'Chief Engineering, Technology, & Innovation Officer and Member of Executive Board',
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Sylvia Maria Couto dos Anjos',
   'title': 'Chief Exploration & Production Officer and Member of Executive Board',
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Ricardo Wagner de Araujo',
   'title': 'Chief Governance & Compliance Officer and Member of Executive Board',
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Angelica Garcia Cobas Laureano',
   'title': 'Chief Energy Transition & Sustainability Officer and Member of Executive Board',
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Bruno  Motta',
   'title': 'Executive Manager of Communication & Brands',
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 4,
 'boardRisk': 2,
 'compensationRisk': 1,
 'shareHolderRightsRisk': 10,
 'overallRisk': 1,
 'governanceEpochDate': 1769904000,
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 38.59,
 'open': 38.86,
 'dayLow': 38.86,
 'dayHigh': 39.66,
 'regularMarketPreviousClose': 38.59,
 'regularMarketOpen': 38.86,
 'regularMarketDayLow': 38.86,
 'regularMarketDayHigh': 39.66,
 'dividendRate': 4.64,
 'dividendYield': 12.02,
 'exDividendDate': 1766448000,
 'payoutRatio': 0.59029996,
 'fiveYearAvgDividendYield': 21.62,
 'beta': 0.141,
 'trailingPE': 7.091398,
 'forwardPE': 3.52297,
 'volume': 43263600,
 'regularMarketVolume': 43263600,
 'averageVolume': 39131513,
 'averageVolume10days': 38435425,
 'averageDailyVolume10Day': 38435425,
 'bid': 39.56,
 'ask': 39.57,
 'bidSize': 0,
 'askSize': 0,
 'marketCap': 531724075008,
 'nonDilutedMarketCap': 414956134551,
 'fiftyTwoWeekLow': 28.86,
 'fiftyTwoWeekHigh': 39.66,
 'allTimeHigh': 67.5,
 'allTimeLow': 4.12,
 'priceToSalesTrailing12Months': 1.0819583,
 'fiftyDayAverage': 33.591,
 'twoHundredDayAverage': 31.9202,
 'trailingAnnualDividendRate': 3.364,
 'trailingAnnualDividendYield': 0.08717284,
 'currency': 'BRL',
 'tradeable': False,
 'enterpriseValue': 813485195264,
 'profitMargins': 0.15774,
 'floatShares': 8112555062,
 'sharesOutstanding': 5446501379,
 'heldPercentInsiders': 0.0,
 'heldPercentInstitutions': 0.60106,
 'impliedSharesOutstanding': 13437555928,
 'bookValue': 32.814,
 'priceToBook': 1.2058878,
 'lastFiscalYearEnd': 1735603200,
 'nextFiscalYearEnd': 1767139200,
 'mostRecentQuarter': 1759190400,
 'earningsQuarterlyGrowth': 0.005,
 'netIncomeToCommon': 77522001920,
 'trailingEps': 5.58,
 'forwardEps': 11.232,
 'lastSplitFactor': '2:1',
 'lastSplitDate': 1209340800,
 'enterpriseToRevenue': 1.655,
 'enterpriseToEbitda': 4.258,
 '52WeekChange': -0.00393492,
 'SandP52WeekChange': 0.15480888,
 'lastDividendValue': 0.952128,
 'lastDividendDate': 1766448000,
 'quoteType': 'EQUITY',
 'currentPrice': 39.57,
 'targetHighPrice': 47.0,
 'targetLowPrice': 36.6,
 'targetMeanPrice': 42.58462,
 'targetMedianPrice': 44.0,
 'recommendationMean': 2.0,
 'recommendationKey': 'buy',
 'numberOfAnalystOpinions': 13,
 'totalCash': 62001000448,
 'totalCashPerShare': 4.81,
 'ebitda': 191036997632,
 'totalDebt': 376082989056,
 'quickRatio': 0.516,
 'currentRatio': 0.819,
 'totalRevenue': 491446009856,
 'debtToEquity': 88.498,
 'revenuePerShare': 38.13,
 'returnOnAssets': 0.07919,
 'returnOnEquity': 0.19022,
 'grossProfits': 236640993280,
 'freeCashflow': 81192501248,
 'operatingCashflow': 193082998784,
 'earningsGrowth': 0.005,
 'revenueGrowth': -0.013,
 'grossMargins': 0.48152,
 'ebitdaMargins': 0.38872,
 'operatingMargins': 0.36224,
 'financialCurrency': 'BRL',
 'symbol': 'PETR4.SA',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Delayed Quote',
 'triggerable': False,
 'customPriceAlertConfidence': 'LOW',
 'corporateActions': [],
 'regularMarketTime': 1771967274,
 'hasPrePostMarketData': False,
 'firstTradeDateMilliseconds': 946900800000,
 'marketState': 'POSTPOST',
 'shortName': 'PETROBRAS   PN      N2',
 'longName': 'Petróleo Brasileiro S.A. - Petrobras',
 'exchange': 'SAO',
 'messageBoardId': 'finmb_409268',
 'exchangeTimezoneName': 'America/Sao_Paulo',
 'exchangeTimezoneShortName': 'BRT',
 'gmtOffSetMilliseconds': -10800000,
 'market': 'br_market',
 'esgPopulated': False,
 'regularMarketChangePercent': 2.5395167,
 'regularMarketPrice': 39.57,
 'cryptoTradeable': False,
 'regularMarketChange': 0.97999954,
 'regularMarketDayRange': '38.86 - 39.66',
 'fullExchangeName': 'São Paulo',
 'averageDailyVolume3Month': 39131513,
 'fiftyTwoWeekLowChange': 10.709999,
 'fiftyTwoWeekLowChangePercent': 0.37110183,
 'fiftyTwoWeekRange': '28.86 - 39.66',
 'fiftyTwoWeekHighChange': -0.09000015,
 'fiftyTwoWeekHighChangePercent': -0.0022692927,
 'fiftyTwoWeekChangePercent': -0.39349198,
 'earningsTimestampStart': 1754593200,
 'earningsTimestampEnd': 1754593200,
 'earningsCallTimestampStart': 1762513140,
 'earningsCallTimestampEnd': 1762513140,
 'isEarningsDateEstimate': False,
 'epsTrailingTwelveMonths': 5.58,
 'epsForward': 11.232,
 'fiftyDayAverageChange': 5.979,
 'fiftyDayAverageChangePercent': 0.17799412,
 'twoHundredDayAverageChange': 7.6497993,
 'twoHundredDayAverageChangePercent': 0.23965387,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 15,
 'averageAnalystRating': '2.0 - Buy',
 'trailingPegRatio': 0.2155}

In [11]:
# Buscar todos os tickers da API do Yahoo Finance que começam com os símbolos base com sequenciais de papeis ON, PN e UNITS e armazenar uma lista de tickers correspondentes
tickers_correspondentes = []
for simbolo in simbolos_base:
    ticker_on = simbolo + '3.SA'  # Ações ordinárias (ON)
    ticker_pn = simbolo + '4.SA'  # Ações preferenciais (PN)
    ticker_units = simbolo + '11.SA'  # Units
    tickers_correspondentes.extend([ticker_on, ticker_pn, ticker_units])
# Exibir os tickers correspondentes para verificar os dados coletados
print(len(tickers_correspondentes))
print(tickers_correspondentes)

1107
['AZTE3.SA', 'AZTE4.SA', 'AZTE11.SA', 'BRAV3.SA', 'BRAV4.SA', 'BRAV11.SA', 'CSAN3.SA', 'CSAN4.SA', 'CSAN11.SA', 'RPMG3.SA', 'RPMG4.SA', 'RPMG11.SA', 'PETR3.SA', 'PETR4.SA', 'PETR11.SA', 'RECV3.SA', 'RECV4.SA', 'RECV11.SA', 'PRIO3.SA', 'PRIO4.SA', 'PRIO11.SA', 'RAIZ3.SA', 'RAIZ4.SA', 'RAIZ11.SA', 'UGPA3.SA', 'UGPA4.SA', 'UGPA11.SA', 'LUPA3.SA', 'LUPA4.SA', 'LUPA11.SA', 'OPCT3.SA', 'OPCT4.SA', 'OPCT11.SA', 'OSXB3.SA', 'OSXB4.SA', 'OSXB11.SA', 'VBBR3.SA', 'VBBR4.SA', 'VBBR11.SA', 'AURA3.SA', 'AURA4.SA', 'AURA11.SA', 'BRAP3.SA', 'BRAP4.SA', 'BRAP11.SA', 'CBAV3.SA', 'CBAV4.SA', 'CBAV11.SA', 'CMIN3.SA', 'CMIN4.SA', 'CMIN11.SA', 'LTEL3.SA', 'LTEL4.SA', 'LTEL11.SA', 'LTLA3.SA', 'LTLA4.SA', 'LTLA11.SA', 'VALE3.SA', 'VALE4.SA', 'VALE11.SA', 'FESA3.SA', 'FESA4.SA', 'FESA11.SA', 'GGBR3.SA', 'GGBR4.SA', 'GGBR11.SA', 'GOAU3.SA', 'GOAU4.SA', 'GOAU11.SA', 'CSNA3.SA', 'CSNA4.SA', 'CSNA11.SA', 'USIM3.SA', 'USIM4.SA', 'USIM11.SA', 'HAGA3.SA', 'HAGA4.SA', 'HAGA11.SA', 'MGEL3.SA', 'MGEL4.SA', 'MGEL11.SA', 'PATI3.SA', 'PATI4.SA', 'PATI11.SA', 'TKNO3.SA', 'TKNO4.SA', 'TKNO11.SA', 'PMAM3.SA', 'PMAM4.SA', 'PMAM11.SA', 'BRKM3.SA', 'BRKM4.SA', 'BRKM11.SA', 'DEXP3.SA', 'DEXP4.SA', 'DEXP11.SA', 'FHER3.SA', 'FHER4.SA', 'FHER11.SA', 'NUTR3.SA', 'NUTR4.SA', 'NUTR11.SA', 'VITT3.SA', 'VITT4.SA', 'VITT11.SA', 'CRPG3.SA', 'CRPG4.SA', 'CRPG11.SA', 'UNIP3.SA', 'UNIP4.SA', 'UNIP11.SA', 'DXCO3.SA', 'DXCO4.SA', 'DXCO11.SA', 'EUCA3.SA', 'EUCA4.SA', 'EUCA11.SA', 'KLBN3.SA', 'KLBN4.SA', 'KLBN11.SA', 'MSPA3.SA', 'MSPA4.SA', 'MSPA11.SA', 'NEMO3.SA', 'NEMO4.SA', 'NEMO11.SA', 'SUZB3.SA', 'SUZB4.SA', 'SUZB11.SA', 'RANI3.SA', 'RANI4.SA', 'RANI11.SA', 'SNSY3.SA', 'SNSY4.SA', 'SNSY11.SA', 'ETER3.SA', 'ETER4.SA', 'ETER11.SA', 'PTBL3.SA', 'PTBL4.SA', 'PTBL11.SA', 'AZEV3.SA', 'AZEV4.SA', 'AZEV11.SA', 'SOND3.SA', 'SOND4.SA', 'SOND11.SA', 'ARML3.SA', 'ARML4.SA', 'ARML11.SA', 'MILS3.SA', 'MILS4.SA', 'MILS11.SA', 'PRNR3.SA', 'PRNR4.SA', 'PRNR11.SA', 'EMBJ3.SA', 'EMBJ4.SA', 'EMBJ11.SA', 'FRAS3.SA', 'FRAS4.SA', 'FRAS11.SA', 'POMO3.SA', 'POMO4.SA', 'POMO11.SA', 'RAPT3.SA', 'RAPT4.SA', 'RAPT11.SA', 'RCSL3.SA', 'RCSL4.SA', 'RCSL11.SA', 'RSUL3.SA', 'RSUL4.SA', 'RSUL11.SA', 'TUPY3.SA', 'TUPY4.SA', 'TUPY11.SA', 'MWET3.SA', 'MWET4.SA', 'MWET11.SA', 'SHUL3.SA', 'SHUL4.SA', 'SHUL11.SA', 'WEGE3.SA', 'WEGE4.SA', 'WEGE11.SA', 'EALT3.SA', 'EALT4.SA', 'EALT11.SA', 'AERI3.SA', 'AERI4.SA', 'AERI11.SA', 'BDLL3.SA', 'BDLL4.SA', 'BDLL11.SA', 'INEP3.SA', 'INEP4.SA', 'INEP11.SA', 'KEPL3.SA', 'KEPL4.SA', 'KEPL11.SA', 'FRIO3.SA', 'FRIO4.SA', 'FRIO11.SA', 'PTCA3.SA', 'PTCA4.SA', 'PTCA11.SA', 'ROMI3.SA', 'ROMI4.SA', 'ROMI11.SA', 'MTSA3.SA', 'MTSA4.SA', 'MTSA11.SA', 'TASA3.SA', 'TASA4.SA', 'TASA11.SA', 'AZUL3.SA', 'AZUL4.SA', 'AZUL11.SA', 'GOLL3.SA', 'GOLL4.SA', 'GOLL11.SA', 'VSPT3.SA', 'VSPT4.SA', 'VSPT11.SA', 'MRSA3.SA', 'MRSA4.SA', 'MRSA11.SA', 'RAIL3.SA', 'RAIL4.SA', 'RAIL11.SA', 'HBSA3.SA', 'HBSA4.SA', 'HBSA11.SA', 'LOGN3.SA', 'LOGN4.SA', 'LOGN11.SA', 'LUXM3.SA', 'LUXM4.SA', 'LUXM11.SA', 'JSLG3.SA', 'JSLG4.SA', 'JSLG11.SA', 'SEQL3.SA', 'SEQL4.SA', 'SEQL11.SA', 'TGMA3.SA', 'TGMA4.SA', 'TGMA11.SA', 'CRTE3.SA', 'CRTE4.SA', 'CRTE11.SA', 'ECOR3.SA', 'ECOR4.SA', 'ECOR11.SA', 'MOTV3.SA', 'MOTV4.SA', 'MOTV11.SA', 'TPIS3.SA', 'TPIS4.SA', 'TPIS11.SA', 'AGRU3.SA', 'AGRU4.SA', 'AGRU11.SA', 'HMOB3.SA', 'HMOB4.SA', 'HMOB11.SA', 'IVPR3.SA', 'IVPR4.SA', 'IVPR11.SA', 'PSVM3.SA', 'PSVM4.SA', 'PSVM11.SA', 'BBML3.SA', 'BBML4.SA', 'BBML11.SA', 'CTAX3.SA', 'CTAX4.SA', 'CTAX11.SA', 'DTCY3.SA', 'DTCY4.SA', 'DTCY11.SA', 'ALPK3.SA', 'ALPK4.SA', 'ALPK11.SA', 'GGPS3.SA', 'GGPS4.SA', 'GGPS11.SA', 'VLID3.SA', 'VLID4.SA', 'VLID11.SA', 'MMAQ3.SA', 'MMAQ4.SA', 'MMAQ11.SA', 'RBNS3.SA', 'RBNS4.SA', 'RBNS11.SA', 'WLMM3.SA', 'WLMM4.SA', 'WLMM11.SA', 'TTEN3.SA', 'TTEN4.SA', 'TTEN11.SA', 'AGXY3.SA', 'AGXY4.SA', 'AGXY11.SA', 'APTI3.SA', 'APTI4.SA', 'APTI11.SA', 'SOJA3.SA', 'SOJA4.SA', 'SOJA11.SA', 'AGRO3.SA', 'AGRO4.SA', 'AGRO11.SA', 'CTCA3.SA', 'CTCA4.SA', 'CTCA11.SA', 'EGGY3.SA', 'EGGY4.SA', 'EGGY11.SA', 'SLCE3.SA', 'SLCE4.SA', 'SLCE11.SA', 'LAND3.SA', 'LAND4.SA', 'LAND11.SA', 'JALL3.SA', 'JALL4.SA', 'JALL11.SA', 'SMTO3.SA', 'SMTO4.SA', 'SMTO11.SA', 'BAUH3.SA', 'BAUH4.SA', 'BAUH11.SA', 'FICT3.SA', 'FICT4.SA', 'FICT11.SA', 'JBSS3.SA', 'JBSS4.SA', 'JBSS11.SA', 'MBRF3.SA', 'MBRF4.SA', 'MBRF11.SA', 'BEEF3.SA', 'BEEF4.SA', 'BEEF11.SA', 'MNPR3.SA', 'MNPR4.SA', 'MNPR11.SA', 'CAML3.SA', 'CAML4.SA', 'CAML11.SA', 'JOPA3.SA', 'JOPA4.SA', 'JOPA11.SA', 'MDIA3.SA', 'MDIA4.SA', 'MDIA11.SA', 'ODER3.SA', 'ODER4.SA', 'ODER11.SA', 'ABEV3.SA', 'ABEV4.SA', 'ABEV11.SA', 'ESPA3.SA', 'ESPA4.SA', 'ESPA11.SA', 'NATU3.SA', 'NATU4.SA', 'NATU11.SA', 'BOBR3.SA', 'BOBR4.SA', 'BOBR11.SA', 'ASAI3.SA', 'ASAI4.SA', 'ASAI11.SA', 'GMAT3.SA', 'GMAT4.SA', 'GMAT11.SA', 'PCAR3.SA', 'PCAR4.SA', 'PCAR11.SA', 'AZZA3.SA', 'AZZA4.SA', 'AZZA11.SA', 'CEAB3.SA', 'CEAB4.SA', 'CEAB11.SA', 'CGRA3.SA', 'CGRA4.SA', 'CGRA11.SA', 'AMAR3.SA', 'AMAR4.SA', 'AMAR11.SA', 'LREN3.SA', 'LREN4.SA', 'LREN11.SA', 'RIAA3.SA', 'RIAA4.SA', 'RIAA11.SA', 'VSTE3.SA', 'VSTE4.SA', 'VSTE11.SA', 'ALLD3.SA', 'ALLD4.SA', 'ALLD11.SA', 'BHIA3.SA', 'BHIA4.SA', 'BHIA11.SA', 'MGLU3.SA', 'MGLU4.SA', 'MGLU11.SA', 'AMER3.SA', 'AMER4.SA', 'AMER11.SA', 'SBFG3.SA', 'SBFG4.SA', 'SBFG11.SA', 'LLBI3.SA', 'LLBI4.SA', 'LLBI11.SA', 'AUAU3.SA', 'AUAU4.SA', 'AUAU11.SA', 'LJQQ3.SA', 'LJQQ4.SA', 'LJQQ11.SA', 'AVLL3.SA', 'AVLL4.SA', 'AVLL11.SA', 'CALI3.SA', 'CALI4.SA', 'CALI11.SA', 'CURY3.SA', 'CURY4.SA', 'CURY11.SA', 'CYRE3.SA', 'CYRE4.SA', 'CYRE11.SA', 'DIRR3.SA', 'DIRR4.SA', 'DIRR11.SA', 'EVEN3.SA', 'EVEN4.SA', 'EVEN11.SA', 'EZTC3.SA', 'EZTC4.SA', 'EZTC11.SA', 'FIEI3.SA', 'FIEI4.SA', 'FIEI11.SA', 'GFSA3.SA', 'GFSA4.SA', 'GFSA11.SA', 'HBOR3.SA', 'HBOR4.SA', 'HBOR11.SA', 'INNC3.SA', 'INNC4.SA', 'INNC11.SA', 'JHSF3.SA', 'JHSF4.SA', 'JHSF11.SA', 'JFEN3.SA', 'JFEN4.SA', 'JFEN11.SA', 'KLAS3.SA', 'KLAS4.SA', 'KLAS11.SA', 'LAVV3.SA', 'LAVV4.SA', 'LAVV11.SA', 'MELK3.SA', 'MELK4.SA', 'MELK11.SA', 'MTRE3.SA', 'MTRE4.SA', 'MTRE11.SA', 'MDNE3.SA', 'MDNE4.SA', 'MDNE11.SA', 'MRVE3.SA', 'MRVE4.SA', 'MRVE11.SA', 'PDGR3.SA', 'PDGR4.SA', 'PDGR11.SA', 'PLPL3.SA', 'PLPL4.SA', 'PLPL11.SA', 'CCTY3.SA', 'CCTY4.SA', 'CCTY11.SA', 'RSID3.SA', 'RSID4.SA', 'RSID11.SA', 'TCSA3.SA', 'TCSA4.SA', 'TCSA11.SA', 'TEND3.SA', 'TEND4.SA', 'TEND11.SA', 'TRIS3.SA', 'TRIS4.SA', 'TRIS11.SA', 'VIVR3.SA', 'VIVR4.SA', 'VIVR11.SA', 'CEDO3.SA', 'CEDO4.SA', 'CEDO11.SA', 'DOHL3.SA', 'DOHL4.SA', 'DOHL11.SA', 'CATA3.SA', 'CATA4.SA', 'CATA11.SA', 'CTKA3.SA', 'CTKA4.SA', 'CTKA11.SA', 'PTNT3.SA', 'PTNT4.SA', 'PTNT11.SA', 'CTSA3.SA', 'CTSA4.SA', 'CTSA11.SA', 'TXRX3.SA', 'TXRX4.SA', 'TXRX11.SA', 'TFCO3.SA', 'TFCO4.SA', 'TFCO11.SA', 'ALPA3.SA', 'ALPA4.SA', 'ALPA11.SA', 'CAMB3.SA', 'CAMB4.SA', 'CAMB11.SA', 'GRND3.SA', 'GRND4.SA', 'GRND11.SA', 'VULC3.SA', 'VULC4.SA', 'VULC11.SA', 'MNDL3.SA', 'MNDL4.SA', 'MNDL11.SA', 'TECN3.SA', 'TECN4.SA', 'TECN11.SA', 'VIVA3.SA', 'VIVA4.SA', 'VIVA11.SA', 'WHRL3.SA', 'WHRL4.SA', 'WHRL11.SA', 'TOKY3.SA', 'TOKY4.SA', 'TOKY11.SA', 'UCAS3.SA', 'UCAS4.SA', 'UCAS11.SA', 'WEST3.SA', 'WEST4.SA', 'WEST11.SA', 'HETA3.SA', 'HETA4.SA', 'HETA11.SA', 'AMOB3.SA', 'AMOB4.SA', 'AMOB11.SA', 'MYPK3.SA', 'MYPK4.SA', 'MYPK11.SA', 'LEVE3.SA', 'LEVE4.SA', 'LEVE11.SA', 'PLAS3.SA', 'PLAS4.SA', 'PLAS11.SA', 'HOOT3.SA', 'HOOT4.SA', 'HOOT11.SA', 'MEAL3.SA', 'MEAL4.SA', 'MEAL11.SA', 'BMKS3.SA', 'BMKS4.SA', 'BMKS11.SA', 'ESTR3.SA', 'ESTR4.SA', 'ESTR11.SA', 'RVEE3.SA', 'RVEE4.SA', 'RVEE11.SA', 'AHEB3.SA', 'AHEB4.SA', 'AHEB11.SA', 'SHOW3.SA', 'SHOW4.SA', 'SHOW11.SA', 'CVCB3.SA', 'CVCB4.SA', 'CVCB11.SA', 'SMFT3.SA', 'SMFT4.SA', 'SMFT11.SA', 'ANIM3.SA', 'ANIM4.SA', 'ANIM11.SA', 'ATED3.SA', 'ATED4.SA', 'ATED11.SA', 'BIED3.SA', 'BIED4.SA', 'BIED11.SA', 'COGN3.SA', 'COGN4.SA', 'COGN11.SA', 'CSED3.SA', 'CSED4.SA', 'CSED11.SA', 'SALT3.SA', 'SALT4.SA', 'SALT11.SA', 'OBTC3.SA', 'OBTC4.SA', 'OBTC11.SA', 'SEER3.SA', 'SEER4.SA', 'SEER11.SA', 'VTRU3.SA', 'VTRU4.SA', 'VTRU11.SA', 'YDUQ3.SA', 'YDUQ4.SA', 'YDUQ11.SA', 'RENT3.SA', 'RENT4.SA', 'RENT11.SA', 'MOVI3.SA', 'MOVI4.SA', 'MOVI11.SA', 'VAMO3.SA', 'VAMO4.SA', 'VAMO11.SA', 'DOTZ3.SA', 'DOTZ4.SA', 'DOTZ11.SA', 'BIOM3.SA', 'BIOM4.SA', 'BIOM11.SA', 'OFSA3.SA', 'OFSA4.SA', 'OFSA11.SA', 'AALR3.SA', 'AALR4.SA', 'AALR11.SA', 'DASA3.SA', 'DASA4.SA', 'DASA11.SA', 'FLRY3.SA', 'FLRY4.SA', 'FLRY11.SA', 'HAPV3.SA', 'HAPV4.SA', 'HAPV11.SA', 'MATD3.SA', 'MATD4.SA', 'MATD11.SA', 'ODPV3.SA', 'ODPV4.SA', 'ODPV11.SA', 'ONCO3.SA', 'ONCO4.SA', 'ONCO11.SA', 'QUAL3.SA', 'QUAL4.SA', 'QUAL11.SA', 'RDOR3.SA', 'RDOR4.SA', 'RDOR11.SA', 'BALM3.SA', 'BALM4.SA', 'BALM11.SA', 'LMED3.SA', 'LMED4.SA', 'LMED11.SA', 'BLAU3.SA', 'BLAU4.SA', 'BLAU11.SA', 'DMVF3.SA', 'DMVF4.SA', 'DMVF11.SA', 'PNVL3.SA', 'PNVL4.SA', 'PNVL11.SA', 'EUFA3.SA', 'EUFA4.SA', 'EUFA11.SA', 'HYPE3.SA', 'HYPE4.SA', 'HYPE11.SA', 'PGMN3.SA', 'PGMN4.SA', 'PGMN11.SA', 'PFRM3.SA', 'PFRM4.SA', 'PFRM11.SA', 'RADL3.SA', 'RADL4.SA', 'RADL11.SA', 'VVEO3.SA', 'VVEO4.SA', 'VVEO11.SA', 'INTB3.SA', 'INTB4.SA', 'INTB11.SA', 'MLAS3.SA', 'MLAS4.SA', 'MLAS11.SA', 'POSI3.SA', 'POSI4.SA', 'POSI11.SA', 'BMOB3.SA', 'BMOB4.SA', 'BMOB11.SA', 'BRQB3.SA', 'BRQB4.SA', 'BRQB11.SA', 'ENJU3.SA', 'ENJU4.SA', 'ENJU11.SA', 'IFCM3.SA', 'IFCM4.SA', 'IFCM11.SA', 'LWSA3.SA', 'LWSA4.SA', 'LWSA11.SA', 'CASH3.SA', 'CASH4.SA', 'CASH11.SA', 'NGRD3.SA', 'NGRD4.SA', 'NGRD11.SA', 'PDTC3.SA', 'PDTC4.SA', 'PDTC11.SA', 'QUSW3.SA', 'QUSW4.SA', 'QUSW11.SA', 'TRAD3.SA', 'TRAD4.SA', 'TRAD11.SA', 'TOTS3.SA', 'TOTS4.SA', 'TOTS11.SA', 'WDCN3.SA', 'WDCN4.SA', 'WDCN11.SA', 'BRST3.SA', 'BRST4.SA', 'BRST11.SA', 'DESK3.SA', 'DESK4.SA', 'DESK11.SA', 'OIBR3.SA', 'OIBR4.SA', 'OIBR11.SA', 'TELB3.SA', 'TELB4.SA', 'TELB11.SA', 'VIVT3.SA', 'VIVT4.SA', 'VIVT11.SA', 'TIMS3.SA', 'TIMS4.SA', 'TIMS11.SA', 'FIQE3.SA', 'FIQE4.SA', 'FIQE11.SA', 'AESO3.SA', 'AESO4.SA', 'AESO11.SA', 'AFLT3.SA', 'AFLT4.SA', 'AFLT11.SA', 'ALUP3.SA', 'ALUP4.SA', 'ALUP11.SA', 'CBEE3.SA', 'CBEE4.SA', 'CBEE11.SA', 'AURE3.SA', 'AURE4.SA', 'AURE11.SA', 'AXIA3.SA', 'AXIA4.SA', 'AXIA11.SA', 'CEBR3.SA', 'CEBR4.SA', 'CEBR11.SA', 'CEED3.SA', 'CEED4.SA', 'CEED11.SA', 'CLSC3.SA', 'CLSC4.SA', 'CLSC11.SA', 'GPAR3.SA', 'GPAR4.SA', 'GPAR11.SA', 'CMIG3.SA', 'CMIG4.SA', 'CMIG11.SA', 'CEEB3.SA', 'CEEB4.SA', 'CEEB11.SA', 'COCE3.SA', 'COCE4.SA', 'COCE11.SA', 'COMR3.SA', 'COMR4.SA', 'COMR11.SA', 'CPLE3.SA', 'CPLE4.SA', 'CPLE11.SA', 'CPFE3.SA', 'CPFE4.SA', 'CPFE11.SA', 'EKTR3.SA', 'EKTR4.SA', 'EKTR11.SA', 'EMAE3.SA', 'EMAE4.SA', 'EMAE11.SA', 'ENGI3.SA', 'ENGI4.SA', 'ENGI11.SA', 'ENMT3.SA', 'ENMT4.SA', 'ENMT11.SA', 'ENEV3.SA', 'ENEV4.SA', 'ENEV11.SA', 'EGIE3.SA', 'EGIE4.SA', 'EGIE11.SA', 'EQPA3.SA', 'EQPA4.SA', 'EQPA11.SA', 'EQMA3.SA', 'EQMA4.SA', 'EQMA11.SA', 'EQTL3.SA', 'EQTL4.SA', 'EQTL11.SA', 'GEPA3.SA', 'GEPA4.SA', 'GEPA11.SA', 'ISAE3.SA', 'ISAE4.SA', 'ISAE11.SA', 'LIGH3.SA', 'LIGH4.SA', 'LIGH11.SA', 'LIGT3.SA', 'LIGT4.SA', 'LIGT11.SA', 'NEOE3.SA', 'NEOE4.SA', 'NEOE11.SA', 'PRMN3.SA', 'PRMN4.SA', 'PRMN11.SA', 'REDE3.SA', 'REDE4.SA', 'REDE11.SA', 'RNEW3.SA', 'RNEW4.SA', 'RNEW11.SA', 'RIOS3.SA', 'RIOS4.SA', 'RIOS11.SA', 'TAEE3.SA', 'TAEE4.SA', 'TAEE11.SA', 'AMBP3.SA', 'AMBP4.SA', 'AMBP11.SA', 'CASN3.SA', 'CASN4.SA', 'CASN11.SA', 'CSMG3.SA', 'CSMG4.SA', 'CSMG11.SA', 'IGSN3.SA', 'IGSN4.SA', 'IGSN11.SA', 'ORVR3.SA', 'ORVR4.SA', 'ORVR11.SA', 'SBSP3.SA', 'SBSP4.SA', 'SBSP11.SA', 'SAPR3.SA', 'SAPR4.SA', 'SAPR11.SA', 'CEGR3.SA', 'CEGR4.SA', 'CEGR11.SA', 'CGAS3.SA', 'CGAS4.SA', 'CGAS11.SA', 'PASS3.SA', 'PASS4.SA', 'PASS11.SA', 'ABCB3.SA', 'ABCB4.SA', 'ABCB11.SA', 'RPAD3.SA', 'RPAD4.SA', 'RPAD11.SA', 'BAZA3.SA', 'BAZA4.SA', 'BAZA11.SA', 'BMGB3.SA', 'BMGB4.SA', 'BMGB11.SA', 'BGIP3.SA', 'BGIP4.SA', 'BGIP11.SA', 'BEES3.SA', 'BEES4.SA', 'BEES11.SA', 'BPAR3.SA', 'BPAR4.SA', 'BPAR11.SA', 'BRSR3.SA', 'BRSR4.SA', 'BRSR11.SA', 'BRBI3.SA', 'BRBI4.SA', 'BRBI11.SA', 'BBDC3.SA', 'BBDC4.SA', 'BBDC11.SA', 'BBAS3.SA', 'BBAS4.SA', 'BBAS11.SA', 'BSLI3.SA', 'BSLI4.SA', 'BSLI11.SA', 'BPAC3.SA', 'BPAC4.SA', 'BPAC11.SA', 'INBR3.SA', 'INBR4.SA', 'INBR11.SA', 'ITUB3.SA', 'ITUB4.SA', 'ITUB11.SA', 'BMIN3.SA', 'BMIN4.SA', 'BMIN11.SA', 'BMEB3.SA', 'BMEB4.SA', 'BMEB11.SA', 'BNBR3.SA', 'BNBR4.SA', 'BNBR11.SA', 'PINE3.SA', 'PINE4.SA', 'PINE11.SA', 'SANB3.SA', 'SANB4.SA', 'SANB11.SA', 'MERC3.SA', 'MERC4.SA', 'MERC11.SA', 'FIGE3.SA', 'FIGE4.SA', 'FIGE11.SA', 'BSCS3.SA', 'BSCS4.SA', 'BSCS11.SA', 'RBRA3.SA', 'RBRA4.SA', 'RBRA11.SA', 'PLSC3.SA', 'PLSC4.SA', 'PLSC11.SA', 'G2DI3.SA', 'G2DI4.SA', 'G2DI11.SA', 'PPLA3.SA', 'PPLA4.SA', 'PPLA11.SA', 'B3SA3.SA', 'B3SA4.SA', 'B3SA11.SA', 'CSUD3.SA', 'CSUD4.SA', 'CSUD11.SA', 'BBSE3.SA', 'BBSE4.SA', 'BBSE11.SA', 'CXSE3.SA', 'CXSE4.SA', 'CXSE11.SA', 'PSSA3.SA', 'PSSA4.SA', 'PSSA11.SA', 'IRBR3.SA', 'IRBR4.SA', 'IRBR11.SA', 'WIZC3.SA', 'WIZC4.SA', 'WIZC11.SA', 'ALOS3.SA', 'ALOS4.SA', 'ALOS11.SA', 'GSHP3.SA', 'GSHP4.SA', 'GSHP11.SA', 'HBTS3.SA', 'HBTS4.SA', 'HBTS11.SA', 'HBRE3.SA', 'HBRE4.SA', 'HBRE11.SA', 'IGTI3.SA', 'IGTI4.SA', 'IGTI11.SA', 'LOGG3.SA', 'LOGG4.SA', 'LOGG11.SA', 'MULT3.SA', 'MULT4.SA', 'MULT11.SA', 'NORD3.SA', 'NORD4.SA', 'NORD11.SA', 'PEAB3.SA', 'PEAB4.SA', 'PEAB11.SA', 'SCAR3.SA', 'SCAR4.SA', 'SCAR11.SA', 'SYNE3.SA', 'SYNE4.SA', 'SYNE11.SA', 'LPSB3.SA', 'LPSB4.SA', 'LPSB11.SA', 'NEXP3.SA', 'NEXP4.SA', 'NEXP11.SA', 'ARND3.SA', 'ARND4.SA', 'ARND11.SA', 'EPAR3.SA', 'EPAR4.SA', 'EPAR11.SA', 'ITSA3.SA', 'ITSA4.SA', 'ITSA11.SA', 'SIMH3.SA', 'SIMH4.SA', 'SIMH11.SA', 'ADMF3.SA', 'ADMF4.SA', 'ADMF11.SA', 'CTBA3.SA', 'CTBA4.SA', 'CTBA11.SA', 'MCRJ3.SA', 'MCRJ4.SA', 'MCRJ11.SA', 'PMSP3.SA', 'PMSP4.SA', 'PMSP11.SA', 'QVQP3.SA', 'QVQP4.SA', 'QVQP11.SA', 'BETP3.SA', 'BETP4.SA', 'BETP11.SA', 'MAPT3.SA', 'MAPT4.SA', 'MAPT11.SA', 'OPGM3.SA', 'OPGM4.SA', 'OPGM11.SA', 'PPAR3.SA', 'PPAR4.SA', 'PPAR11.SA', 'PRPT3.SA', 'PRPT4.SA', 'PRPT11.SA', 'OPSE3.SA', 'OPSE4.SA', 'OPSE11.SA', 'OPTS3.SA', 'OPTS4.SA', 'OPTS11.SA']

In [ ]:
# Verificar quais tickers correspondentes existem na API do Yahoo Finance e armazenar os tickers válidos em uma nova lista
tickers_validos = []
for ticker in tickers_correspondentes:
    try:
        yf.Ticker(ticker).info  # Verificar se o ticker existe na API do Yahoo Finance
        tickers_validos.append(ticker)  # Adicionar o ticker válido à lista
    except Exception as e:
        print(f"Ticker {ticker} não encontrado: {e}")  # Imprimir mensagem de erro para tickers não encontrados

In [ ]:
# Exibir os tickers válidos para verificar os dados coletados
print(len(tickers_validos))
print(tickers_validos)

-----------------------------------------------

#### Função para gerar os tickers a partir de um arquivo Excel

In [12]:
# Biblioteca para validar os tickers usando a API do Yahoo Finance
import yfinance as yf
from datetime import datetime, timedelta
import pandas as pd
import warnings

In [13]:
# Função para gerar a lista de tickers do Yahoo Finance
def gerar_tickers_yf(caminho_arquivo, planilha='Setor', colunas_intervalo='B:H', 
                    pula_linhas=2, numero_linhas=370):
    """
    Gera uma lista de tickers do Yahoo Finance a partir de um arquivo Excel com dados da B3.
    
    Esta função lê um arquivo Excel contendo informações de empresas listadas na B3
    e gera tickers correspondentes para as três classes de ações: Ordinárias (ON),
    Preferenciais (PN) e Units. Os tickers gerados seguem o padrão do Yahoo Finance.
    
    Parâmetros
    ----------
    caminho_arquivo : str
        Caminho completo ou relativo do arquivo Excel contendo dados das empresas e setores.
    planilha : str, optional
        Nome da aba/planilha no arquivo Excel (padrão: 'Setor').
    colunas_intervalo : str, optional
        Intervalo de colunas a ler no formato Excel (padrão: 'B:H').
        Exemplo: 'A:E' ou 'B:H'.
    pula_linhas : int, optional
        Número de linhas iniciais a pular na leitura (padrão: 2).
        Útil para ignorar cabeçalhos ou informações adicionais.
    numero_linhas : int, optional
        Número máximo de linhas de dados a ler (padrão: 370).
    
    Returno
    -------
    list
        Lista contendo tickers do Yahoo Finance no formato 'CÓDIGO#.SA', onde:
        - CÓDIGO#3.SA : Ações Ordinárias (ON)
        - CÓDIGO#4.SA : Ações Preferenciais (PN)
        - CÓDIGO#11.SA : Units
    
    Notas
    -----
    - O arquivo Excel deve conter uma coluna chamada 'CÓDIGO' que será usada como índice.
    - Cada símbolo base gera 3 tickers (ON, PN e Units).
    - O sufixo '.SA' é adicionado automaticamente para indicar ações da bolsa brasileira no Yahoo Finance.
    """
    # DataFrame para armazenar os dados coletados
    df_b3_empresas_setor = pd.read_excel(
                            io=caminho_arquivo, 
                            sheet_name=planilha,
                            usecols=colunas_intervalo,
                            skiprows=pula_linhas,
                            nrows=numero_linhas,
                            index_col='CÓDIGO'
                            )

    # Símbolos base dos papeis negociados na B3
    simbolos_base_b3 = df_b3_empresas_setor.index.tolist()

    # Gerar os tickers correspondentes para cada símbolo base, 
    # considerando as diferentes classes de ações (ON, PN, Units)
    tickers_yf = []
    for simbolo in simbolos_base_b3:
        ticker_on = simbolo + '3.SA'  # Ações ordinárias (ON)
        ticker_pn = simbolo + '4.SA'  # Ações preferenciais (PN)
        ticker_units = simbolo + '11.SA'  # Units
        tickers_yf.extend([ticker_on, ticker_pn, ticker_units])
    
    return tickers_yf

In [15]:
# Localização do arquivo base de setores e empresas listadas na B3
caminho_arquivo_b3 = "../utils/gera_tikers/"
arquivo_acoes_b3 = "B3_Empresas_Setor_20260206.xlsx"
arquivo_completo = caminho_arquivo_b3 + arquivo_acoes_b3

# Gerar a lista de tickers do Yahoo Finance a partir do arquivo Excel
lista_tickers_yf = gerar_tickers_yf(arquivo_completo)

# Exibir a quantidade total de tickers gerados e a lista completa
print("==============================================================")
print("Gerando a lista de tickers do Yahoo Finance a partir do arquivo Excel...")
print(f"Arquivo Excel utilizado: {arquivo_completo}")
print(f"A quantidade total de tickers gerados é: {len(lista_tickers_yf)}")
print(lista_tickers_yf)
print("==============================================================")

==============================================================
Gerando a lista de tickers do Yahoo Finance a partir do arquivo Excel...
Arquivo Excel utilizado: ../utils/gera_tikers/B3_Empresas_Setor_20260206.xlsx
A quantidade total de tickers gerados é: 1107
['AZTE3.SA', 'AZTE4.SA', 'AZTE11.SA', 'BRAV3.SA', 'BRAV4.SA', 'BRAV11.SA', 'CSAN3.SA', 'CSAN4.SA', 'CSAN11.SA', 'RPMG3.SA', 'RPMG4.SA', 'RPMG11.SA', 'PETR3.SA', 'PETR4.SA', 'PETR11.SA', 'RECV3.SA', 'RECV4.SA', 'RECV11.SA', 'PRIO3.SA', 'PRIO4.SA', 'PRIO11.SA', 'RAIZ3.SA', 'RAIZ4.SA', 'RAIZ11.SA', 'UGPA3.SA', 'UGPA4.SA', 'UGPA11.SA', 'LUPA3.SA', 'LUPA4.SA', 'LUPA11.SA', 'OPCT3.SA', 'OPCT4.SA', 'OPCT11.SA', 'OSXB3.SA', 'OSXB4.SA', 'OSXB11.SA', 'VBBR3.SA', 'VBBR4.SA', 'VBBR11.SA', 'AURA3.SA', 'AURA4.SA', 'AURA11.SA', 'BRAP3.SA', 'BRAP4.SA', 'BRAP11.SA', 'CBAV3.SA', 'CBAV4.SA', 'CBAV11.SA', 'CMIN3.SA', 'CMIN4.SA', 'CMIN11.SA', 'LTEL3.SA', 'LTEL4.SA', 'LTEL11.SA', 'LTLA3.SA', 'LTLA4.SA', 'LTLA11.SA', 'VALE3.SA', 'VALE4.SA', 'VALE11.SA', 'FESA3.SA', 'FESA4.SA', 'FESA11.SA', 'GGBR3.SA', 'GGBR4.SA', 'GGBR11.SA', 'GOAU3.SA', 'GOAU4.SA', 'GOAU11.SA', 'CSNA3.SA', 'CSNA4.SA', 'CSNA11.SA', 'USIM3.SA', 'USIM4.SA', 'USIM11.SA', 'HAGA3.SA', 'HAGA4.SA', 'HAGA11.SA', 'MGEL3.SA', 'MGEL4.SA', 'MGEL11.SA', 'PATI3.SA', 'PATI4.SA', 'PATI11.SA', 'TKNO3.SA', 'TKNO4.SA', 'TKNO11.SA', 'PMAM3.SA', 'PMAM4.SA', 'PMAM11.SA', 'BRKM3.SA', 'BRKM4.SA', 'BRKM11.SA', 'DEXP3.SA', 'DEXP4.SA', 'DEXP11.SA', 'FHER3.SA', 'FHER4.SA', 'FHER11.SA', 'NUTR3.SA', 'NUTR4.SA', 'NUTR11.SA', 'VITT3.SA', 'VITT4.SA', 'VITT11.SA', 'CRPG3.SA', 'CRPG4.SA', 'CRPG11.SA', 'UNIP3.SA', 'UNIP4.SA', 'UNIP11.SA', 'DXCO3.SA', 'DXCO4.SA', 'DXCO11.SA', 'EUCA3.SA', 'EUCA4.SA', 'EUCA11.SA', 'KLBN3.SA', 'KLBN4.SA', 'KLBN11.SA', 'MSPA3.SA', 'MSPA4.SA', 'MSPA11.SA', 'NEMO3.SA', 'NEMO4.SA', 'NEMO11.SA', 'SUZB3.SA', 'SUZB4.SA', 'SUZB11.SA', 'RANI3.SA', 'RANI4.SA', 'RANI11.SA', 'SNSY3.SA', 'SNSY4.SA', 'SNSY11.SA', 'ETER3.SA', 'ETER4.SA', 'ETER11.SA', 'PTBL3.SA', 'PTBL4.SA', 'PTBL11.SA', 'AZEV3.SA', 'AZEV4.SA', 'AZEV11.SA', 'SOND3.SA', 'SOND4.SA', 'SOND11.SA', 'ARML3.SA', 'ARML4.SA', 'ARML11.SA', 'MILS3.SA', 'MILS4.SA', 'MILS11.SA', 'PRNR3.SA', 'PRNR4.SA', 'PRNR11.SA', 'EMBJ3.SA', 'EMBJ4.SA', 'EMBJ11.SA', 'FRAS3.SA', 'FRAS4.SA', 'FRAS11.SA', 'POMO3.SA', 'POMO4.SA', 'POMO11.SA', 'RAPT3.SA', 'RAPT4.SA', 'RAPT11.SA', 'RCSL3.SA', 'RCSL4.SA', 'RCSL11.SA', 'RSUL3.SA', 'RSUL4.SA', 'RSUL11.SA', 'TUPY3.SA', 'TUPY4.SA', 'TUPY11.SA', 'MWET3.SA', 'MWET4.SA', 'MWET11.SA', 'SHUL3.SA', 'SHUL4.SA', 'SHUL11.SA', 'WEGE3.SA', 'WEGE4.SA', 'WEGE11.SA', 'EALT3.SA', 'EALT4.SA', 'EALT11.SA', 'AERI3.SA', 'AERI4.SA', 'AERI11.SA', 'BDLL3.SA', 'BDLL4.SA', 'BDLL11.SA', 'INEP3.SA', 'INEP4.SA', 'INEP11.SA', 'KEPL3.SA', 'KEPL4.SA', 'KEPL11.SA', 'FRIO3.SA', 'FRIO4.SA', 'FRIO11.SA', 'PTCA3.SA', 'PTCA4.SA', 'PTCA11.SA', 'ROMI3.SA', 'ROMI4.SA', 'ROMI11.SA', 'MTSA3.SA', 'MTSA4.SA', 'MTSA11.SA', 'TASA3.SA', 'TASA4.SA', 'TASA11.SA', 'AZUL3.SA', 'AZUL4.SA', 'AZUL11.SA', 'GOLL3.SA', 'GOLL4.SA', 'GOLL11.SA', 'VSPT3.SA', 'VSPT4.SA', 'VSPT11.SA', 'MRSA3.SA', 'MRSA4.SA', 'MRSA11.SA', 'RAIL3.SA', 'RAIL4.SA', 'RAIL11.SA', 'HBSA3.SA', 'HBSA4.SA', 'HBSA11.SA', 'LOGN3.SA', 'LOGN4.SA', 'LOGN11.SA', 'LUXM3.SA', 'LUXM4.SA', 'LUXM11.SA', 'JSLG3.SA', 'JSLG4.SA', 'JSLG11.SA', 'SEQL3.SA', 'SEQL4.SA', 'SEQL11.SA', 'TGMA3.SA', 'TGMA4.SA', 'TGMA11.SA', 'CRTE3.SA', 'CRTE4.SA', 'CRTE11.SA', 'ECOR3.SA', 'ECOR4.SA', 'ECOR11.SA', 'MOTV3.SA', 'MOTV4.SA', 'MOTV11.SA', 'TPIS3.SA', 'TPIS4.SA', 'TPIS11.SA', 'AGRU3.SA', 'AGRU4.SA', 'AGRU11.SA', 'HMOB3.SA', 'HMOB4.SA', 'HMOB11.SA', 'IVPR3.SA', 'IVPR4.SA', 'IVPR11.SA', 'PSVM3.SA', 'PSVM4.SA', 'PSVM11.SA', 'BBML3.SA', 'BBML4.SA', 'BBML11.SA', 'CTAX3.SA', 'CTAX4.SA', 'CTAX11.SA', 'DTCY3.SA', 'DTCY4.SA', 'DTCY11.SA', 'ALPK3.SA', 'ALPK4.SA', 'ALPK11.SA', 'GGPS3.SA', 'GGPS4.SA', 'GGPS11.SA', 'VLID3.SA', 'VLID4.SA', 'VLID11.SA', 'MMAQ3.SA', 'MMAQ4.SA', 'MMAQ11.SA', 'RBNS3.SA', 'RBNS4.SA', 'RBNS11.SA', 'WLMM3.SA', 'WLMM4.SA', 'WLMM11.SA', 'TTEN3.SA', 'TTEN4.SA', 'TTEN11.SA', 'AGXY3.SA', 'AGXY4.SA', 'AGXY11.SA', 'APTI3.SA', 'APTI4.SA', 'APTI11.SA', 'SOJA3.SA', 'SOJA4.SA', 'SOJA11.SA', 'AGRO3.SA', 'AGRO4.SA', 'AGRO11.SA', 'CTCA3.SA', 'CTCA4.SA', 'CTCA11.SA', 'EGGY3.SA', 'EGGY4.SA', 'EGGY11.SA', 'SLCE3.SA', 'SLCE4.SA', 'SLCE11.SA', 'LAND3.SA', 'LAND4.SA', 'LAND11.SA', 'JALL3.SA', 'JALL4.SA', 'JALL11.SA', 'SMTO3.SA', 'SMTO4.SA', 'SMTO11.SA', 'BAUH3.SA', 'BAUH4.SA', 'BAUH11.SA', 'FICT3.SA', 'FICT4.SA', 'FICT11.SA', 'JBSS3.SA', 'JBSS4.SA', 'JBSS11.SA', 'MBRF3.SA', 'MBRF4.SA', 'MBRF11.SA', 'BEEF3.SA', 'BEEF4.SA', 'BEEF11.SA', 'MNPR3.SA', 'MNPR4.SA', 'MNPR11.SA', 'CAML3.SA', 'CAML4.SA', 'CAML11.SA', 'JOPA3.SA', 'JOPA4.SA', 'JOPA11.SA', 'MDIA3.SA', 'MDIA4.SA', 'MDIA11.SA', 'ODER3.SA', 'ODER4.SA', 'ODER11.SA', 'ABEV3.SA', 'ABEV4.SA', 'ABEV11.SA', 'ESPA3.SA', 'ESPA4.SA', 'ESPA11.SA', 'NATU3.SA', 'NATU4.SA', 'NATU11.SA', 'BOBR3.SA', 'BOBR4.SA', 'BOBR11.SA', 'ASAI3.SA', 'ASAI4.SA', 'ASAI11.SA', 'GMAT3.SA', 'GMAT4.SA', 'GMAT11.SA', 'PCAR3.SA', 'PCAR4.SA', 'PCAR11.SA', 'AZZA3.SA', 'AZZA4.SA', 'AZZA11.SA', 'CEAB3.SA', 'CEAB4.SA', 'CEAB11.SA', 'CGRA3.SA', 'CGRA4.SA', 'CGRA11.SA', 'AMAR3.SA', 'AMAR4.SA', 'AMAR11.SA', 'LREN3.SA', 'LREN4.SA', 'LREN11.SA', 'RIAA3.SA', 'RIAA4.SA', 'RIAA11.SA', 'VSTE3.SA', 'VSTE4.SA', 'VSTE11.SA', 'ALLD3.SA', 'ALLD4.SA', 'ALLD11.SA', 'BHIA3.SA', 'BHIA4.SA', 'BHIA11.SA', 'MGLU3.SA', 'MGLU4.SA', 'MGLU11.SA', 'AMER3.SA', 'AMER4.SA', 'AMER11.SA', 'SBFG3.SA', 'SBFG4.SA', 'SBFG11.SA', 'LLBI3.SA', 'LLBI4.SA', 'LLBI11.SA', 'AUAU3.SA', 'AUAU4.SA', 'AUAU11.SA', 'LJQQ3.SA', 'LJQQ4.SA', 'LJQQ11.SA', 'AVLL3.SA', 'AVLL4.SA', 'AVLL11.SA', 'CALI3.SA', 'CALI4.SA', 'CALI11.SA', 'CURY3.SA', 'CURY4.SA', 'CURY11.SA', 'CYRE3.SA', 'CYRE4.SA', 'CYRE11.SA', 'DIRR3.SA', 'DIRR4.SA', 'DIRR11.SA', 'EVEN3.SA', 'EVEN4.SA', 'EVEN11.SA', 'EZTC3.SA', 'EZTC4.SA', 'EZTC11.SA', 'FIEI3.SA', 'FIEI4.SA', 'FIEI11.SA', 'GFSA3.SA', 'GFSA4.SA', 'GFSA11.SA', 'HBOR3.SA', 'HBOR4.SA', 'HBOR11.SA', 'INNC3.SA', 'INNC4.SA', 'INNC11.SA', 'JHSF3.SA', 'JHSF4.SA', 'JHSF11.SA', 'JFEN3.SA', 'JFEN4.SA', 'JFEN11.SA', 'KLAS3.SA', 'KLAS4.SA', 'KLAS11.SA', 'LAVV3.SA', 'LAVV4.SA', 'LAVV11.SA', 'MELK3.SA', 'MELK4.SA', 'MELK11.SA', 'MTRE3.SA', 'MTRE4.SA', 'MTRE11.SA', 'MDNE3.SA', 'MDNE4.SA', 'MDNE11.SA', 'MRVE3.SA', 'MRVE4.SA', 'MRVE11.SA', 'PDGR3.SA', 'PDGR4.SA', 'PDGR11.SA', 'PLPL3.SA', 'PLPL4.SA', 'PLPL11.SA', 'CCTY3.SA', 'CCTY4.SA', 'CCTY11.SA', 'RSID3.SA', 'RSID4.SA', 'RSID11.SA', 'TCSA3.SA', 'TCSA4.SA', 'TCSA11.SA', 'TEND3.SA', 'TEND4.SA', 'TEND11.SA', 'TRIS3.SA', 'TRIS4.SA', 'TRIS11.SA', 'VIVR3.SA', 'VIVR4.SA', 'VIVR11.SA', 'CEDO3.SA', 'CEDO4.SA', 'CEDO11.SA', 'DOHL3.SA', 'DOHL4.SA', 'DOHL11.SA', 'CATA3.SA', 'CATA4.SA', 'CATA11.SA', 'CTKA3.SA', 'CTKA4.SA', 'CTKA11.SA', 'PTNT3.SA', 'PTNT4.SA', 'PTNT11.SA', 'CTSA3.SA', 'CTSA4.SA', 'CTSA11.SA', 'TXRX3.SA', 'TXRX4.SA', 'TXRX11.SA', 'TFCO3.SA', 'TFCO4.SA', 'TFCO11.SA', 'ALPA3.SA', 'ALPA4.SA', 'ALPA11.SA', 'CAMB3.SA', 'CAMB4.SA', 'CAMB11.SA', 'GRND3.SA', 'GRND4.SA', 'GRND11.SA', 'VULC3.SA', 'VULC4.SA', 'VULC11.SA', 'MNDL3.SA', 'MNDL4.SA', 'MNDL11.SA', 'TECN3.SA', 'TECN4.SA', 'TECN11.SA', 'VIVA3.SA', 'VIVA4.SA', 'VIVA11.SA', 'WHRL3.SA', 'WHRL4.SA', 'WHRL11.SA', 'TOKY3.SA', 'TOKY4.SA', 'TOKY11.SA', 'UCAS3.SA', 'UCAS4.SA', 'UCAS11.SA', 'WEST3.SA', 'WEST4.SA', 'WEST11.SA', 'HETA3.SA', 'HETA4.SA', 'HETA11.SA', 'AMOB3.SA', 'AMOB4.SA', 'AMOB11.SA', 'MYPK3.SA', 'MYPK4.SA', 'MYPK11.SA', 'LEVE3.SA', 'LEVE4.SA', 'LEVE11.SA', 'PLAS3.SA', 'PLAS4.SA', 'PLAS11.SA', 'HOOT3.SA', 'HOOT4.SA', 'HOOT11.SA', 'MEAL3.SA', 'MEAL4.SA', 'MEAL11.SA', 'BMKS3.SA', 'BMKS4.SA', 'BMKS11.SA', 'ESTR3.SA', 'ESTR4.SA', 'ESTR11.SA', 'RVEE3.SA', 'RVEE4.SA', 'RVEE11.SA', 'AHEB3.SA', 'AHEB4.SA', 'AHEB11.SA', 'SHOW3.SA', 'SHOW4.SA', 'SHOW11.SA', 'CVCB3.SA', 'CVCB4.SA', 'CVCB11.SA', 'SMFT3.SA', 'SMFT4.SA', 'SMFT11.SA', 'ANIM3.SA', 'ANIM4.SA', 'ANIM11.SA', 'ATED3.SA', 'ATED4.SA', 'ATED11.SA', 'BIED3.SA', 'BIED4.SA', 'BIED11.SA', 'COGN3.SA', 'COGN4.SA', 'COGN11.SA', 'CSED3.SA', 'CSED4.SA', 'CSED11.SA', 'SALT3.SA', 'SALT4.SA', 'SALT11.SA', 'OBTC3.SA', 'OBTC4.SA', 'OBTC11.SA', 'SEER3.SA', 'SEER4.SA', 'SEER11.SA', 'VTRU3.SA', 'VTRU4.SA', 'VTRU11.SA', 'YDUQ3.SA', 'YDUQ4.SA', 'YDUQ11.SA', 'RENT3.SA', 'RENT4.SA', 'RENT11.SA', 'MOVI3.SA', 'MOVI4.SA', 'MOVI11.SA', 'VAMO3.SA', 'VAMO4.SA', 'VAMO11.SA', 'DOTZ3.SA', 'DOTZ4.SA', 'DOTZ11.SA', 'BIOM3.SA', 'BIOM4.SA', 'BIOM11.SA', 'OFSA3.SA', 'OFSA4.SA', 'OFSA11.SA', 'AALR3.SA', 'AALR4.SA', 'AALR11.SA', 'DASA3.SA', 'DASA4.SA', 'DASA11.SA', 'FLRY3.SA', 'FLRY4.SA', 'FLRY11.SA', 'HAPV3.SA', 'HAPV4.SA', 'HAPV11.SA', 'MATD3.SA', 'MATD4.SA', 'MATD11.SA', 'ODPV3.SA', 'ODPV4.SA', 'ODPV11.SA', 'ONCO3.SA', 'ONCO4.SA', 'ONCO11.SA', 'QUAL3.SA', 'QUAL4.SA', 'QUAL11.SA', 'RDOR3.SA', 'RDOR4.SA', 'RDOR11.SA', 'BALM3.SA', 'BALM4.SA', 'BALM11.SA', 'LMED3.SA', 'LMED4.SA', 'LMED11.SA', 'BLAU3.SA', 'BLAU4.SA', 'BLAU11.SA', 'DMVF3.SA', 'DMVF4.SA', 'DMVF11.SA', 'PNVL3.SA', 'PNVL4.SA', 'PNVL11.SA', 'EUFA3.SA', 'EUFA4.SA', 'EUFA11.SA', 'HYPE3.SA', 'HYPE4.SA', 'HYPE11.SA', 'PGMN3.SA', 'PGMN4.SA', 'PGMN11.SA', 'PFRM3.SA', 'PFRM4.SA', 'PFRM11.SA', 'RADL3.SA', 'RADL4.SA', 'RADL11.SA', 'VVEO3.SA', 'VVEO4.SA', 'VVEO11.SA', 'INTB3.SA', 'INTB4.SA', 'INTB11.SA', 'MLAS3.SA', 'MLAS4.SA', 'MLAS11.SA', 'POSI3.SA', 'POSI4.SA', 'POSI11.SA', 'BMOB3.SA', 'BMOB4.SA', 'BMOB11.SA', 'BRQB3.SA', 'BRQB4.SA', 'BRQB11.SA', 'ENJU3.SA', 'ENJU4.SA', 'ENJU11.SA', 'IFCM3.SA', 'IFCM4.SA', 'IFCM11.SA', 'LWSA3.SA', 'LWSA4.SA', 'LWSA11.SA', 'CASH3.SA', 'CASH4.SA', 'CASH11.SA', 'NGRD3.SA', 'NGRD4.SA', 'NGRD11.SA', 'PDTC3.SA', 'PDTC4.SA', 'PDTC11.SA', 'QUSW3.SA', 'QUSW4.SA', 'QUSW11.SA', 'TRAD3.SA', 'TRAD4.SA', 'TRAD11.SA', 'TOTS3.SA', 'TOTS4.SA', 'TOTS11.SA', 'WDCN3.SA', 'WDCN4.SA', 'WDCN11.SA', 'BRST3.SA', 'BRST4.SA', 'BRST11.SA', 'DESK3.SA', 'DESK4.SA', 'DESK11.SA', 'OIBR3.SA', 'OIBR4.SA', 'OIBR11.SA', 'TELB3.SA', 'TELB4.SA', 'TELB11.SA', 'VIVT3.SA', 'VIVT4.SA', 'VIVT11.SA', 'TIMS3.SA', 'TIMS4.SA', 'TIMS11.SA', 'FIQE3.SA', 'FIQE4.SA', 'FIQE11.SA', 'AESO3.SA', 'AESO4.SA', 'AESO11.SA', 'AFLT3.SA', 'AFLT4.SA', 'AFLT11.SA', 'ALUP3.SA', 'ALUP4.SA', 'ALUP11.SA', 'CBEE3.SA', 'CBEE4.SA', 'CBEE11.SA', 'AURE3.SA', 'AURE4.SA', 'AURE11.SA', 'AXIA3.SA', 'AXIA4.SA', 'AXIA11.SA', 'CEBR3.SA', 'CEBR4.SA', 'CEBR11.SA', 'CEED3.SA', 'CEED4.SA', 'CEED11.SA', 'CLSC3.SA', 'CLSC4.SA', 'CLSC11.SA', 'GPAR3.SA', 'GPAR4.SA', 'GPAR11.SA', 'CMIG3.SA', 'CMIG4.SA', 'CMIG11.SA', 'CEEB3.SA', 'CEEB4.SA', 'CEEB11.SA', 'COCE3.SA', 'COCE4.SA', 'COCE11.SA', 'COMR3.SA', 'COMR4.SA', 'COMR11.SA', 'CPLE3.SA', 'CPLE4.SA', 'CPLE11.SA', 'CPFE3.SA', 'CPFE4.SA', 'CPFE11.SA', 'EKTR3.SA', 'EKTR4.SA', 'EKTR11.SA', 'EMAE3.SA', 'EMAE4.SA', 'EMAE11.SA', 'ENGI3.SA', 'ENGI4.SA', 'ENGI11.SA', 'ENMT3.SA', 'ENMT4.SA', 'ENMT11.SA', 'ENEV3.SA', 'ENEV4.SA', 'ENEV11.SA', 'EGIE3.SA', 'EGIE4.SA', 'EGIE11.SA', 'EQPA3.SA', 'EQPA4.SA', 'EQPA11.SA', 'EQMA3.SA', 'EQMA4.SA', 'EQMA11.SA', 'EQTL3.SA', 'EQTL4.SA', 'EQTL11.SA', 'GEPA3.SA', 'GEPA4.SA', 'GEPA11.SA', 'ISAE3.SA', 'ISAE4.SA', 'ISAE11.SA', 'LIGH3.SA', 'LIGH4.SA', 'LIGH11.SA', 'LIGT3.SA', 'LIGT4.SA', 'LIGT11.SA', 'NEOE3.SA', 'NEOE4.SA', 'NEOE11.SA', 'PRMN3.SA', 'PRMN4.SA', 'PRMN11.SA', 'REDE3.SA', 'REDE4.SA', 'REDE11.SA', 'RNEW3.SA', 'RNEW4.SA', 'RNEW11.SA', 'RIOS3.SA', 'RIOS4.SA', 'RIOS11.SA', 'TAEE3.SA', 'TAEE4.SA', 'TAEE11.SA', 'AMBP3.SA', 'AMBP4.SA', 'AMBP11.SA', 'CASN3.SA', 'CASN4.SA', 'CASN11.SA', 'CSMG3.SA', 'CSMG4.SA', 'CSMG11.SA', 'IGSN3.SA', 'IGSN4.SA', 'IGSN11.SA', 'ORVR3.SA', 'ORVR4.SA', 'ORVR11.SA', 'SBSP3.SA', 'SBSP4.SA', 'SBSP11.SA', 'SAPR3.SA', 'SAPR4.SA', 'SAPR11.SA', 'CEGR3.SA', 'CEGR4.SA', 'CEGR11.SA', 'CGAS3.SA', 'CGAS4.SA', 'CGAS11.SA', 'PASS3.SA', 'PASS4.SA', 'PASS11.SA', 'ABCB3.SA', 'ABCB4.SA', 'ABCB11.SA', 'RPAD3.SA', 'RPAD4.SA', 'RPAD11.SA', 'BAZA3.SA', 'BAZA4.SA', 'BAZA11.SA', 'BMGB3.SA', 'BMGB4.SA', 'BMGB11.SA', 'BGIP3.SA', 'BGIP4.SA', 'BGIP11.SA', 'BEES3.SA', 'BEES4.SA', 'BEES11.SA', 'BPAR3.SA', 'BPAR4.SA', 'BPAR11.SA', 'BRSR3.SA', 'BRSR4.SA', 'BRSR11.SA', 'BRBI3.SA', 'BRBI4.SA', 'BRBI11.SA', 'BBDC3.SA', 'BBDC4.SA', 'BBDC11.SA', 'BBAS3.SA', 'BBAS4.SA', 'BBAS11.SA', 'BSLI3.SA', 'BSLI4.SA', 'BSLI11.SA', 'BPAC3.SA', 'BPAC4.SA', 'BPAC11.SA', 'INBR3.SA', 'INBR4.SA', 'INBR11.SA', 'ITUB3.SA', 'ITUB4.SA', 'ITUB11.SA', 'BMIN3.SA', 'BMIN4.SA', 'BMIN11.SA', 'BMEB3.SA', 'BMEB4.SA', 'BMEB11.SA', 'BNBR3.SA', 'BNBR4.SA', 'BNBR11.SA', 'PINE3.SA', 'PINE4.SA', 'PINE11.SA', 'SANB3.SA', 'SANB4.SA', 'SANB11.SA', 'MERC3.SA', 'MERC4.SA', 'MERC11.SA', 'FIGE3.SA', 'FIGE4.SA', 'FIGE11.SA', 'BSCS3.SA', 'BSCS4.SA', 'BSCS11.SA', 'RBRA3.SA', 'RBRA4.SA', 'RBRA11.SA', 'PLSC3.SA', 'PLSC4.SA', 'PLSC11.SA', 'G2DI3.SA', 'G2DI4.SA', 'G2DI11.SA', 'PPLA3.SA', 'PPLA4.SA', 'PPLA11.SA', 'B3SA3.SA', 'B3SA4.SA', 'B3SA11.SA', 'CSUD3.SA', 'CSUD4.SA', 'CSUD11.SA', 'BBSE3.SA', 'BBSE4.SA', 'BBSE11.SA', 'CXSE3.SA', 'CXSE4.SA', 'CXSE11.SA', 'PSSA3.SA', 'PSSA4.SA', 'PSSA11.SA', 'IRBR3.SA', 'IRBR4.SA', 'IRBR11.SA', 'WIZC3.SA', 'WIZC4.SA', 'WIZC11.SA', 'ALOS3.SA', 'ALOS4.SA', 'ALOS11.SA', 'GSHP3.SA', 'GSHP4.SA', 'GSHP11.SA', 'HBTS3.SA', 'HBTS4.SA', 'HBTS11.SA', 'HBRE3.SA', 'HBRE4.SA', 'HBRE11.SA', 'IGTI3.SA', 'IGTI4.SA', 'IGTI11.SA', 'LOGG3.SA', 'LOGG4.SA', 'LOGG11.SA', 'MULT3.SA', 'MULT4.SA', 'MULT11.SA', 'NORD3.SA', 'NORD4.SA', 'NORD11.SA', 'PEAB3.SA', 'PEAB4.SA', 'PEAB11.SA', 'SCAR3.SA', 'SCAR4.SA', 'SCAR11.SA', 'SYNE3.SA', 'SYNE4.SA', 'SYNE11.SA', 'LPSB3.SA', 'LPSB4.SA', 'LPSB11.SA', 'NEXP3.SA', 'NEXP4.SA', 'NEXP11.SA', 'ARND3.SA', 'ARND4.SA', 'ARND11.SA', 'EPAR3.SA', 'EPAR4.SA', 'EPAR11.SA', 'ITSA3.SA', 'ITSA4.SA', 'ITSA11.SA', 'SIMH3.SA', 'SIMH4.SA', 'SIMH11.SA', 'ADMF3.SA', 'ADMF4.SA', 'ADMF11.SA', 'CTBA3.SA', 'CTBA4.SA', 'CTBA11.SA', 'MCRJ3.SA', 'MCRJ4.SA', 'MCRJ11.SA', 'PMSP3.SA', 'PMSP4.SA', 'PMSP11.SA', 'QVQP3.SA', 'QVQP4.SA', 'QVQP11.SA', 'BETP3.SA', 'BETP4.SA', 'BETP11.SA', 'MAPT3.SA', 'MAPT4.SA', 'MAPT11.SA', 'OPGM3.SA', 'OPGM4.SA', 'OPGM11.SA', 'PPAR3.SA', 'PPAR4.SA', 'PPAR11.SA', 'PRPT3.SA', 'PRPT4.SA', 'PRPT11.SA', 'OPSE3.SA', 'OPSE4.SA', 'OPSE11.SA', 'OPTS3.SA', 'OPTS4.SA', 'OPTS11.SA']
==============================================================

###  Função para filtrar tickers válidos na consulta do Yahoo Finance
Critério baseado no texto **"HTTP Error 404"** para selecionar os tickers válidos no Yahoo Finance. A função irá retornar uma lista de tickers válidos para consulta, eliminando aqueles que não estão disponíveis na plataforma.

In [16]:
# Filtrar os tickers válidos, excluindo aqueles que geram erro 404 
# ou retornam informações vazias.
def filtrar_tickers_validos(lista_tickers_yf):
    """
    Recebe uma lista de tickers e retorna apenas os válidos para 
    o Yahoo Finance.
    Tickers que geram mensagem contendo "HTTP Error 404" são excluídos.
    
    Ordem de verificação:
    1. Captura de exceções HTTP 404 (prioridade)
    2. Validação de info não vazio
    3. Verificação de campos essenciais (symbol)
    
    Parâmetros
    ----------
    lista_tickers_yf : list
        Lista de tickers a serem validados.
    
    Retorno
    -------
    list, list
        - tickers_validos_yf: Lista de tickers válidos para o Yahoo Finance.
        - tickers_erro_404_yf: Lista de tickers que geraram erro 404 ou retornaram informações vazias.
    """
    # Listas para armazenar os tickers válidos e os que geraram erro 404
    tickers_validos_yf = []
    tickers_erro_404_yf = []
    
    # Iterar sobre cada ticker e realizar as verificações
    for ticker in lista_tickers_yf:
        try:
            warnings.filterwarnings("ignore")  # Ignorar avisos de depreciação ou outros tipos de avisos
            info = yf.Ticker(ticker).info
            
        except Exception as e:
            # PRIORIDADE 1: Capturar e verificar primeiro se é um erro 404
            erro_str = str(e)
            
            if "HTTP Error 404" in erro_str or "Not Found" in erro_str:
                tickers_erro_404_yf.append(ticker)
                print(f"Ticker {ticker} gerou erro 404: {erro_str[:80]}")
            else:
                # Outros erros também são considerados inválidos
                tickers_erro_404_yf.append(ticker)
                print(f"Ticker {ticker} gerou erro: {erro_str[:80]}")
            continue
        
        # PRIORIDADE 2: Se não houve exceção, verificar se info é válido
        if not info or len(info) == 0:
            tickers_erro_404_yf.append(ticker)
            print(f"Ticker {ticker} retornou informações vazias.")
            continue
        
        # PRIORIDADE 3: Verificar se contém campos essenciais
        if 'symbol' not in info or info.get('symbol') is None:
            tickers_erro_404_yf.append(ticker)
            print(f"Ticker {ticker} não contém símbolo válido.")
            continue
        
        # Se passou por todas as verificações, o ticker é válido
        tickers_validos_yf.append(ticker)
        print(f"Ticker {ticker} é válido.")

    return tickers_validos_yf, tickers_erro_404_yf

In [17]:
'''
tickers_testes = ['PETR4.SA', 'VALE3.SA', 'AZTE3.SA', 'AZTE4.SA', 'AZTE11.SA', 'BRAV3.SA', 'BRAV4.SA', 'BRAV11.SA', 'CSAN3.SA', 'CSAN4.SA', 'CSAN11.SA', 'RPMG3.SA', 'RPMG4.SA', 'RPMG11.SA', 'PETR3.SA', 'PETR4.SA', 'PETR11.SA', 'RECV3.SA', 'RECV4.SA', 'RECV11.SA', 'PRIO3.SA', 'PRIO4.SA', 'PRIO11.SA', 'RAIZ3.SA', 'RAIZ4.SA', 'RAIZ11.SA', 'UGPA3.SA', 'UGPA4.SA', 'UGPA11.SA','ABCD3.SA']  # Exemplo de tickers para teste
print("A quantidade de tickers para o teste é:", len(tickers_testes))
'''

'\ntickers_testes = [\'PETR4.SA\', \'VALE3.SA\', \'AZTE3.SA\', \'AZTE4.SA\', \'AZTE11.SA\', \'BRAV3.SA\', \'BRAV4.SA\', \'BRAV11.SA\', \'CSAN3.SA\', \'CSAN4.SA\', \'CSAN11.SA\', \'RPMG3.SA\', \'RPMG4.SA\', \'RPMG11.SA\', \'PETR3.SA\', \'PETR4.SA\', \'PETR11.SA\', \'RECV3.SA\', \'RECV4.SA\', \'RECV11.SA\', \'PRIO3.SA\', \'PRIO4.SA\', \'PRIO11.SA\', \'RAIZ3.SA\', \'RAIZ4.SA\', \'RAIZ11.SA\', \'UGPA3.SA\', \'UGPA4.SA\', \'UGPA11.SA\',\'ABCD3.SA\']  # Exemplo de tickers para teste\nprint("A quantidade de tickers para o teste é:", len(tickers_testes))\n'

In [18]:
# Filtrar os tickers válidos, excluindo aqueles que geram erro 404 ou retornam informações vazias
tickers_validos_yf, tickers_erro_404_yf = filtrar_tickers_validos(lista_tickers_yf)

# Exibir a quantidade de tickers válidos e os que geraram erro 404
print("==============================================================")
print(f"A quantidade de tickers válidos é: {len(tickers_validos_yf)}")
print(f"Tickers válidos: {tickers_validos_yf}")
print()
print(f"A quantidade de tickers que geraram erro 404 ou informações vazias é: {len(tickers_erro_404_yf)}")
print(f"Tickers que geraram erro 404 ou informações vazias: {tickers_erro_404_yf}")
print("==============================================================")

Ticker AZTE3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: AZTE4.SA"}}}

Ticker AZTE4.SA não contém símbolo válido.
Ticker AZTE11.SA é válido.
Ticker BRAV3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: BRAV4.SA"}}}

Ticker BRAV4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: BRAV11.SA"}}}

Ticker BRAV11.SA não contém símbolo válido.
Ticker CSAN3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CSAN4.SA"}}}

Ticker CSAN4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CSAN11.SA"}}}

Ticker CSAN11.SA não contém símbolo válido.
Ticker RPMG3.SA é válido.
Ticker RPMG4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: RPMG11.SA"}}}

Ticker RPMG11.SA não contém símbolo válido.
Ticker PETR3.SA é válido.
Ticker PETR4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: PETR11.SA"}}}

Ticker PETR11.SA não contém símbolo válido.
Ticker RECV3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: RECV4.SA"}}}

Ticker RECV4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: RECV11.SA"}}}

Ticker RECV11.SA não contém símbolo válido.
Ticker PRIO3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: PRIO4.SA"}}}

Ticker PRIO4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: PRIO11.SA"}}}

Ticker PRIO11.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: RAIZ3.SA"}}}

Ticker RAIZ3.SA não contém símbolo válido.
Ticker RAIZ4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: RAIZ11.SA"}}}

Ticker RAIZ11.SA não contém símbolo válido.
Ticker UGPA3.SA é válido.
Ticker UGPA4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: UGPA11.SA"}}}

Ticker UGPA11.SA não contém símbolo válido.
Ticker LUPA3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: LUPA4.SA"}}}

Ticker LUPA4.SA não contém símbolo válido.
Ticker LUPA11.SA é válido.
Ticker OPCT3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: OPCT4.SA"}}}

Ticker OPCT4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: OPCT11.SA"}}}

Ticker OPCT11.SA não contém símbolo válido.
Ticker OSXB3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: OSXB4.SA"}}}

Ticker OSXB4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: OSXB11.SA"}}}

Ticker OSXB11.SA não contém símbolo válido.
Ticker VBBR3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: VBBR4.SA"}}}

Ticker VBBR4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: VBBR11.SA"}}}

Ticker VBBR11.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: AURA3.SA"}}}

Ticker AURA3.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: AURA4.SA"}}}

Ticker AURA4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: AURA11.SA"}}}

Ticker AURA11.SA não contém símbolo válido.
Ticker BRAP3.SA é válido.
Ticker BRAP4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: BRAP11.SA"}}}

Ticker BRAP11.SA não contém símbolo válido.
Ticker CBAV3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CBAV4.SA"}}}

Ticker CBAV4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CBAV11.SA"}}}

Ticker CBAV11.SA não contém símbolo válido.
Ticker CMIN3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CMIN4.SA"}}}

Ticker CMIN4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CMIN11.SA"}}}

Ticker CMIN11.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: LTEL3.SA"}}}

Ticker LTEL3.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: LTEL4.SA"}}}

Ticker LTEL4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: LTEL11.SA"}}}

Ticker LTEL11.SA não contém símbolo válido.
Ticker LTLA3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: LTLA4.SA"}}}

Ticker LTLA4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: LTLA11.SA"}}}

Ticker LTLA11.SA não contém símbolo válido.
Ticker VALE3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: VALE4.SA"}}}

Ticker VALE4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: VALE11.SA"}}}

Ticker VALE11.SA não contém símbolo válido.
Ticker FESA3.SA é válido.
Ticker FESA4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: FESA11.SA"}}}

Ticker FESA11.SA não contém símbolo válido.
Ticker GGBR3.SA é válido.
Ticker GGBR4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: GGBR11.SA"}}}

Ticker GGBR11.SA não contém símbolo válido.
Ticker GOAU3.SA é válido.
Ticker GOAU4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: GOAU11.SA"}}}

Ticker GOAU11.SA não contém símbolo válido.
Ticker CSNA3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CSNA4.SA"}}}

Ticker CSNA4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CSNA11.SA"}}}

Ticker CSNA11.SA não contém símbolo válido.
Ticker USIM3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: USIM4.SA"}}}

Ticker USIM4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: USIM11.SA"}}}

Ticker USIM11.SA não contém símbolo válido.
Ticker HAGA3.SA é válido.
Ticker HAGA4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: HAGA11.SA"}}}

Ticker HAGA11.SA não contém símbolo válido.
Ticker MGEL3.SA é válido.
Ticker MGEL4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: MGEL11.SA"}}}

Ticker MGEL11.SA não contém símbolo válido.
Ticker PATI3.SA é válido.
Ticker PATI4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: PATI11.SA"}}}

Ticker PATI11.SA não contém símbolo válido.
Ticker TKNO3.SA é válido.
Ticker TKNO4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: TKNO11.SA"}}}

Ticker TKNO11.SA não contém símbolo válido.
Ticker PMAM3.SA é válido.
Ticker PMAM4.SA é válido.
Ticker PMAM11.SA é válido.
Ticker BRKM3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: BRKM4.SA"}}}

Ticker BRKM4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: BRKM11.SA"}}}

Ticker BRKM11.SA não contém símbolo válido.
Ticker DEXP3.SA é válido.
Ticker DEXP4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: DEXP11.SA"}}}

Ticker DEXP11.SA não contém símbolo válido.
Ticker FHER3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: FHER4.SA"}}}

Ticker FHER4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: FHER11.SA"}}}

Ticker FHER11.SA não contém símbolo válido.
Ticker NUTR3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: NUTR4.SA"}}}

Ticker NUTR4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: NUTR11.SA"}}}

Ticker NUTR11.SA não contém símbolo válido.
Ticker VITT3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: VITT4.SA"}}}

Ticker VITT4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: VITT11.SA"}}}

Ticker VITT11.SA não contém símbolo válido.
Ticker CRPG3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CRPG4.SA"}}}

Ticker CRPG4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CRPG11.SA"}}}

Ticker CRPG11.SA não contém símbolo válido.
Ticker UNIP3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: UNIP4.SA"}}}

Ticker UNIP4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: UNIP11.SA"}}}

Ticker UNIP11.SA não contém símbolo válido.
Ticker DXCO3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: DXCO4.SA"}}}

Ticker DXCO4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: DXCO11.SA"}}}

Ticker DXCO11.SA não contém símbolo válido.
Ticker EUCA3.SA é válido.
Ticker EUCA4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: EUCA11.SA"}}}

Ticker EUCA11.SA não contém símbolo válido.
Ticker KLBN3.SA é válido.
Ticker KLBN4.SA é válido.
Ticker KLBN11.SA é válido.
Ticker MSPA3.SA é válido.
Ticker MSPA4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: MSPA11.SA"}}}

Ticker MSPA11.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: NEMO3.SA"}}}

Ticker NEMO3.SA não contém símbolo válido.
Ticker NEMO4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: NEMO11.SA"}}}

Ticker NEMO11.SA não contém símbolo válido.
Ticker SUZB3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: SUZB4.SA"}}}

Ticker SUZB4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: SUZB11.SA"}}}

Ticker SUZB11.SA não contém símbolo válido.
Ticker RANI3.SA é válido.
Ticker RANI4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: RANI11.SA"}}}

Ticker RANI11.SA não contém símbolo válido.
Ticker SNSY3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: SNSY4.SA"}}}

Ticker SNSY4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: SNSY11.SA"}}}

Ticker SNSY11.SA não contém símbolo válido.
Ticker ETER3.SA é válido.
Ticker ETER4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: ETER11.SA"}}}

Ticker ETER11.SA não contém símbolo válido.
Ticker PTBL3.SA é válido.
Ticker PTBL4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: PTBL11.SA"}}}

Ticker PTBL11.SA não contém símbolo válido.
Ticker AZEV3.SA é válido.
Ticker AZEV4.SA é válido.
Ticker AZEV11.SA é válido.
Ticker SOND3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: SOND4.SA"}}}

Ticker SOND4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: SOND11.SA"}}}

Ticker SOND11.SA não contém símbolo válido.
Ticker ARML3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: ARML4.SA"}}}

Ticker ARML4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: ARML11.SA"}}}

Ticker ARML11.SA não contém símbolo válido.
Ticker MILS3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: MILS4.SA"}}}

Ticker MILS4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: MILS11.SA"}}}

Ticker MILS11.SA não contém símbolo válido.
Ticker PRNR3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: PRNR4.SA"}}}

Ticker PRNR4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: PRNR11.SA"}}}

Ticker PRNR11.SA não contém símbolo válido.
Ticker EMBJ3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: EMBJ4.SA"}}}

Ticker EMBJ4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: EMBJ11.SA"}}}

Ticker EMBJ11.SA não contém símbolo válido.
Ticker FRAS3.SA é válido.
Ticker FRAS4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: FRAS11.SA"}}}

Ticker FRAS11.SA não contém símbolo válido.
Ticker POMO3.SA é válido.
Ticker POMO4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: POMO11.SA"}}}

Ticker POMO11.SA não contém símbolo válido.
Ticker RAPT3.SA é válido.
Ticker RAPT4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: RAPT11.SA"}}}

Ticker RAPT11.SA não contém símbolo válido.
Ticker RCSL3.SA é válido.
Ticker RCSL4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: RCSL11.SA"}}}

Ticker RCSL11.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: RSUL3.SA"}}}

Ticker RSUL3.SA não contém símbolo válido.
Ticker RSUL4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: RSUL11.SA"}}}

Ticker RSUL11.SA não contém símbolo válido.
Ticker TUPY3.SA é válido.
Ticker TUPY4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: TUPY11.SA"}}}

Ticker TUPY11.SA não contém símbolo válido.
Ticker MWET3.SA é válido.
Ticker MWET4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: MWET11.SA"}}}

Ticker MWET11.SA não contém símbolo válido.
Ticker SHUL3.SA é válido.
Ticker SHUL4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: SHUL11.SA"}}}

Ticker SHUL11.SA não contém símbolo válido.
Ticker WEGE3.SA é válido.
Ticker WEGE4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: WEGE11.SA"}}}

Ticker WEGE11.SA não contém símbolo válido.
Ticker EALT3.SA é válido.
Ticker EALT4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: EALT11.SA"}}}

Ticker EALT11.SA não contém símbolo válido.
Ticker AERI3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: AERI4.SA"}}}

Ticker AERI4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: AERI11.SA"}}}

Ticker AERI11.SA não contém símbolo válido.
Ticker BDLL3.SA é válido.
Ticker BDLL4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: BDLL11.SA"}}}

Ticker BDLL11.SA não contém símbolo válido.
Ticker INEP3.SA é válido.
Ticker INEP4.SA é válido.
Ticker INEP11.SA é válido.
Ticker KEPL3.SA é válido.
Ticker KEPL4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: KEPL11.SA"}}}

Ticker KEPL11.SA não contém símbolo válido.
Ticker FRIO3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: FRIO4.SA"}}}

Ticker FRIO4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: FRIO11.SA"}}}

Ticker FRIO11.SA não contém símbolo válido.
Ticker PTCA3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: PTCA4.SA"}}}

Ticker PTCA4.SA não contém símbolo válido.
Ticker PTCA11.SA é válido.
Ticker ROMI3.SA é válido.
Ticker ROMI4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: ROMI11.SA"}}}

Ticker ROMI11.SA não contém símbolo válido.
Ticker MTSA3.SA é válido.
Ticker MTSA4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: MTSA11.SA"}}}

Ticker MTSA11.SA não contém símbolo válido.
Ticker TASA3.SA é válido.
Ticker TASA4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: TASA11.SA"}}}

Ticker TASA11.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: AZUL3.SA"}}}

Ticker AZUL3.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: AZUL4.SA"}}}

Ticker AZUL4.SA não contém símbolo válido.
Ticker AZUL11.SA é válido.
Ticker GOLL3.SA é válido.
Ticker GOLL4.SA é válido.
Ticker GOLL11.SA é válido.
Ticker VSPT3.SA é válido.
Ticker VSPT4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: VSPT11.SA"}}}

Ticker VSPT11.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: MRSA3.SA"}}}

Ticker MRSA3.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: MRSA4.SA"}}}

Ticker MRSA4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: MRSA11.SA"}}}

Ticker MRSA11.SA não contém símbolo válido.
Ticker RAIL3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: RAIL4.SA"}}}

Ticker RAIL4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: RAIL11.SA"}}}

Ticker RAIL11.SA não contém símbolo válido.
Ticker HBSA3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: HBSA4.SA"}}}

Ticker HBSA4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: HBSA11.SA"}}}

Ticker HBSA11.SA não contém símbolo válido.
Ticker LOGN3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: LOGN4.SA"}}}

Ticker LOGN4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: LOGN11.SA"}}}

Ticker LOGN11.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: LUXM3.SA"}}}

Ticker LUXM3.SA não contém símbolo válido.
Ticker LUXM4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: LUXM11.SA"}}}

Ticker LUXM11.SA não contém símbolo válido.
Ticker JSLG3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: JSLG4.SA"}}}

Ticker JSLG4.SA não contém símbolo válido.
Ticker JSLG11.SA é válido.
Ticker SEQL3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: SEQL4.SA"}}}

Ticker SEQL4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: SEQL11.SA"}}}

Ticker SEQL11.SA não contém símbolo válido.
Ticker TGMA3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: TGMA4.SA"}}}

Ticker TGMA4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: TGMA11.SA"}}}

Ticker TGMA11.SA não contém símbolo válido.
Ticker CRTE3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CRTE4.SA"}}}

Ticker CRTE4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CRTE11.SA"}}}

Ticker CRTE11.SA não contém símbolo válido.
Ticker ECOR3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: ECOR4.SA"}}}

Ticker ECOR4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: ECOR11.SA"}}}

Ticker ECOR11.SA não contém símbolo válido.
Ticker MOTV3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: MOTV4.SA"}}}

Ticker MOTV4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: MOTV11.SA"}}}

Ticker MOTV11.SA não contém símbolo válido.
Ticker TPIS3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: TPIS4.SA"}}}

Ticker TPIS4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: TPIS11.SA"}}}

Ticker TPIS11.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: AGRU3.SA"}}}

Ticker AGRU3.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: AGRU4.SA"}}}

Ticker AGRU4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: AGRU11.SA"}}}

Ticker AGRU11.SA não contém símbolo válido.
Ticker HMOB3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: HMOB4.SA"}}}

Ticker HMOB4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: HMOB11.SA"}}}

Ticker HMOB11.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: IVPR3.SA"}}}

Ticker IVPR3.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: IVPR4.SA"}}}

Ticker IVPR4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: IVPR11.SA"}}}

Ticker IVPR11.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: PSVM3.SA"}}}

Ticker PSVM3.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: PSVM4.SA"}}}

Ticker PSVM4.SA não contém símbolo válido.
Ticker PSVM11.SA é válido.
Ticker BBML3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: BBML4.SA"}}}

Ticker BBML4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: BBML11.SA"}}}

Ticker BBML11.SA não contém símbolo válido.
Ticker CTAX3.SA é válido.
Ticker CTAX4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CTAX11.SA"}}}

Ticker CTAX11.SA não contém símbolo válido.
Ticker DTCY3.SA é válido.
Ticker DTCY4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: DTCY11.SA"}}}

Ticker DTCY11.SA não contém símbolo válido.
Ticker ALPK3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: ALPK4.SA"}}}

Ticker ALPK4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: ALPK11.SA"}}}

Ticker ALPK11.SA não contém símbolo válido.
Ticker GGPS3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: GGPS4.SA"}}}

Ticker GGPS4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: GGPS11.SA"}}}

Ticker GGPS11.SA não contém símbolo válido.
Ticker VLID3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: VLID4.SA"}}}

Ticker VLID4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: VLID11.SA"}}}

Ticker VLID11.SA não contém símbolo válido.
Ticker MMAQ3.SA é válido.
Ticker MMAQ4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: MMAQ11.SA"}}}

Ticker MMAQ11.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: RBNS3.SA"}}}

Ticker RBNS3.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: RBNS4.SA"}}}

Ticker RBNS4.SA não contém símbolo válido.
Ticker RBNS11.SA é válido.
Ticker WLMM3.SA é válido.
Ticker WLMM4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: WLMM11.SA"}}}

Ticker WLMM11.SA não contém símbolo válido.
Ticker TTEN3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: TTEN4.SA"}}}

Ticker TTEN4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: TTEN11.SA"}}}

Ticker TTEN11.SA não contém símbolo válido.
Ticker AGXY3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: AGXY4.SA"}}}

Ticker AGXY4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: AGXY11.SA"}}}

Ticker AGXY11.SA não contém símbolo válido.
Ticker APTI3.SA é válido.
Ticker APTI4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: APTI11.SA"}}}

Ticker APTI11.SA não contém símbolo válido.
Ticker SOJA3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: SOJA4.SA"}}}

Ticker SOJA4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: SOJA11.SA"}}}

Ticker SOJA11.SA não contém símbolo válido.
Ticker AGRO3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: AGRO4.SA"}}}

Ticker AGRO4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: AGRO11.SA"}}}

Ticker AGRO11.SA não contém símbolo válido.
Ticker CTCA3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CTCA4.SA"}}}

Ticker CTCA4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CTCA11.SA"}}}

Ticker CTCA11.SA não contém símbolo válido.
Ticker EGGY3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: EGGY4.SA"}}}

Ticker EGGY4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: EGGY11.SA"}}}

Ticker EGGY11.SA não contém símbolo válido.
Ticker SLCE3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: SLCE4.SA"}}}

Ticker SLCE4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: SLCE11.SA"}}}

Ticker SLCE11.SA não contém símbolo válido.
Ticker LAND3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: LAND4.SA"}}}

Ticker LAND4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: LAND11.SA"}}}

Ticker LAND11.SA não contém símbolo válido.
Ticker JALL3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: JALL4.SA"}}}

Ticker JALL4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: JALL11.SA"}}}

Ticker JALL11.SA não contém símbolo válido.
Ticker SMTO3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: SMTO4.SA"}}}

Ticker SMTO4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: SMTO11.SA"}}}

Ticker SMTO11.SA não contém símbolo válido.
Ticker BAUH3.SA é válido.
Ticker BAUH4.SA é válido.
Ticker BAUH11.SA é válido.
Ticker FICT3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: FICT4.SA"}}}

Ticker FICT4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: FICT11.SA"}}}

Ticker FICT11.SA não contém símbolo válido.
Ticker JBSS3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: JBSS4.SA"}}}

Ticker JBSS4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: JBSS11.SA"}}}

Ticker JBSS11.SA não contém símbolo válido.
Ticker MBRF3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: MBRF4.SA"}}}

Ticker MBRF4.SA não contém símbolo válido.
Ticker MBRF11.SA é válido.
Ticker BEEF3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: BEEF4.SA"}}}

Ticker BEEF4.SA não contém símbolo válido.
Ticker BEEF11.SA é válido.
Ticker MNPR3.SA é válido.
Ticker MNPR4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: MNPR11.SA"}}}

Ticker MNPR11.SA não contém símbolo válido.
Ticker CAML3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CAML4.SA"}}}

Ticker CAML4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CAML11.SA"}}}

Ticker CAML11.SA não contém símbolo válido.
Ticker JOPA3.SA é válido.
Ticker JOPA4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: JOPA11.SA"}}}

Ticker JOPA11.SA não contém símbolo válido.
Ticker MDIA3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: MDIA4.SA"}}}

Ticker MDIA4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: MDIA11.SA"}}}

Ticker MDIA11.SA não contém símbolo válido.
Ticker ODER3.SA é válido.
Ticker ODER4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: ODER11.SA"}}}

Ticker ODER11.SA não contém símbolo válido.
Ticker ABEV3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: ABEV4.SA"}}}

Ticker ABEV4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: ABEV11.SA"}}}

Ticker ABEV11.SA não contém símbolo válido.
Ticker ESPA3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: ESPA4.SA"}}}

Ticker ESPA4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: ESPA11.SA"}}}

Ticker ESPA11.SA não contém símbolo válido.
Ticker NATU3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: NATU4.SA"}}}

Ticker NATU4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: NATU11.SA"}}}

Ticker NATU11.SA não contém símbolo válido.
Ticker BOBR3.SA é válido.
Ticker BOBR4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: BOBR11.SA"}}}

Ticker BOBR11.SA não contém símbolo válido.
Ticker ASAI3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: ASAI4.SA"}}}

Ticker ASAI4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: ASAI11.SA"}}}

Ticker ASAI11.SA não contém símbolo válido.
Ticker GMAT3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: GMAT4.SA"}}}

Ticker GMAT4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: GMAT11.SA"}}}

Ticker GMAT11.SA não contém símbolo válido.
Ticker PCAR3.SA é válido.
Ticker PCAR4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: PCAR11.SA"}}}

Ticker PCAR11.SA não contém símbolo válido.
Ticker AZZA3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: AZZA4.SA"}}}

Ticker AZZA4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: AZZA11.SA"}}}

Ticker AZZA11.SA não contém símbolo válido.
Ticker CEAB3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CEAB4.SA"}}}

Ticker CEAB4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CEAB11.SA"}}}

Ticker CEAB11.SA não contém símbolo válido.
Ticker CGRA3.SA é válido.
Ticker CGRA4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CGRA11.SA"}}}

Ticker CGRA11.SA não contém símbolo válido.
Ticker AMAR3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: AMAR4.SA"}}}

Ticker AMAR4.SA não contém símbolo válido.
Ticker AMAR11.SA é válido.
Ticker LREN3.SA é válido.
Ticker LREN4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: LREN11.SA"}}}

Ticker LREN11.SA não contém símbolo válido.
Ticker RIAA3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: RIAA4.SA"}}}

Ticker RIAA4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: RIAA11.SA"}}}

Ticker RIAA11.SA não contém símbolo válido.
Ticker VSTE3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: VSTE4.SA"}}}

Ticker VSTE4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: VSTE11.SA"}}}

Ticker VSTE11.SA não contém símbolo válido.
Ticker ALLD3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: ALLD4.SA"}}}

Ticker ALLD4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: ALLD11.SA"}}}

Ticker ALLD11.SA não contém símbolo válido.
Ticker BHIA3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: BHIA4.SA"}}}

Ticker BHIA4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: BHIA11.SA"}}}

Ticker BHIA11.SA não contém símbolo válido.
Ticker MGLU3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: MGLU4.SA"}}}

Ticker MGLU4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: MGLU11.SA"}}}

Ticker MGLU11.SA não contém símbolo válido.
Ticker AMER3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: AMER4.SA"}}}

Ticker AMER4.SA não contém símbolo válido.
Ticker AMER11.SA é válido.
Ticker SBFG3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: SBFG4.SA"}}}

Ticker SBFG4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: SBFG11.SA"}}}

Ticker SBFG11.SA não contém símbolo válido.
Ticker LLBI3.SA é válido.
Ticker LLBI4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: LLBI11.SA"}}}

Ticker LLBI11.SA não contém símbolo válido.
Ticker AUAU3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: AUAU4.SA"}}}

Ticker AUAU4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: AUAU11.SA"}}}

Ticker AUAU11.SA não contém símbolo válido.
Ticker LJQQ3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: LJQQ4.SA"}}}

Ticker LJQQ4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: LJQQ11.SA"}}}

Ticker LJQQ11.SA não contém símbolo válido.
Ticker AVLL3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: AVLL4.SA"}}}

Ticker AVLL4.SA não contém símbolo válido.
Ticker AVLL11.SA é válido.
Ticker CALI3.SA é válido.
Ticker CALI4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CALI11.SA"}}}

Ticker CALI11.SA não contém símbolo válido.
Ticker CURY3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CURY4.SA"}}}

Ticker CURY4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CURY11.SA"}}}

Ticker CURY11.SA não contém símbolo válido.
Ticker CYRE3.SA é válido.
Ticker CYRE4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CYRE11.SA"}}}

Ticker CYRE11.SA não contém símbolo válido.
Ticker DIRR3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: DIRR4.SA"}}}

Ticker DIRR4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: DIRR11.SA"}}}

Ticker DIRR11.SA não contém símbolo válido.
Ticker EVEN3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: EVEN4.SA"}}}

Ticker EVEN4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: EVEN11.SA"}}}

Ticker EVEN11.SA não contém símbolo válido.
Ticker EZTC3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: EZTC4.SA"}}}

Ticker EZTC4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: EZTC11.SA"}}}

Ticker EZTC11.SA não contém símbolo válido.
Ticker FIEI3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: FIEI4.SA"}}}

Ticker FIEI4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: FIEI11.SA"}}}

Ticker FIEI11.SA não contém símbolo válido.
Ticker GFSA3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: GFSA4.SA"}}}

Ticker GFSA4.SA não contém símbolo válido.
Ticker GFSA11.SA é válido.
Ticker HBOR3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: HBOR4.SA"}}}

Ticker HBOR4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: HBOR11.SA"}}}

Ticker HBOR11.SA não contém símbolo válido.
Ticker INNC3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: INNC4.SA"}}}

Ticker INNC4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: INNC11.SA"}}}

Ticker INNC11.SA não contém símbolo válido.
Ticker JHSF3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: JHSF4.SA"}}}

Ticker JHSF4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: JHSF11.SA"}}}

Ticker JHSF11.SA não contém símbolo válido.
Ticker JFEN3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: JFEN4.SA"}}}

Ticker JFEN4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: JFEN11.SA"}}}

Ticker JFEN11.SA não contém símbolo válido.
Ticker KLAS3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: KLAS4.SA"}}}

Ticker KLAS4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: KLAS11.SA"}}}

Ticker KLAS11.SA não contém símbolo válido.
Ticker LAVV3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: LAVV4.SA"}}}

Ticker LAVV4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: LAVV11.SA"}}}

Ticker LAVV11.SA não contém símbolo válido.
Ticker MELK3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: MELK4.SA"}}}

Ticker MELK4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: MELK11.SA"}}}

Ticker MELK11.SA não contém símbolo válido.
Ticker MTRE3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: MTRE4.SA"}}}

Ticker MTRE4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: MTRE11.SA"}}}

Ticker MTRE11.SA não contém símbolo válido.
Ticker MDNE3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: MDNE4.SA"}}}

Ticker MDNE4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: MDNE11.SA"}}}

Ticker MDNE11.SA não contém símbolo válido.
Ticker MRVE3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: MRVE4.SA"}}}

Ticker MRVE4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: MRVE11.SA"}}}

Ticker MRVE11.SA não contém símbolo válido.
Ticker PDGR3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: PDGR4.SA"}}}

Ticker PDGR4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: PDGR11.SA"}}}

Ticker PDGR11.SA não contém símbolo válido.
Ticker PLPL3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: PLPL4.SA"}}}

Ticker PLPL4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: PLPL11.SA"}}}

Ticker PLPL11.SA não contém símbolo válido.
Ticker CCTY3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CCTY4.SA"}}}

Ticker CCTY4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CCTY11.SA"}}}

Ticker CCTY11.SA não contém símbolo válido.
Ticker RSID3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: RSID4.SA"}}}

Ticker RSID4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: RSID11.SA"}}}

Ticker RSID11.SA não contém símbolo válido.
Ticker TCSA3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: TCSA4.SA"}}}

Ticker TCSA4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: TCSA11.SA"}}}

Ticker TCSA11.SA não contém símbolo válido.
Ticker TEND3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: TEND4.SA"}}}

Ticker TEND4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: TEND11.SA"}}}

Ticker TEND11.SA não contém símbolo válido.
Ticker TRIS3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: TRIS4.SA"}}}

Ticker TRIS4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: TRIS11.SA"}}}

Ticker TRIS11.SA não contém símbolo válido.
Ticker VIVR3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: VIVR4.SA"}}}

Ticker VIVR4.SA não contém símbolo válido.
Ticker VIVR11.SA é válido.
Ticker CEDO3.SA é válido.
Ticker CEDO4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CEDO11.SA"}}}

Ticker CEDO11.SA não contém símbolo válido.
Ticker DOHL3.SA é válido.
Ticker DOHL4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: DOHL11.SA"}}}

Ticker DOHL11.SA não contém símbolo válido.
Ticker CATA3.SA é válido.
Ticker CATA4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CATA11.SA"}}}

Ticker CATA11.SA não contém símbolo válido.
Ticker CTKA3.SA é válido.
Ticker CTKA4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CTKA11.SA"}}}

Ticker CTKA11.SA não contém símbolo válido.
Ticker PTNT3.SA é válido.
Ticker PTNT4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: PTNT11.SA"}}}

Ticker PTNT11.SA não contém símbolo válido.
Ticker CTSA3.SA é válido.
Ticker CTSA4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CTSA11.SA"}}}

Ticker CTSA11.SA não contém símbolo válido.
Ticker TXRX3.SA é válido.
Ticker TXRX4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: TXRX11.SA"}}}

Ticker TXRX11.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: TFCO3.SA"}}}

Ticker TFCO3.SA não contém símbolo válido.
Ticker TFCO4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: TFCO11.SA"}}}

Ticker TFCO11.SA não contém símbolo válido.
Ticker ALPA3.SA é válido.
Ticker ALPA4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: ALPA11.SA"}}}

Ticker ALPA11.SA não contém símbolo válido.
Ticker CAMB3.SA é válido.
Ticker CAMB4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CAMB11.SA"}}}

Ticker CAMB11.SA não contém símbolo válido.
Ticker GRND3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: GRND4.SA"}}}

Ticker GRND4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: GRND11.SA"}}}

Ticker GRND11.SA não contém símbolo válido.
Ticker VULC3.SA é válido.
Ticker VULC4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: VULC11.SA"}}}

Ticker VULC11.SA não contém símbolo válido.
Ticker MNDL3.SA é válido.
Ticker MNDL4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: MNDL11.SA"}}}

Ticker MNDL11.SA não contém símbolo válido.
Ticker TECN3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: TECN4.SA"}}}

Ticker TECN4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: TECN11.SA"}}}

Ticker TECN11.SA não contém símbolo válido.
Ticker VIVA3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: VIVA4.SA"}}}

Ticker VIVA4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: VIVA11.SA"}}}

Ticker VIVA11.SA não contém símbolo válido.
Ticker WHRL3.SA é válido.
Ticker WHRL4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: WHRL11.SA"}}}

Ticker WHRL11.SA não contém símbolo válido.
Ticker TOKY3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: TOKY4.SA"}}}

Ticker TOKY4.SA não contém símbolo válido.
Ticker TOKY11.SA é válido.
Ticker UCAS3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: UCAS4.SA"}}}

Ticker UCAS4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: UCAS11.SA"}}}

Ticker UCAS11.SA não contém símbolo válido.
Ticker WEST3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: WEST4.SA"}}}

Ticker WEST4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: WEST11.SA"}}}

Ticker WEST11.SA não contém símbolo válido.
Ticker HETA3.SA é válido.
Ticker HETA4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: HETA11.SA"}}}

Ticker HETA11.SA não contém símbolo válido.
Ticker AMOB3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: AMOB4.SA"}}}

Ticker AMOB4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: AMOB11.SA"}}}

Ticker AMOB11.SA não contém símbolo válido.
Ticker MYPK3.SA é válido.
Ticker MYPK4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: MYPK11.SA"}}}

Ticker MYPK11.SA não contém símbolo válido.
Ticker LEVE3.SA é válido.
Ticker LEVE4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: LEVE11.SA"}}}

Ticker LEVE11.SA não contém símbolo válido.
Ticker PLAS3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: PLAS4.SA"}}}

Ticker PLAS4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: PLAS11.SA"}}}

Ticker PLAS11.SA não contém símbolo válido.
Ticker HOOT3.SA é válido.
Ticker HOOT4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: HOOT11.SA"}}}

Ticker HOOT11.SA não contém símbolo válido.
Ticker MEAL3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: MEAL4.SA"}}}

Ticker MEAL4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: MEAL11.SA"}}}

Ticker MEAL11.SA não contém símbolo válido.
Ticker BMKS3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: BMKS4.SA"}}}

Ticker BMKS4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: BMKS11.SA"}}}

Ticker BMKS11.SA não contém símbolo válido.
Ticker ESTR3.SA é válido.
Ticker ESTR4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: ESTR11.SA"}}}

Ticker ESTR11.SA não contém símbolo válido.
Ticker RVEE3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: RVEE4.SA"}}}

Ticker RVEE4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: RVEE11.SA"}}}

Ticker RVEE11.SA não contém símbolo válido.
Ticker AHEB3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: AHEB4.SA"}}}

Ticker AHEB4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: AHEB11.SA"}}}

Ticker AHEB11.SA não contém símbolo válido.
Ticker SHOW3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: SHOW4.SA"}}}

Ticker SHOW4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: SHOW11.SA"}}}

Ticker SHOW11.SA não contém símbolo válido.
Ticker CVCB3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CVCB4.SA"}}}

Ticker CVCB4.SA não contém símbolo válido.
Ticker CVCB11.SA é válido.
Ticker SMFT3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: SMFT4.SA"}}}

Ticker SMFT4.SA não contém símbolo válido.
Ticker SMFT11.SA é válido.
Ticker ANIM3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: ANIM4.SA"}}}

Ticker ANIM4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: ANIM11.SA"}}}

Ticker ANIM11.SA não contém símbolo válido.
Ticker ATED3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: ATED4.SA"}}}

Ticker ATED4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: ATED11.SA"}}}

Ticker ATED11.SA não contém símbolo válido.
Ticker BIED3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: BIED4.SA"}}}

Ticker BIED4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: BIED11.SA"}}}

Ticker BIED11.SA não contém símbolo válido.
Ticker COGN3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: COGN4.SA"}}}

Ticker COGN4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: COGN11.SA"}}}

Ticker COGN11.SA não contém símbolo válido.
Ticker CSED3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CSED4.SA"}}}

Ticker CSED4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CSED11.SA"}}}

Ticker CSED11.SA não contém símbolo válido.
Ticker SALT3.SA é válido.
Ticker SALT4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: SALT11.SA"}}}

Ticker SALT11.SA não contém símbolo válido.
Ticker OBTC3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: OBTC4.SA"}}}

Ticker OBTC4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: OBTC11.SA"}}}

Ticker OBTC11.SA não contém símbolo válido.
Ticker SEER3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: SEER4.SA"}}}

Ticker SEER4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: SEER11.SA"}}}

Ticker SEER11.SA não contém símbolo válido.
Ticker VTRU3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: VTRU4.SA"}}}

Ticker VTRU4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: VTRU11.SA"}}}

Ticker VTRU11.SA não contém símbolo válido.
Ticker YDUQ3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: YDUQ4.SA"}}}

Ticker YDUQ4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: YDUQ11.SA"}}}

Ticker YDUQ11.SA não contém símbolo válido.
Ticker RENT3.SA é válido.
Ticker RENT4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: RENT11.SA"}}}

Ticker RENT11.SA não contém símbolo válido.
Ticker MOVI3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: MOVI4.SA"}}}

Ticker MOVI4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: MOVI11.SA"}}}

Ticker MOVI11.SA não contém símbolo válido.
Ticker VAMO3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: VAMO4.SA"}}}

Ticker VAMO4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: VAMO11.SA"}}}

Ticker VAMO11.SA não contém símbolo válido.
Ticker DOTZ3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: DOTZ4.SA"}}}

Ticker DOTZ4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: DOTZ11.SA"}}}

Ticker DOTZ11.SA não contém símbolo válido.
Ticker BIOM3.SA é válido.
Ticker BIOM4.SA é válido.
Ticker BIOM11.SA é válido.
Ticker OFSA3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: OFSA4.SA"}}}

Ticker OFSA4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: OFSA11.SA"}}}

Ticker OFSA11.SA não contém símbolo válido.
Ticker AALR3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: AALR4.SA"}}}

Ticker AALR4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: AALR11.SA"}}}

Ticker AALR11.SA não contém símbolo válido.
Ticker DASA3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: DASA4.SA"}}}

Ticker DASA4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: DASA11.SA"}}}

Ticker DASA11.SA não contém símbolo válido.
Ticker FLRY3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: FLRY4.SA"}}}

Ticker FLRY4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: FLRY11.SA"}}}

Ticker FLRY11.SA não contém símbolo válido.
Ticker HAPV3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: HAPV4.SA"}}}

Ticker HAPV4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: HAPV11.SA"}}}

Ticker HAPV11.SA não contém símbolo válido.
Ticker MATD3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: MATD4.SA"}}}

Ticker MATD4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: MATD11.SA"}}}

Ticker MATD11.SA não contém símbolo válido.
Ticker ODPV3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: ODPV4.SA"}}}

Ticker ODPV4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: ODPV11.SA"}}}

Ticker ODPV11.SA não contém símbolo válido.
Ticker ONCO3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: ONCO4.SA"}}}

Ticker ONCO4.SA não contém símbolo válido.
Ticker ONCO11.SA é válido.
Ticker QUAL3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: QUAL4.SA"}}}

Ticker QUAL4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: QUAL11.SA"}}}

Ticker QUAL11.SA não contém símbolo válido.
Ticker RDOR3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: RDOR4.SA"}}}

Ticker RDOR4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: RDOR11.SA"}}}

Ticker RDOR11.SA não contém símbolo válido.
Ticker BALM3.SA é válido.
Ticker BALM4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: BALM11.SA"}}}

Ticker BALM11.SA não contém símbolo válido.
Ticker LMED3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: LMED4.SA"}}}

Ticker LMED4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: LMED11.SA"}}}

Ticker LMED11.SA não contém símbolo válido.
Ticker BLAU3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: BLAU4.SA"}}}

Ticker BLAU4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: BLAU11.SA"}}}

Ticker BLAU11.SA não contém símbolo válido.
Ticker DMVF3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: DMVF4.SA"}}}

Ticker DMVF4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: DMVF11.SA"}}}

Ticker DMVF11.SA não contém símbolo válido.
Ticker PNVL3.SA é válido.
Ticker PNVL4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: PNVL11.SA"}}}

Ticker PNVL11.SA não contém símbolo válido.
Ticker EUFA3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: EUFA4.SA"}}}

Ticker EUFA4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: EUFA11.SA"}}}

Ticker EUFA11.SA não contém símbolo válido.
Ticker HYPE3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: HYPE4.SA"}}}

Ticker HYPE4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: HYPE11.SA"}}}

Ticker HYPE11.SA não contém símbolo válido.
Ticker PGMN3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: PGMN4.SA"}}}

Ticker PGMN4.SA não contém símbolo válido.
Ticker PGMN11.SA é válido.
Ticker PFRM3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: PFRM4.SA"}}}

Ticker PFRM4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: PFRM11.SA"}}}

Ticker PFRM11.SA não contém símbolo válido.
Ticker RADL3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: RADL4.SA"}}}

Ticker RADL4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: RADL11.SA"}}}

Ticker RADL11.SA não contém símbolo válido.
Ticker VVEO3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: VVEO4.SA"}}}

Ticker VVEO4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: VVEO11.SA"}}}

Ticker VVEO11.SA não contém símbolo válido.
Ticker INTB3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: INTB4.SA"}}}

Ticker INTB4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: INTB11.SA"}}}

Ticker INTB11.SA não contém símbolo válido.
Ticker MLAS3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: MLAS4.SA"}}}

Ticker MLAS4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: MLAS11.SA"}}}

Ticker MLAS11.SA não contém símbolo válido.
Ticker POSI3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: POSI4.SA"}}}

Ticker POSI4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: POSI11.SA"}}}

Ticker POSI11.SA não contém símbolo válido.
Ticker BMOB3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: BMOB4.SA"}}}

Ticker BMOB4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: BMOB11.SA"}}}

Ticker BMOB11.SA não contém símbolo válido.
Ticker BRQB3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: BRQB4.SA"}}}

Ticker BRQB4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: BRQB11.SA"}}}

Ticker BRQB11.SA não contém símbolo válido.
Ticker ENJU3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: ENJU4.SA"}}}

Ticker ENJU4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: ENJU11.SA"}}}

Ticker ENJU11.SA não contém símbolo válido.
Ticker IFCM3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: IFCM4.SA"}}}

Ticker IFCM4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: IFCM11.SA"}}}

Ticker IFCM11.SA não contém símbolo válido.
Ticker LWSA3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: LWSA4.SA"}}}

Ticker LWSA4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: LWSA11.SA"}}}

Ticker LWSA11.SA não contém símbolo válido.
Ticker CASH3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CASH4.SA"}}}

Ticker CASH4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CASH11.SA"}}}

Ticker CASH11.SA não contém símbolo válido.
Ticker NGRD3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: NGRD4.SA"}}}

Ticker NGRD4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: NGRD11.SA"}}}

Ticker NGRD11.SA não contém símbolo válido.
Ticker PDTC3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: PDTC4.SA"}}}

Ticker PDTC4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: PDTC11.SA"}}}

Ticker PDTC11.SA não contém símbolo válido.
Ticker QUSW3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: QUSW4.SA"}}}

Ticker QUSW4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: QUSW11.SA"}}}

Ticker QUSW11.SA não contém símbolo válido.
Ticker TRAD3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: TRAD4.SA"}}}

Ticker TRAD4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: TRAD11.SA"}}}

Ticker TRAD11.SA não contém símbolo válido.
Ticker TOTS3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: TOTS4.SA"}}}

Ticker TOTS4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: TOTS11.SA"}}}

Ticker TOTS11.SA não contém símbolo válido.
Ticker WDCN3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: WDCN4.SA"}}}

Ticker WDCN4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: WDCN11.SA"}}}

Ticker WDCN11.SA não contém símbolo válido.
Ticker BRST3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: BRST4.SA"}}}

Ticker BRST4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: BRST11.SA"}}}

Ticker BRST11.SA não contém símbolo válido.
Ticker DESK3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: DESK4.SA"}}}

Ticker DESK4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: DESK11.SA"}}}

Ticker DESK11.SA não contém símbolo válido.
Ticker OIBR3.SA é válido.
Ticker OIBR4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: OIBR11.SA"}}}

Ticker OIBR11.SA não contém símbolo válido.
Ticker TELB3.SA é válido.
Ticker TELB4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: TELB11.SA"}}}

Ticker TELB11.SA não contém símbolo válido.
Ticker VIVT3.SA é válido.
Ticker VIVT4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: VIVT11.SA"}}}

Ticker VIVT11.SA não contém símbolo válido.
Ticker TIMS3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: TIMS4.SA"}}}

Ticker TIMS4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: TIMS11.SA"}}}

Ticker TIMS11.SA não contém símbolo válido.
Ticker FIQE3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: FIQE4.SA"}}}

Ticker FIQE4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: FIQE11.SA"}}}

Ticker FIQE11.SA não contém símbolo válido.
Ticker AESO3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: AESO4.SA"}}}

Ticker AESO4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: AESO11.SA"}}}

Ticker AESO11.SA não contém símbolo válido.
Ticker AFLT3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: AFLT4.SA"}}}

Ticker AFLT4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: AFLT11.SA"}}}

Ticker AFLT11.SA não contém símbolo válido.
Ticker ALUP3.SA é válido.
Ticker ALUP4.SA é válido.
Ticker ALUP11.SA é válido.
Ticker CBEE3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CBEE4.SA"}}}

Ticker CBEE4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CBEE11.SA"}}}

Ticker CBEE11.SA não contém símbolo válido.
Ticker AURE3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: AURE4.SA"}}}

Ticker AURE4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: AURE11.SA"}}}

Ticker AURE11.SA não contém símbolo válido.
Ticker AXIA3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: AXIA4.SA"}}}

Ticker AXIA4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: AXIA11.SA"}}}

Ticker AXIA11.SA não contém símbolo válido.
Ticker CEBR3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CEBR4.SA"}}}

Ticker CEBR4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CEBR11.SA"}}}

Ticker CEBR11.SA não contém símbolo válido.
Ticker CEED3.SA é válido.
Ticker CEED4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CEED11.SA"}}}

Ticker CEED11.SA não contém símbolo válido.
Ticker CLSC3.SA é válido.
Ticker CLSC4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CLSC11.SA"}}}

Ticker CLSC11.SA não contém símbolo válido.
Ticker GPAR3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: GPAR4.SA"}}}

Ticker GPAR4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: GPAR11.SA"}}}

Ticker GPAR11.SA não contém símbolo válido.
Ticker CMIG3.SA é válido.
Ticker CMIG4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CMIG11.SA"}}}

Ticker CMIG11.SA não contém símbolo válido.
Ticker CEEB3.SA é válido.
Ticker CEEB4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CEEB11.SA"}}}

Ticker CEEB11.SA não contém símbolo válido.
Ticker COCE3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: COCE4.SA"}}}

Ticker COCE4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: COCE11.SA"}}}

Ticker COCE11.SA não contém símbolo válido.
Ticker COMR3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: COMR4.SA"}}}

Ticker COMR4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: COMR11.SA"}}}

Ticker COMR11.SA não contém símbolo válido.
Ticker CPLE3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CPLE4.SA"}}}

Ticker CPLE4.SA não contém símbolo válido.
Ticker CPLE11.SA é válido.
Ticker CPFE3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CPFE4.SA"}}}

Ticker CPFE4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CPFE11.SA"}}}

Ticker CPFE11.SA não contém símbolo válido.
Ticker EKTR3.SA é válido.
Ticker EKTR4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: EKTR11.SA"}}}

Ticker EKTR11.SA não contém símbolo válido.
Ticker EMAE3.SA é válido.
Ticker EMAE4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: EMAE11.SA"}}}

Ticker EMAE11.SA não contém símbolo válido.
Ticker ENGI3.SA é válido.
Ticker ENGI4.SA é válido.
Ticker ENGI11.SA é válido.
Ticker ENMT3.SA é válido.
Ticker ENMT4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: ENMT11.SA"}}}

Ticker ENMT11.SA não contém símbolo válido.
Ticker ENEV3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: ENEV4.SA"}}}

Ticker ENEV4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: ENEV11.SA"}}}

Ticker ENEV11.SA não contém símbolo válido.
Ticker EGIE3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: EGIE4.SA"}}}

Ticker EGIE4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: EGIE11.SA"}}}

Ticker EGIE11.SA não contém símbolo válido.
Ticker EQPA3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: EQPA4.SA"}}}

Ticker EQPA4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: EQPA11.SA"}}}

Ticker EQPA11.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: EQMA3.SA"}}}

Ticker EQMA3.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: EQMA4.SA"}}}

Ticker EQMA4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: EQMA11.SA"}}}

Ticker EQMA11.SA não contém símbolo válido.
Ticker EQTL3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: EQTL4.SA"}}}

Ticker EQTL4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: EQTL11.SA"}}}

Ticker EQTL11.SA não contém símbolo válido.
Ticker GEPA3.SA é válido.
Ticker GEPA4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: GEPA11.SA"}}}

Ticker GEPA11.SA não contém símbolo válido.
Ticker ISAE3.SA é válido.
Ticker ISAE4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: ISAE11.SA"}}}

Ticker ISAE11.SA não contém símbolo válido.
Ticker LIGH3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: LIGH4.SA"}}}

Ticker LIGH4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: LIGH11.SA"}}}

Ticker LIGH11.SA não contém símbolo válido.
Ticker LIGT3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: LIGT4.SA"}}}

Ticker LIGT4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: LIGT11.SA"}}}

Ticker LIGT11.SA não contém símbolo válido.
Ticker NEOE3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: NEOE4.SA"}}}

Ticker NEOE4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: NEOE11.SA"}}}

Ticker NEOE11.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: PRMN3.SA"}}}

Ticker PRMN3.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: PRMN4.SA"}}}

Ticker PRMN4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: PRMN11.SA"}}}

Ticker PRMN11.SA não contém símbolo válido.
Ticker REDE3.SA é válido.
Ticker REDE4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: REDE11.SA"}}}

Ticker REDE11.SA não contém símbolo válido.
Ticker RNEW3.SA é válido.
Ticker RNEW4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: RNEW11.SA"}}}

Ticker RNEW11.SA não contém símbolo válido.
Ticker RIOS3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: RIOS4.SA"}}}

Ticker RIOS4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: RIOS11.SA"}}}

Ticker RIOS11.SA não contém símbolo válido.
Ticker TAEE3.SA é válido.
Ticker TAEE4.SA é válido.
Ticker TAEE11.SA é válido.
Ticker AMBP3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: AMBP4.SA"}}}

Ticker AMBP4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: AMBP11.SA"}}}

Ticker AMBP11.SA não contém símbolo válido.
Ticker CASN3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CASN4.SA"}}}

Ticker CASN4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CASN11.SA"}}}

Ticker CASN11.SA não contém símbolo válido.
Ticker CSMG3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CSMG4.SA"}}}

Ticker CSMG4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CSMG11.SA"}}}

Ticker CSMG11.SA não contém símbolo válido.
Ticker IGSN3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: IGSN4.SA"}}}

Ticker IGSN4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: IGSN11.SA"}}}

Ticker IGSN11.SA não contém símbolo válido.
Ticker ORVR3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: ORVR4.SA"}}}

Ticker ORVR4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: ORVR11.SA"}}}

Ticker ORVR11.SA não contém símbolo válido.
Ticker SBSP3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: SBSP4.SA"}}}

Ticker SBSP4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: SBSP11.SA"}}}

Ticker SBSP11.SA não contém símbolo válido.
Ticker SAPR3.SA é válido.
Ticker SAPR4.SA é válido.
Ticker SAPR11.SA é válido.
Ticker CEGR3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CEGR4.SA"}}}

Ticker CEGR4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CEGR11.SA"}}}

Ticker CEGR11.SA não contém símbolo válido.
Ticker CGAS3.SA é válido.
Ticker CGAS4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CGAS11.SA"}}}

Ticker CGAS11.SA não contém símbolo válido.
Ticker PASS3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: PASS4.SA"}}}

Ticker PASS4.SA não contém símbolo válido.
Ticker PASS11.SA é válido.
Ticker ABCB3.SA é válido.
Ticker ABCB4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: ABCB11.SA"}}}

Ticker ABCB11.SA não contém símbolo válido.
Ticker RPAD3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: RPAD4.SA"}}}

Ticker RPAD4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: RPAD11.SA"}}}

Ticker RPAD11.SA não contém símbolo válido.
Ticker BAZA3.SA é válido.
Ticker BAZA4.SA é válido.
Ticker BAZA11.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: BMGB3.SA"}}}

Ticker BMGB3.SA não contém símbolo válido.
Ticker BMGB4.SA é válido.
Ticker BMGB11.SA é válido.
Ticker BGIP3.SA é válido.
Ticker BGIP4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: BGIP11.SA"}}}

Ticker BGIP11.SA não contém símbolo válido.
Ticker BEES3.SA é válido.
Ticker BEES4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: BEES11.SA"}}}

Ticker BEES11.SA não contém símbolo válido.
Ticker BPAR3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: BPAR4.SA"}}}

Ticker BPAR4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: BPAR11.SA"}}}

Ticker BPAR11.SA não contém símbolo válido.
Ticker BRSR3.SA é válido.
Ticker BRSR4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: BRSR11.SA"}}}

Ticker BRSR11.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: BRBI3.SA"}}}

Ticker BRBI3.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: BRBI4.SA"}}}

Ticker BRBI4.SA não contém símbolo válido.
Ticker BRBI11.SA é válido.
Ticker BBDC3.SA é válido.
Ticker BBDC4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: BBDC11.SA"}}}

Ticker BBDC11.SA não contém símbolo válido.
Ticker BBAS3.SA é válido.
Ticker BBAS4.SA é válido.
Ticker BBAS11.SA é válido.
Ticker BSLI3.SA é válido.
Ticker BSLI4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: BSLI11.SA"}}}

Ticker BSLI11.SA não contém símbolo válido.
Ticker BPAC3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: BPAC4.SA"}}}

Ticker BPAC4.SA não contém símbolo válido.
Ticker BPAC11.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: INBR3.SA"}}}

Ticker INBR3.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: INBR4.SA"}}}

Ticker INBR4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: INBR11.SA"}}}

Ticker INBR11.SA não contém símbolo válido.
Ticker ITUB3.SA é válido.
Ticker ITUB4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: ITUB11.SA"}}}

Ticker ITUB11.SA não contém símbolo válido.
Ticker BMIN3.SA é válido.
Ticker BMIN4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: BMIN11.SA"}}}

Ticker BMIN11.SA não contém símbolo válido.
Ticker BMEB3.SA é válido.
Ticker BMEB4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: BMEB11.SA"}}}

Ticker BMEB11.SA não contém símbolo válido.
Ticker BNBR3.SA é válido.
Ticker BNBR4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: BNBR11.SA"}}}

Ticker BNBR11.SA não contém símbolo válido.
Ticker PINE3.SA é válido.
Ticker PINE4.SA é válido.
Ticker PINE11.SA é válido.
Ticker SANB3.SA é válido.
Ticker SANB4.SA é válido.
Ticker SANB11.SA é válido.
Ticker MERC3.SA é válido.
Ticker MERC4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: MERC11.SA"}}}

Ticker MERC11.SA não contém símbolo válido.
Ticker FIGE3.SA é válido.
Ticker FIGE4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: FIGE11.SA"}}}

Ticker FIGE11.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: BSCS3.SA"}}}

Ticker BSCS3.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: BSCS4.SA"}}}

Ticker BSCS4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: BSCS11.SA"}}}

Ticker BSCS11.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: RBRA3.SA"}}}

Ticker RBRA3.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: RBRA4.SA"}}}

Ticker RBRA4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: RBRA11.SA"}}}

Ticker RBRA11.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: PLSC3.SA"}}}

Ticker PLSC3.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: PLSC4.SA"}}}

Ticker PLSC4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: PLSC11.SA"}}}

Ticker PLSC11.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: G2DI3.SA"}}}

Ticker G2DI3.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: G2DI4.SA"}}}

Ticker G2DI4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: G2DI11.SA"}}}

Ticker G2DI11.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: PPLA3.SA"}}}

Ticker PPLA3.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: PPLA4.SA"}}}

Ticker PPLA4.SA não contém símbolo válido.
Ticker PPLA11.SA é válido.
Ticker B3SA3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: B3SA4.SA"}}}

Ticker B3SA4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: B3SA11.SA"}}}

Ticker B3SA11.SA não contém símbolo válido.
Ticker CSUD3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CSUD4.SA"}}}

Ticker CSUD4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CSUD11.SA"}}}

Ticker CSUD11.SA não contém símbolo válido.
Ticker BBSE3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: BBSE4.SA"}}}

Ticker BBSE4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: BBSE11.SA"}}}

Ticker BBSE11.SA não contém símbolo válido.
Ticker CXSE3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CXSE4.SA"}}}

Ticker CXSE4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CXSE11.SA"}}}

Ticker CXSE11.SA não contém símbolo válido.
Ticker PSSA3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: PSSA4.SA"}}}

Ticker PSSA4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: PSSA11.SA"}}}

Ticker PSSA11.SA não contém símbolo válido.
Ticker IRBR3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: IRBR4.SA"}}}

Ticker IRBR4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: IRBR11.SA"}}}

Ticker IRBR11.SA não contém símbolo válido.
Ticker WIZC3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: WIZC4.SA"}}}

Ticker WIZC4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: WIZC11.SA"}}}

Ticker WIZC11.SA não contém símbolo válido.
Ticker ALOS3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: ALOS4.SA"}}}

Ticker ALOS4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: ALOS11.SA"}}}

Ticker ALOS11.SA não contém símbolo válido.
Ticker GSHP3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: GSHP4.SA"}}}

Ticker GSHP4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: GSHP11.SA"}}}

Ticker GSHP11.SA não contém símbolo válido.
Ticker HBTS3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: HBTS4.SA"}}}

Ticker HBTS4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: HBTS11.SA"}}}

Ticker HBTS11.SA não contém símbolo válido.
Ticker HBRE3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: HBRE4.SA"}}}

Ticker HBRE4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: HBRE11.SA"}}}

Ticker HBRE11.SA não contém símbolo válido.
Ticker IGTI3.SA é válido.
Ticker IGTI4.SA é válido.
Ticker IGTI11.SA é válido.
Ticker LOGG3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: LOGG4.SA"}}}

Ticker LOGG4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: LOGG11.SA"}}}

Ticker LOGG11.SA não contém símbolo válido.
Ticker MULT3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: MULT4.SA"}}}

Ticker MULT4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: MULT11.SA"}}}

Ticker MULT11.SA não contém símbolo válido.
Ticker NORD3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: NORD4.SA"}}}

Ticker NORD4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: NORD11.SA"}}}

Ticker NORD11.SA não contém símbolo válido.
Ticker PEAB3.SA é válido.
Ticker PEAB4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: PEAB11.SA"}}}

Ticker PEAB11.SA não contém símbolo válido.
Ticker SCAR3.SA é válido.
Ticker SCAR4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: SCAR11.SA"}}}

Ticker SCAR11.SA não contém símbolo válido.
Ticker SYNE3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: SYNE4.SA"}}}

Ticker SYNE4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: SYNE11.SA"}}}

Ticker SYNE11.SA não contém símbolo válido.
Ticker LPSB3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: LPSB4.SA"}}}

Ticker LPSB4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: LPSB11.SA"}}}

Ticker LPSB11.SA não contém símbolo válido.
Ticker NEXP3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: NEXP4.SA"}}}

Ticker NEXP4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: NEXP11.SA"}}}

Ticker NEXP11.SA não contém símbolo válido.
Ticker ARND3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: ARND4.SA"}}}

Ticker ARND4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: ARND11.SA"}}}

Ticker ARND11.SA não contém símbolo válido.
Ticker EPAR3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: EPAR4.SA"}}}

Ticker EPAR4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: EPAR11.SA"}}}

Ticker EPAR11.SA não contém símbolo válido.
Ticker ITSA3.SA é válido.
Ticker ITSA4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: ITSA11.SA"}}}

Ticker ITSA11.SA não contém símbolo válido.
Ticker SIMH3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: SIMH4.SA"}}}

Ticker SIMH4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: SIMH11.SA"}}}

Ticker SIMH11.SA não contém símbolo válido.
Ticker ADMF3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: ADMF4.SA"}}}

Ticker ADMF4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: ADMF11.SA"}}}

Ticker ADMF11.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CTBA3.SA"}}}

Ticker CTBA3.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CTBA4.SA"}}}

Ticker CTBA4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CTBA11.SA"}}}

Ticker CTBA11.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: MCRJ3.SA"}}}

Ticker MCRJ3.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: MCRJ4.SA"}}}

Ticker MCRJ4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: MCRJ11.SA"}}}

Ticker MCRJ11.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: PMSP3.SA"}}}

Ticker PMSP3.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: PMSP4.SA"}}}

Ticker PMSP4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: PMSP11.SA"}}}

Ticker PMSP11.SA não contém símbolo válido.
Ticker QVQP3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: QVQP4.SA"}}}

Ticker QVQP4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: QVQP11.SA"}}}

Ticker QVQP11.SA não contém símbolo válido.
Ticker BETP3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: BETP4.SA"}}}

Ticker BETP4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: BETP11.SA"}}}

Ticker BETP11.SA não contém símbolo válido.
Ticker MAPT3.SA é válido.
Ticker MAPT4.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: MAPT11.SA"}}}

Ticker MAPT11.SA não contém símbolo válido.
Ticker OPGM3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: OPGM4.SA"}}}

Ticker OPGM4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: OPGM11.SA"}}}

Ticker OPGM11.SA não contém símbolo válido.
Ticker PPAR3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: PPAR4.SA"}}}

Ticker PPAR4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: PPAR11.SA"}}}

Ticker PPAR11.SA não contém símbolo válido.
Ticker PRPT3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: PRPT4.SA"}}}

Ticker PRPT4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: PRPT11.SA"}}}

Ticker PRPT11.SA não contém símbolo válido.
Ticker OPSE3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: OPSE4.SA"}}}

Ticker OPSE4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: OPSE11.SA"}}}

Ticker OPSE11.SA não contém símbolo válido.
Ticker OPTS3.SA é válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: OPTS4.SA"}}}

Ticker OPTS4.SA não contém símbolo válido.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: OPTS11.SA"}}}

Ticker OPTS11.SA não contém símbolo válido.
==============================================================
A quantidade de tickers válidos é: 505
Tickers válidos: ['AZTE3.SA', 'AZTE11.SA', 'BRAV3.SA', 'CSAN3.SA', 'RPMG3.SA', 'RPMG4.SA', 'PETR3.SA', 'PETR4.SA', 'RECV3.SA', 'PRIO3.SA', 'RAIZ4.SA', 'UGPA3.SA', 'UGPA4.SA', 'LUPA3.SA', 'LUPA11.SA', 'OPCT3.SA', 'OSXB3.SA', 'VBBR3.SA', 'BRAP3.SA', 'BRAP4.SA', 'CBAV3.SA', 'CMIN3.SA', 'LTLA3.SA', 'VALE3.SA', 'FESA3.SA', 'FESA4.SA', 'GGBR3.SA', 'GGBR4.SA', 'GOAU3.SA', 'GOAU4.SA', 'CSNA3.SA', 'USIM3.SA', 'HAGA3.SA', 'HAGA4.SA', 'MGEL3.SA', 'MGEL4.SA', 'PATI3.SA', 'PATI4.SA', 'TKNO3.SA', 'TKNO4.SA', 'PMAM3.SA', 'PMAM4.SA', 'PMAM11.SA', 'BRKM3.SA', 'DEXP3.SA', 'DEXP4.SA', 'FHER3.SA', 'NUTR3.SA', 'VITT3.SA', 'CRPG3.SA', 'UNIP3.SA', 'DXCO3.SA', 'EUCA3.SA', 'EUCA4.SA', 'KLBN3.SA', 'KLBN4.SA', 'KLBN11.SA', 'MSPA3.SA', 'MSPA4.SA', 'NEMO4.SA', 'SUZB3.SA', 'RANI3.SA', 'RANI4.SA', 'SNSY3.SA', 'ETER3.SA', 'ETER4.SA', 'PTBL3.SA', 'PTBL4.SA', 'AZEV3.SA', 'AZEV4.SA', 'AZEV11.SA', 'SOND3.SA', 'ARML3.SA', 'MILS3.SA', 'PRNR3.SA', 'EMBJ3.SA', 'FRAS3.SA', 'FRAS4.SA', 'POMO3.SA', 'POMO4.SA', 'RAPT3.SA', 'RAPT4.SA', 'RCSL3.SA', 'RCSL4.SA', 'RSUL4.SA', 'TUPY3.SA', 'TUPY4.SA', 'MWET3.SA', 'MWET4.SA', 'SHUL3.SA', 'SHUL4.SA', 'WEGE3.SA', 'WEGE4.SA', 'EALT3.SA', 'EALT4.SA', 'AERI3.SA', 'BDLL3.SA', 'BDLL4.SA', 'INEP3.SA', 'INEP4.SA', 'INEP11.SA', 'KEPL3.SA', 'KEPL4.SA', 'FRIO3.SA', 'PTCA3.SA', 'PTCA11.SA', 'ROMI3.SA', 'ROMI4.SA', 'MTSA3.SA', 'MTSA4.SA', 'TASA3.SA', 'TASA4.SA', 'AZUL11.SA', 'GOLL3.SA', 'GOLL4.SA', 'GOLL11.SA', 'VSPT3.SA', 'VSPT4.SA', 'RAIL3.SA', 'HBSA3.SA', 'LOGN3.SA', 'LUXM4.SA', 'JSLG3.SA', 'JSLG11.SA', 'SEQL3.SA', 'TGMA3.SA', 'CRTE3.SA', 'ECOR3.SA', 'MOTV3.SA', 'TPIS3.SA', 'HMOB3.SA', 'PSVM11.SA', 'BBML3.SA', 'CTAX3.SA', 'CTAX4.SA', 'DTCY3.SA', 'DTCY4.SA', 'ALPK3.SA', 'GGPS3.SA', 'VLID3.SA', 'MMAQ3.SA', 'MMAQ4.SA', 'RBNS11.SA', 'WLMM3.SA', 'WLMM4.SA', 'TTEN3.SA', 'AGXY3.SA', 'APTI3.SA', 'APTI4.SA', 'SOJA3.SA', 'AGRO3.SA', 'CTCA3.SA', 'EGGY3.SA', 'SLCE3.SA', 'LAND3.SA', 'JALL3.SA', 'SMTO3.SA', 'BAUH3.SA', 'BAUH4.SA', 'BAUH11.SA', 'FICT3.SA', 'JBSS3.SA', 'MBRF3.SA', 'MBRF11.SA', 'BEEF3.SA', 'BEEF11.SA', 'MNPR3.SA', 'MNPR4.SA', 'CAML3.SA', 'JOPA3.SA', 'JOPA4.SA', 'MDIA3.SA', 'ODER3.SA', 'ODER4.SA', 'ABEV3.SA', 'ESPA3.SA', 'NATU3.SA', 'BOBR3.SA', 'BOBR4.SA', 'ASAI3.SA', 'GMAT3.SA', 'PCAR3.SA', 'PCAR4.SA', 'AZZA3.SA', 'CEAB3.SA', 'CGRA3.SA', 'CGRA4.SA', 'AMAR3.SA', 'AMAR11.SA', 'LREN3.SA', 'LREN4.SA', 'RIAA3.SA', 'VSTE3.SA', 'ALLD3.SA', 'BHIA3.SA', 'MGLU3.SA', 'AMER3.SA', 'AMER11.SA', 'SBFG3.SA', 'LLBI3.SA', 'LLBI4.SA', 'AUAU3.SA', 'LJQQ3.SA', 'AVLL3.SA', 'AVLL11.SA', 'CALI3.SA', 'CALI4.SA', 'CURY3.SA', 'CYRE3.SA', 'CYRE4.SA', 'DIRR3.SA', 'EVEN3.SA', 'EZTC3.SA', 'FIEI3.SA', 'GFSA3.SA', 'GFSA11.SA', 'HBOR3.SA', 'INNC3.SA', 'JHSF3.SA', 'JFEN3.SA', 'KLAS3.SA', 'LAVV3.SA', 'MELK3.SA', 'MTRE3.SA', 'MDNE3.SA', 'MRVE3.SA', 'PDGR3.SA', 'PLPL3.SA', 'CCTY3.SA', 'RSID3.SA', 'TCSA3.SA', 'TEND3.SA', 'TRIS3.SA', 'VIVR3.SA', 'VIVR11.SA', 'CEDO3.SA', 'CEDO4.SA', 'DOHL3.SA', 'DOHL4.SA', 'CATA3.SA', 'CATA4.SA', 'CTKA3.SA', 'CTKA4.SA', 'PTNT3.SA', 'PTNT4.SA', 'CTSA3.SA', 'CTSA4.SA', 'TXRX3.SA', 'TXRX4.SA', 'TFCO4.SA', 'ALPA3.SA', 'ALPA4.SA', 'CAMB3.SA', 'CAMB4.SA', 'GRND3.SA', 'VULC3.SA', 'VULC4.SA', 'MNDL3.SA', 'MNDL4.SA', 'TECN3.SA', 'VIVA3.SA', 'WHRL3.SA', 'WHRL4.SA', 'TOKY3.SA', 'TOKY11.SA', 'UCAS3.SA', 'WEST3.SA', 'HETA3.SA', 'HETA4.SA', 'AMOB3.SA', 'MYPK3.SA', 'MYPK4.SA', 'LEVE3.SA', 'LEVE4.SA', 'PLAS3.SA', 'HOOT3.SA', 'HOOT4.SA', 'MEAL3.SA', 'BMKS3.SA', 'ESTR3.SA', 'ESTR4.SA', 'RVEE3.SA', 'AHEB3.SA', 'SHOW3.SA', 'CVCB3.SA', 'CVCB11.SA', 'SMFT3.SA', 'SMFT11.SA', 'ANIM3.SA', 'ATED3.SA', 'BIED3.SA', 'COGN3.SA', 'CSED3.SA', 'SALT3.SA', 'SALT4.SA', 'OBTC3.SA', 'SEER3.SA', 'VTRU3.SA', 'YDUQ3.SA', 'RENT3.SA', 'RENT4.SA', 'MOVI3.SA', 'VAMO3.SA', 'DOTZ3.SA', 'BIOM3.SA', 'BIOM4.SA', 'BIOM11.SA', 'OFSA3.SA', 'AALR3.SA', 'DASA3.SA', 'FLRY3.SA', 'HAPV3.SA', 'MATD3.SA', 'ODPV3.SA', 'ONCO3.SA', 'ONCO11.SA', 'QUAL3.SA', 'RDOR3.SA', 'BALM3.SA', 'BALM4.SA', 'LMED3.SA', 'BLAU3.SA', 'DMVF3.SA', 'PNVL3.SA', 'PNVL4.SA', 'EUFA3.SA', 'HYPE3.SA', 'PGMN3.SA', 'PGMN11.SA', 'PFRM3.SA', 'RADL3.SA', 'VVEO3.SA', 'INTB3.SA', 'MLAS3.SA', 'POSI3.SA', 'BMOB3.SA', 'BRQB3.SA', 'ENJU3.SA', 'IFCM3.SA', 'LWSA3.SA', 'CASH3.SA', 'NGRD3.SA', 'PDTC3.SA', 'QUSW3.SA', 'TRAD3.SA', 'TOTS3.SA', 'WDCN3.SA', 'BRST3.SA', 'DESK3.SA', 'OIBR3.SA', 'OIBR4.SA', 'TELB3.SA', 'TELB4.SA', 'VIVT3.SA', 'VIVT4.SA', 'TIMS3.SA', 'FIQE3.SA', 'AESO3.SA', 'AFLT3.SA', 'ALUP3.SA', 'ALUP4.SA', 'ALUP11.SA', 'CBEE3.SA', 'AURE3.SA', 'AXIA3.SA', 'CEBR3.SA', 'CEED3.SA', 'CEED4.SA', 'CLSC3.SA', 'CLSC4.SA', 'GPAR3.SA', 'CMIG3.SA', 'CMIG4.SA', 'CEEB3.SA', 'CEEB4.SA', 'COCE3.SA', 'COMR3.SA', 'CPLE3.SA', 'CPLE11.SA', 'CPFE3.SA', 'EKTR3.SA', 'EKTR4.SA', 'EMAE3.SA', 'EMAE4.SA', 'ENGI3.SA', 'ENGI4.SA', 'ENGI11.SA', 'ENMT3.SA', 'ENMT4.SA', 'ENEV3.SA', 'EGIE3.SA', 'EQPA3.SA', 'EQTL3.SA', 'GEPA3.SA', 'GEPA4.SA', 'ISAE3.SA', 'ISAE4.SA', 'LIGH3.SA', 'LIGT3.SA', 'NEOE3.SA', 'REDE3.SA', 'REDE4.SA', 'RNEW3.SA', 'RNEW4.SA', 'RIOS3.SA', 'TAEE3.SA', 'TAEE4.SA', 'TAEE11.SA', 'AMBP3.SA', 'CASN3.SA', 'CSMG3.SA', 'IGSN3.SA', 'ORVR3.SA', 'SBSP3.SA', 'SAPR3.SA', 'SAPR4.SA', 'SAPR11.SA', 'CEGR3.SA', 'CGAS3.SA', 'CGAS4.SA', 'PASS3.SA', 'PASS11.SA', 'ABCB3.SA', 'ABCB4.SA', 'RPAD3.SA', 'BAZA3.SA', 'BAZA4.SA', 'BAZA11.SA', 'BMGB4.SA', 'BMGB11.SA', 'BGIP3.SA', 'BGIP4.SA', 'BEES3.SA', 'BEES4.SA', 'BPAR3.SA', 'BRSR3.SA', 'BRSR4.SA', 'BRBI11.SA', 'BBDC3.SA', 'BBDC4.SA', 'BBAS3.SA', 'BBAS4.SA', 'BBAS11.SA', 'BSLI3.SA', 'BSLI4.SA', 'BPAC3.SA', 'BPAC11.SA', 'ITUB3.SA', 'ITUB4.SA', 'BMIN3.SA', 'BMIN4.SA', 'BMEB3.SA', 'BMEB4.SA', 'BNBR3.SA', 'BNBR4.SA', 'PINE3.SA', 'PINE4.SA', 'PINE11.SA', 'SANB3.SA', 'SANB4.SA', 'SANB11.SA', 'MERC3.SA', 'MERC4.SA', 'FIGE3.SA', 'FIGE4.SA', 'PPLA11.SA', 'B3SA3.SA', 'CSUD3.SA', 'BBSE3.SA', 'CXSE3.SA', 'PSSA3.SA', 'IRBR3.SA', 'WIZC3.SA', 'ALOS3.SA', 'GSHP3.SA', 'HBTS3.SA', 'HBRE3.SA', 'IGTI3.SA', 'IGTI4.SA', 'IGTI11.SA', 'LOGG3.SA', 'MULT3.SA', 'NORD3.SA', 'PEAB3.SA', 'PEAB4.SA', 'SCAR3.SA', 'SCAR4.SA', 'SYNE3.SA', 'LPSB3.SA', 'NEXP3.SA', 'ARND3.SA', 'EPAR3.SA', 'ITSA3.SA', 'ITSA4.SA', 'SIMH3.SA', 'ADMF3.SA', 'QVQP3.SA', 'BETP3.SA', 'MAPT3.SA', 'MAPT4.SA', 'OPGM3.SA', 'PPAR3.SA', 'PRPT3.SA', 'OPSE3.SA', 'OPTS3.SA']

A quantidade de tickers que geraram erro 404 ou informações vazias é: 602
Tickers que geraram erro 404 ou informações vazias: ['AZTE4.SA', 'BRAV4.SA', 'BRAV11.SA', 'CSAN4.SA', 'CSAN11.SA', 'RPMG11.SA', 'PETR11.SA', 'RECV4.SA', 'RECV11.SA', 'PRIO4.SA', 'PRIO11.SA', 'RAIZ3.SA', 'RAIZ11.SA', 'UGPA11.SA', 'LUPA4.SA', 'OPCT4.SA', 'OPCT11.SA', 'OSXB4.SA', 'OSXB11.SA', 'VBBR4.SA', 'VBBR11.SA', 'AURA3.SA', 'AURA4.SA', 'AURA11.SA', 'BRAP11.SA', 'CBAV4.SA', 'CBAV11.SA', 'CMIN4.SA', 'CMIN11.SA', 'LTEL3.SA', 'LTEL4.SA', 'LTEL11.SA', 'LTLA4.SA', 'LTLA11.SA', 'VALE4.SA', 'VALE11.SA', 'FESA11.SA', 'GGBR11.SA', 'GOAU11.SA', 'CSNA4.SA', 'CSNA11.SA', 'USIM4.SA', 'USIM11.SA', 'HAGA11.SA', 'MGEL11.SA', 'PATI11.SA', 'TKNO11.SA', 'BRKM4.SA', 'BRKM11.SA', 'DEXP11.SA', 'FHER4.SA', 'FHER11.SA', 'NUTR4.SA', 'NUTR11.SA', 'VITT4.SA', 'VITT11.SA', 'CRPG4.SA', 'CRPG11.SA', 'UNIP4.SA', 'UNIP11.SA', 'DXCO4.SA', 'DXCO11.SA', 'EUCA11.SA', 'MSPA11.SA', 'NEMO3.SA', 'NEMO11.SA', 'SUZB4.SA', 'SUZB11.SA', 'RANI11.SA', 'SNSY4.SA', 'SNSY11.SA', 'ETER11.SA', 'PTBL11.SA', 'SOND4.SA', 'SOND11.SA', 'ARML4.SA', 'ARML11.SA', 'MILS4.SA', 'MILS11.SA', 'PRNR4.SA', 'PRNR11.SA', 'EMBJ4.SA', 'EMBJ11.SA', 'FRAS11.SA', 'POMO11.SA', 'RAPT11.SA', 'RCSL11.SA', 'RSUL3.SA', 'RSUL11.SA', 'TUPY11.SA', 'MWET11.SA', 'SHUL11.SA', 'WEGE11.SA', 'EALT11.SA', 'AERI4.SA', 'AERI11.SA', 'BDLL11.SA', 'KEPL11.SA', 'FRIO4.SA', 'FRIO11.SA', 'PTCA4.SA', 'ROMI11.SA', 'MTSA11.SA', 'TASA11.SA', 'AZUL3.SA', 'AZUL4.SA', 'VSPT11.SA', 'MRSA3.SA', 'MRSA4.SA', 'MRSA11.SA', 'RAIL4.SA', 'RAIL11.SA', 'HBSA4.SA', 'HBSA11.SA', 'LOGN4.SA', 'LOGN11.SA', 'LUXM3.SA', 'LUXM11.SA', 'JSLG4.SA', 'SEQL4.SA', 'SEQL11.SA', 'TGMA4.SA', 'TGMA11.SA', 'CRTE4.SA', 'CRTE11.SA', 'ECOR4.SA', 'ECOR11.SA', 'MOTV4.SA', 'MOTV11.SA', 'TPIS4.SA', 'TPIS11.SA', 'AGRU3.SA', 'AGRU4.SA', 'AGRU11.SA', 'HMOB4.SA', 'HMOB11.SA', 'IVPR3.SA', 'IVPR4.SA', 'IVPR11.SA', 'PSVM3.SA', 'PSVM4.SA', 'BBML4.SA', 'BBML11.SA', 'CTAX11.SA', 'DTCY11.SA', 'ALPK4.SA', 'ALPK11.SA', 'GGPS4.SA', 'GGPS11.SA', 'VLID4.SA', 'VLID11.SA', 'MMAQ11.SA', 'RBNS3.SA', 'RBNS4.SA', 'WLMM11.SA', 'TTEN4.SA', 'TTEN11.SA', 'AGXY4.SA', 'AGXY11.SA', 'APTI11.SA', 'SOJA4.SA', 'SOJA11.SA', 'AGRO4.SA', 'AGRO11.SA', 'CTCA4.SA', 'CTCA11.SA', 'EGGY4.SA', 'EGGY11.SA', 'SLCE4.SA', 'SLCE11.SA', 'LAND4.SA', 'LAND11.SA', 'JALL4.SA', 'JALL11.SA', 'SMTO4.SA', 'SMTO11.SA', 'FICT4.SA', 'FICT11.SA', 'JBSS4.SA', 'JBSS11.SA', 'MBRF4.SA', 'BEEF4.SA', 'MNPR11.SA', 'CAML4.SA', 'CAML11.SA', 'JOPA11.SA', 'MDIA4.SA', 'MDIA11.SA', 'ODER11.SA', 'ABEV4.SA', 'ABEV11.SA', 'ESPA4.SA', 'ESPA11.SA', 'NATU4.SA', 'NATU11.SA', 'BOBR11.SA', 'ASAI4.SA', 'ASAI11.SA', 'GMAT4.SA', 'GMAT11.SA', 'PCAR11.SA', 'AZZA4.SA', 'AZZA11.SA', 'CEAB4.SA', 'CEAB11.SA', 'CGRA11.SA', 'AMAR4.SA', 'LREN11.SA', 'RIAA4.SA', 'RIAA11.SA', 'VSTE4.SA', 'VSTE11.SA', 'ALLD4.SA', 'ALLD11.SA', 'BHIA4.SA', 'BHIA11.SA', 'MGLU4.SA', 'MGLU11.SA', 'AMER4.SA', 'SBFG4.SA', 'SBFG11.SA', 'LLBI11.SA', 'AUAU4.SA', 'AUAU11.SA', 'LJQQ4.SA', 'LJQQ11.SA', 'AVLL4.SA', 'CALI11.SA', 'CURY4.SA', 'CURY11.SA', 'CYRE11.SA', 'DIRR4.SA', 'DIRR11.SA', 'EVEN4.SA', 'EVEN11.SA', 'EZTC4.SA', 'EZTC11.SA', 'FIEI4.SA', 'FIEI11.SA', 'GFSA4.SA', 'HBOR4.SA', 'HBOR11.SA', 'INNC4.SA', 'INNC11.SA', 'JHSF4.SA', 'JHSF11.SA', 'JFEN4.SA', 'JFEN11.SA', 'KLAS4.SA', 'KLAS11.SA', 'LAVV4.SA', 'LAVV11.SA', 'MELK4.SA', 'MELK11.SA', 'MTRE4.SA', 'MTRE11.SA', 'MDNE4.SA', 'MDNE11.SA', 'MRVE4.SA', 'MRVE11.SA', 'PDGR4.SA', 'PDGR11.SA', 'PLPL4.SA', 'PLPL11.SA', 'CCTY4.SA', 'CCTY11.SA', 'RSID4.SA', 'RSID11.SA', 'TCSA4.SA', 'TCSA11.SA', 'TEND4.SA', 'TEND11.SA', 'TRIS4.SA', 'TRIS11.SA', 'VIVR4.SA', 'CEDO11.SA', 'DOHL11.SA', 'CATA11.SA', 'CTKA11.SA', 'PTNT11.SA', 'CTSA11.SA', 'TXRX11.SA', 'TFCO3.SA', 'TFCO11.SA', 'ALPA11.SA', 'CAMB11.SA', 'GRND4.SA', 'GRND11.SA', 'VULC11.SA', 'MNDL11.SA', 'TECN4.SA', 'TECN11.SA', 'VIVA4.SA', 'VIVA11.SA', 'WHRL11.SA', 'TOKY4.SA', 'UCAS4.SA', 'UCAS11.SA', 'WEST4.SA', 'WEST11.SA', 'HETA11.SA', 'AMOB4.SA', 'AMOB11.SA', 'MYPK11.SA', 'LEVE11.SA', 'PLAS4.SA', 'PLAS11.SA', 'HOOT11.SA', 'MEAL4.SA', 'MEAL11.SA', 'BMKS4.SA', 'BMKS11.SA', 'ESTR11.SA', 'RVEE4.SA', 'RVEE11.SA', 'AHEB4.SA', 'AHEB11.SA', 'SHOW4.SA', 'SHOW11.SA', 'CVCB4.SA', 'SMFT4.SA', 'ANIM4.SA', 'ANIM11.SA', 'ATED4.SA', 'ATED11.SA', 'BIED4.SA', 'BIED11.SA', 'COGN4.SA', 'COGN11.SA', 'CSED4.SA', 'CSED11.SA', 'SALT11.SA', 'OBTC4.SA', 'OBTC11.SA', 'SEER4.SA', 'SEER11.SA', 'VTRU4.SA', 'VTRU11.SA', 'YDUQ4.SA', 'YDUQ11.SA', 'RENT11.SA', 'MOVI4.SA', 'MOVI11.SA', 'VAMO4.SA', 'VAMO11.SA', 'DOTZ4.SA', 'DOTZ11.SA', 'OFSA4.SA', 'OFSA11.SA', 'AALR4.SA', 'AALR11.SA', 'DASA4.SA', 'DASA11.SA', 'FLRY4.SA', 'FLRY11.SA', 'HAPV4.SA', 'HAPV11.SA', 'MATD4.SA', 'MATD11.SA', 'ODPV4.SA', 'ODPV11.SA', 'ONCO4.SA', 'QUAL4.SA', 'QUAL11.SA', 'RDOR4.SA', 'RDOR11.SA', 'BALM11.SA', 'LMED4.SA', 'LMED11.SA', 'BLAU4.SA', 'BLAU11.SA', 'DMVF4.SA', 'DMVF11.SA', 'PNVL11.SA', 'EUFA4.SA', 'EUFA11.SA', 'HYPE4.SA', 'HYPE11.SA', 'PGMN4.SA', 'PFRM4.SA', 'PFRM11.SA', 'RADL4.SA', 'RADL11.SA', 'VVEO4.SA', 'VVEO11.SA', 'INTB4.SA', 'INTB11.SA', 'MLAS4.SA', 'MLAS11.SA', 'POSI4.SA', 'POSI11.SA', 'BMOB4.SA', 'BMOB11.SA', 'BRQB4.SA', 'BRQB11.SA', 'ENJU4.SA', 'ENJU11.SA', 'IFCM4.SA', 'IFCM11.SA', 'LWSA4.SA', 'LWSA11.SA', 'CASH4.SA', 'CASH11.SA', 'NGRD4.SA', 'NGRD11.SA', 'PDTC4.SA', 'PDTC11.SA', 'QUSW4.SA', 'QUSW11.SA', 'TRAD4.SA', 'TRAD11.SA', 'TOTS4.SA', 'TOTS11.SA', 'WDCN4.SA', 'WDCN11.SA', 'BRST4.SA', 'BRST11.SA', 'DESK4.SA', 'DESK11.SA', 'OIBR11.SA', 'TELB11.SA', 'VIVT11.SA', 'TIMS4.SA', 'TIMS11.SA', 'FIQE4.SA', 'FIQE11.SA', 'AESO4.SA', 'AESO11.SA', 'AFLT4.SA', 'AFLT11.SA', 'CBEE4.SA', 'CBEE11.SA', 'AURE4.SA', 'AURE11.SA', 'AXIA4.SA', 'AXIA11.SA', 'CEBR4.SA', 'CEBR11.SA', 'CEED11.SA', 'CLSC11.SA', 'GPAR4.SA', 'GPAR11.SA', 'CMIG11.SA', 'CEEB11.SA', 'COCE4.SA', 'COCE11.SA', 'COMR4.SA', 'COMR11.SA', 'CPLE4.SA', 'CPFE4.SA', 'CPFE11.SA', 'EKTR11.SA', 'EMAE11.SA', 'ENMT11.SA', 'ENEV4.SA', 'ENEV11.SA', 'EGIE4.SA', 'EGIE11.SA', 'EQPA4.SA', 'EQPA11.SA', 'EQMA3.SA', 'EQMA4.SA', 'EQMA11.SA', 'EQTL4.SA', 'EQTL11.SA', 'GEPA11.SA', 'ISAE11.SA', 'LIGH4.SA', 'LIGH11.SA', 'LIGT4.SA', 'LIGT11.SA', 'NEOE4.SA', 'NEOE11.SA', 'PRMN3.SA', 'PRMN4.SA', 'PRMN11.SA', 'REDE11.SA', 'RNEW11.SA', 'RIOS4.SA', 'RIOS11.SA', 'AMBP4.SA', 'AMBP11.SA', 'CASN4.SA', 'CASN11.SA', 'CSMG4.SA', 'CSMG11.SA', 'IGSN4.SA', 'IGSN11.SA', 'ORVR4.SA', 'ORVR11.SA', 'SBSP4.SA', 'SBSP11.SA', 'CEGR4.SA', 'CEGR11.SA', 'CGAS11.SA', 'PASS4.SA', 'ABCB11.SA', 'RPAD4.SA', 'RPAD11.SA', 'BMGB3.SA', 'BGIP11.SA', 'BEES11.SA', 'BPAR4.SA', 'BPAR11.SA', 'BRSR11.SA', 'BRBI3.SA', 'BRBI4.SA', 'BBDC11.SA', 'BSLI11.SA', 'BPAC4.SA', 'INBR3.SA', 'INBR4.SA', 'INBR11.SA', 'ITUB11.SA', 'BMIN11.SA', 'BMEB11.SA', 'BNBR11.SA', 'MERC11.SA', 'FIGE11.SA', 'BSCS3.SA', 'BSCS4.SA', 'BSCS11.SA', 'RBRA3.SA', 'RBRA4.SA', 'RBRA11.SA', 'PLSC3.SA', 'PLSC4.SA', 'PLSC11.SA', 'G2DI3.SA', 'G2DI4.SA', 'G2DI11.SA', 'PPLA3.SA', 'PPLA4.SA', 'B3SA4.SA', 'B3SA11.SA', 'CSUD4.SA', 'CSUD11.SA', 'BBSE4.SA', 'BBSE11.SA', 'CXSE4.SA', 'CXSE11.SA', 'PSSA4.SA', 'PSSA11.SA', 'IRBR4.SA', 'IRBR11.SA', 'WIZC4.SA', 'WIZC11.SA', 'ALOS4.SA', 'ALOS11.SA', 'GSHP4.SA', 'GSHP11.SA', 'HBTS4.SA', 'HBTS11.SA', 'HBRE4.SA', 'HBRE11.SA', 'LOGG4.SA', 'LOGG11.SA', 'MULT4.SA', 'MULT11.SA', 'NORD4.SA', 'NORD11.SA', 'PEAB11.SA', 'SCAR11.SA', 'SYNE4.SA', 'SYNE11.SA', 'LPSB4.SA', 'LPSB11.SA', 'NEXP4.SA', 'NEXP11.SA', 'ARND4.SA', 'ARND11.SA', 'EPAR4.SA', 'EPAR11.SA', 'ITSA11.SA', 'SIMH4.SA', 'SIMH11.SA', 'ADMF4.SA', 'ADMF11.SA', 'CTBA3.SA', 'CTBA4.SA', 'CTBA11.SA', 'MCRJ3.SA', 'MCRJ4.SA', 'MCRJ11.SA', 'PMSP3.SA', 'PMSP4.SA', 'PMSP11.SA', 'QVQP4.SA', 'QVQP11.SA', 'BETP4.SA', 'BETP11.SA', 'MAPT11.SA', 'OPGM4.SA', 'OPGM11.SA', 'PPAR4.SA', 'PPAR11.SA', 'PRPT4.SA', 'PRPT11.SA', 'OPSE4.SA', 'OPSE11.SA', 'OPTS4.SA', 'OPTS11.SA']
==============================================================

### Gerar arquivo CSV para viabilizar a consulta dos símbolos resultantes no Yahoo Finance

Sequência de instrução:
- Ler o arquivo Excel "B3_Empresas_Setor_20260206.xlsx", transformado em um Dataframe usando o Pandas.
- Utilizar o 4 caracteres iniciais dos Tickers Válidos "ticker_validos_yf" para buscar as informações na coluna "CÓDIGO" para obter as outras informações das colunas do Dataframe resultante do "B3_Empresas_Setor_20260206.xlsx".
- Gerar um arquivo csv com as informações combinadas das duas consultas:
    - coluna index: Ticker com valores correspondentes do tickers_validos_yf
    - colunas BEEST, SETOR ECONÔMICO, SBSETOR, SEGMENTO, NOME DE PREGÃO, SEGMENTO DE NEGOCIAÇÃO dos valores das respectivas colunas do df_b3_empresas_setor

In [19]:
# Exibir os tickers válidos
print("Tickers válidos para consulta no Yahoo Finance:")
print("Quantidade de tickers válidos: ", len(tickers_validos_yf))
print(tickers_validos_yf)

Tickers válidos para consulta no Yahoo Finance:
Quantidade de tickers válidos:  505
['AZTE3.SA', 'AZTE11.SA', 'BRAV3.SA', 'CSAN3.SA', 'RPMG3.SA', 'RPMG4.SA', 'PETR3.SA', 'PETR4.SA', 'RECV3.SA', 'PRIO3.SA', 'RAIZ4.SA', 'UGPA3.SA', 'UGPA4.SA', 'LUPA3.SA', 'LUPA11.SA', 'OPCT3.SA', 'OSXB3.SA', 'VBBR3.SA', 'BRAP3.SA', 'BRAP4.SA', 'CBAV3.SA', 'CMIN3.SA', 'LTLA3.SA', 'VALE3.SA', 'FESA3.SA', 'FESA4.SA', 'GGBR3.SA', 'GGBR4.SA', 'GOAU3.SA', 'GOAU4.SA', 'CSNA3.SA', 'USIM3.SA', 'HAGA3.SA', 'HAGA4.SA', 'MGEL3.SA', 'MGEL4.SA', 'PATI3.SA', 'PATI4.SA', 'TKNO3.SA', 'TKNO4.SA', 'PMAM3.SA', 'PMAM4.SA', 'PMAM11.SA', 'BRKM3.SA', 'DEXP3.SA', 'DEXP4.SA', 'FHER3.SA', 'NUTR3.SA', 'VITT3.SA', 'CRPG3.SA', 'UNIP3.SA', 'DXCO3.SA', 'EUCA3.SA', 'EUCA4.SA', 'KLBN3.SA', 'KLBN4.SA', 'KLBN11.SA', 'MSPA3.SA', 'MSPA4.SA', 'NEMO4.SA', 'SUZB3.SA', 'RANI3.SA', 'RANI4.SA', 'SNSY3.SA', 'ETER3.SA', 'ETER4.SA', 'PTBL3.SA', 'PTBL4.SA', 'AZEV3.SA', 'AZEV4.SA', 'AZEV11.SA', 'SOND3.SA', 'ARML3.SA', 'MILS3.SA', 'PRNR3.SA', 'EMBJ3.SA', 'FRAS3.SA', 'FRAS4.SA', 'POMO3.SA', 'POMO4.SA', 'RAPT3.SA', 'RAPT4.SA', 'RCSL3.SA', 'RCSL4.SA', 'RSUL4.SA', 'TUPY3.SA', 'TUPY4.SA', 'MWET3.SA', 'MWET4.SA', 'SHUL3.SA', 'SHUL4.SA', 'WEGE3.SA', 'WEGE4.SA', 'EALT3.SA', 'EALT4.SA', 'AERI3.SA', 'BDLL3.SA', 'BDLL4.SA', 'INEP3.SA', 'INEP4.SA', 'INEP11.SA', 'KEPL3.SA', 'KEPL4.SA', 'FRIO3.SA', 'PTCA3.SA', 'PTCA11.SA', 'ROMI3.SA', 'ROMI4.SA', 'MTSA3.SA', 'MTSA4.SA', 'TASA3.SA', 'TASA4.SA', 'AZUL11.SA', 'GOLL3.SA', 'GOLL4.SA', 'GOLL11.SA', 'VSPT3.SA', 'VSPT4.SA', 'RAIL3.SA', 'HBSA3.SA', 'LOGN3.SA', 'LUXM4.SA', 'JSLG3.SA', 'JSLG11.SA', 'SEQL3.SA', 'TGMA3.SA', 'CRTE3.SA', 'ECOR3.SA', 'MOTV3.SA', 'TPIS3.SA', 'HMOB3.SA', 'PSVM11.SA', 'BBML3.SA', 'CTAX3.SA', 'CTAX4.SA', 'DTCY3.SA', 'DTCY4.SA', 'ALPK3.SA', 'GGPS3.SA', 'VLID3.SA', 'MMAQ3.SA', 'MMAQ4.SA', 'RBNS11.SA', 'WLMM3.SA', 'WLMM4.SA', 'TTEN3.SA', 'AGXY3.SA', 'APTI3.SA', 'APTI4.SA', 'SOJA3.SA', 'AGRO3.SA', 'CTCA3.SA', 'EGGY3.SA', 'SLCE3.SA', 'LAND3.SA', 'JALL3.SA', 'SMTO3.SA', 'BAUH3.SA', 'BAUH4.SA', 'BAUH11.SA', 'FICT3.SA', 'JBSS3.SA', 'MBRF3.SA', 'MBRF11.SA', 'BEEF3.SA', 'BEEF11.SA', 'MNPR3.SA', 'MNPR4.SA', 'CAML3.SA', 'JOPA3.SA', 'JOPA4.SA', 'MDIA3.SA', 'ODER3.SA', 'ODER4.SA', 'ABEV3.SA', 'ESPA3.SA', 'NATU3.SA', 'BOBR3.SA', 'BOBR4.SA', 'ASAI3.SA', 'GMAT3.SA', 'PCAR3.SA', 'PCAR4.SA', 'AZZA3.SA', 'CEAB3.SA', 'CGRA3.SA', 'CGRA4.SA', 'AMAR3.SA', 'AMAR11.SA', 'LREN3.SA', 'LREN4.SA', 'RIAA3.SA', 'VSTE3.SA', 'ALLD3.SA', 'BHIA3.SA', 'MGLU3.SA', 'AMER3.SA', 'AMER11.SA', 'SBFG3.SA', 'LLBI3.SA', 'LLBI4.SA', 'AUAU3.SA', 'LJQQ3.SA', 'AVLL3.SA', 'AVLL11.SA', 'CALI3.SA', 'CALI4.SA', 'CURY3.SA', 'CYRE3.SA', 'CYRE4.SA', 'DIRR3.SA', 'EVEN3.SA', 'EZTC3.SA', 'FIEI3.SA', 'GFSA3.SA', 'GFSA11.SA', 'HBOR3.SA', 'INNC3.SA', 'JHSF3.SA', 'JFEN3.SA', 'KLAS3.SA', 'LAVV3.SA', 'MELK3.SA', 'MTRE3.SA', 'MDNE3.SA', 'MRVE3.SA', 'PDGR3.SA', 'PLPL3.SA', 'CCTY3.SA', 'RSID3.SA', 'TCSA3.SA', 'TEND3.SA', 'TRIS3.SA', 'VIVR3.SA', 'VIVR11.SA', 'CEDO3.SA', 'CEDO4.SA', 'DOHL3.SA', 'DOHL4.SA', 'CATA3.SA', 'CATA4.SA', 'CTKA3.SA', 'CTKA4.SA', 'PTNT3.SA', 'PTNT4.SA', 'CTSA3.SA', 'CTSA4.SA', 'TXRX3.SA', 'TXRX4.SA', 'TFCO4.SA', 'ALPA3.SA', 'ALPA4.SA', 'CAMB3.SA', 'CAMB4.SA', 'GRND3.SA', 'VULC3.SA', 'VULC4.SA', 'MNDL3.SA', 'MNDL4.SA', 'TECN3.SA', 'VIVA3.SA', 'WHRL3.SA', 'WHRL4.SA', 'TOKY3.SA', 'TOKY11.SA', 'UCAS3.SA', 'WEST3.SA', 'HETA3.SA', 'HETA4.SA', 'AMOB3.SA', 'MYPK3.SA', 'MYPK4.SA', 'LEVE3.SA', 'LEVE4.SA', 'PLAS3.SA', 'HOOT3.SA', 'HOOT4.SA', 'MEAL3.SA', 'BMKS3.SA', 'ESTR3.SA', 'ESTR4.SA', 'RVEE3.SA', 'AHEB3.SA', 'SHOW3.SA', 'CVCB3.SA', 'CVCB11.SA', 'SMFT3.SA', 'SMFT11.SA', 'ANIM3.SA', 'ATED3.SA', 'BIED3.SA', 'COGN3.SA', 'CSED3.SA', 'SALT3.SA', 'SALT4.SA', 'OBTC3.SA', 'SEER3.SA', 'VTRU3.SA', 'YDUQ3.SA', 'RENT3.SA', 'RENT4.SA', 'MOVI3.SA', 'VAMO3.SA', 'DOTZ3.SA', 'BIOM3.SA', 'BIOM4.SA', 'BIOM11.SA', 'OFSA3.SA', 'AALR3.SA', 'DASA3.SA', 'FLRY3.SA', 'HAPV3.SA', 'MATD3.SA', 'ODPV3.SA', 'ONCO3.SA', 'ONCO11.SA', 'QUAL3.SA', 'RDOR3.SA', 'BALM3.SA', 'BALM4.SA', 'LMED3.SA', 'BLAU3.SA', 'DMVF3.SA', 'PNVL3.SA', 'PNVL4.SA', 'EUFA3.SA', 'HYPE3.SA', 'PGMN3.SA', 'PGMN11.SA', 'PFRM3.SA', 'RADL3.SA', 'VVEO3.SA', 'INTB3.SA', 'MLAS3.SA', 'POSI3.SA', 'BMOB3.SA', 'BRQB3.SA', 'ENJU3.SA', 'IFCM3.SA', 'LWSA3.SA', 'CASH3.SA', 'NGRD3.SA', 'PDTC3.SA', 'QUSW3.SA', 'TRAD3.SA', 'TOTS3.SA', 'WDCN3.SA', 'BRST3.SA', 'DESK3.SA', 'OIBR3.SA', 'OIBR4.SA', 'TELB3.SA', 'TELB4.SA', 'VIVT3.SA', 'VIVT4.SA', 'TIMS3.SA', 'FIQE3.SA', 'AESO3.SA', 'AFLT3.SA', 'ALUP3.SA', 'ALUP4.SA', 'ALUP11.SA', 'CBEE3.SA', 'AURE3.SA', 'AXIA3.SA', 'CEBR3.SA', 'CEED3.SA', 'CEED4.SA', 'CLSC3.SA', 'CLSC4.SA', 'GPAR3.SA', 'CMIG3.SA', 'CMIG4.SA', 'CEEB3.SA', 'CEEB4.SA', 'COCE3.SA', 'COMR3.SA', 'CPLE3.SA', 'CPLE11.SA', 'CPFE3.SA', 'EKTR3.SA', 'EKTR4.SA', 'EMAE3.SA', 'EMAE4.SA', 'ENGI3.SA', 'ENGI4.SA', 'ENGI11.SA', 'ENMT3.SA', 'ENMT4.SA', 'ENEV3.SA', 'EGIE3.SA', 'EQPA3.SA', 'EQTL3.SA', 'GEPA3.SA', 'GEPA4.SA', 'ISAE3.SA', 'ISAE4.SA', 'LIGH3.SA', 'LIGT3.SA', 'NEOE3.SA', 'REDE3.SA', 'REDE4.SA', 'RNEW3.SA', 'RNEW4.SA', 'RIOS3.SA', 'TAEE3.SA', 'TAEE4.SA', 'TAEE11.SA', 'AMBP3.SA', 'CASN3.SA', 'CSMG3.SA', 'IGSN3.SA', 'ORVR3.SA', 'SBSP3.SA', 'SAPR3.SA', 'SAPR4.SA', 'SAPR11.SA', 'CEGR3.SA', 'CGAS3.SA', 'CGAS4.SA', 'PASS3.SA', 'PASS11.SA', 'ABCB3.SA', 'ABCB4.SA', 'RPAD3.SA', 'BAZA3.SA', 'BAZA4.SA', 'BAZA11.SA', 'BMGB4.SA', 'BMGB11.SA', 'BGIP3.SA', 'BGIP4.SA', 'BEES3.SA', 'BEES4.SA', 'BPAR3.SA', 'BRSR3.SA', 'BRSR4.SA', 'BRBI11.SA', 'BBDC3.SA', 'BBDC4.SA', 'BBAS3.SA', 'BBAS4.SA', 'BBAS11.SA', 'BSLI3.SA', 'BSLI4.SA', 'BPAC3.SA', 'BPAC11.SA', 'ITUB3.SA', 'ITUB4.SA', 'BMIN3.SA', 'BMIN4.SA', 'BMEB3.SA', 'BMEB4.SA', 'BNBR3.SA', 'BNBR4.SA', 'PINE3.SA', 'PINE4.SA', 'PINE11.SA', 'SANB3.SA', 'SANB4.SA', 'SANB11.SA', 'MERC3.SA', 'MERC4.SA', 'FIGE3.SA', 'FIGE4.SA', 'PPLA11.SA', 'B3SA3.SA', 'CSUD3.SA', 'BBSE3.SA', 'CXSE3.SA', 'PSSA3.SA', 'IRBR3.SA', 'WIZC3.SA', 'ALOS3.SA', 'GSHP3.SA', 'HBTS3.SA', 'HBRE3.SA', 'IGTI3.SA', 'IGTI4.SA', 'IGTI11.SA', 'LOGG3.SA', 'MULT3.SA', 'NORD3.SA', 'PEAB3.SA', 'PEAB4.SA', 'SCAR3.SA', 'SCAR4.SA', 'SYNE3.SA', 'LPSB3.SA', 'NEXP3.SA', 'ARND3.SA', 'EPAR3.SA', 'ITSA3.SA', 'ITSA4.SA', 'SIMH3.SA', 'ADMF3.SA', 'QVQP3.SA', 'BETP3.SA', 'MAPT3.SA', 'MAPT4.SA', 'OPGM3.SA', 'PPAR3.SA', 'PRPT3.SA', 'OPSE3.SA', 'OPTS3.SA']

In [20]:
# Arquivo Excel de origem da relação de papéis e setores
arquivo = "../utils/gera_tikers/B3_Empresas_Setor_20260206.xlsx"

# Planilha e aba onde estão os papéis e setores
planilha = 'Setor'
colunas_intervalo = 'B:H'
pula_linhas = 2
numero_linhas = 370

# DataFrame para armazenar os dados coletados
df_b3_empresas_setor = pd.read_excel(
                        io=arquivo, 
                        sheet_name=planilha,
                        usecols=colunas_intervalo,
                        skiprows=pula_linhas,
                        nrows=numero_linhas,
                        index_col='CÓDIGO' # Definir a coluna 'CÓDIGO' como índice do DataFrame
                        )

# Exibir o DataFrame para verificar os dados coletados
df_b3_empresas_setor.head()

,BEEST,SETOR ECONÔMICO,SUBSETOR,SEGMENTO,NOME DE PREGÃO,SEGMENTO DE NEGOCIAÇÃO
CÓDIGO,,,,,,
AZTE,Outra,"Petróleo, Gás e Biocombustíveis","Petróleo, Gás e Biocombustíveis","Exploração, Refino e Distribuição",AZT ENERGIA,Básico Bolsa
BRAV,Outra,"Petróleo, Gás e Biocombustíveis","Petróleo, Gás e Biocombustíveis","Exploração, Refino e Distribuição",BRAVA,Novo Mercado
CSAN,Outra,"Petróleo, Gás e Biocombustíveis","Petróleo, Gás e Biocombustíveis","Exploração, Refino e Distribuição",COSAN,Novo Mercado
RPMG,Outra,"Petróleo, Gás e Biocombustíveis","Petróleo, Gás e Biocombustíveis","Exploração, Refino e Distribuição",PET MANGUINH,Básico Bolsa
PETR,Escolhida,"Petróleo, Gás e Biocombustíveis","Petróleo, Gás e Biocombustíveis","Exploração, Refino e Distribuição",PETROBRAS,Nível 2

In [22]:
# Iterar sobre os 4 primeiros caracteres dos tickers válidos para buscar as das colunas do DataFrame para gerar um novo DataFrame

# Criar uma lista para armazenar os dicionários de informações dos tickers válidos
tickers_info_list = []

# Iterar sobre os tickers válidos e extrair as informações correspondentes do DataFrame original
for ticker in tickers_validos_yf:
    # Extrair os 4 primeiros caracteres do ticker para buscar no DataFrame
    t = ticker[:4]
    # Localizar o ticker no DataFrame Empresas Setor da B3 e extrair as informações correspondentes
    info = df_b3_empresas_setor.loc[df_b3_empresas_setor.index.str.startswith(t)]
    # Para cada linha encontrada, adicionar o ticker como uma nova coluna
    for _, row in info.iterrows(): # Iterar sobre as linhas encontradas para o ticker
        row_dict = row.to_dict() # Converter a linha para um dicionário
        row_dict['TICKER'] = ticker # Adicionar o ticker ao dicionário
        tickers_info_list.append(row_dict) # Adicionar o dicionário à lista de informações dos tickers

# Criar o DataFrame a partir da lista
tickers_info = pd.DataFrame(tickers_info_list)

# Definir a coluna TICKER como index do DataFrame
tickers_info = tickers_info.set_index('TICKER')

# Exibir a quantidade de tickers_info gerados
print("Quantidade de tickers_info gerados: ", len(tickers_info))

# Exibir o DataFrame com as informações dos tickers válidos
tickers_info.head()

Quantidade de tickers_info gerados:  505

,BEEST,SETOR ECONÔMICO,SUBSETOR,SEGMENTO,NOME DE PREGÃO,SEGMENTO DE NEGOCIAÇÃO
TICKER,,,,,,
AZTE3.SA,Outra,"Petróleo, Gás e Biocombustíveis","Petróleo, Gás e Biocombustíveis","Exploração, Refino e Distribuição",AZT ENERGIA,Básico Bolsa
AZTE11.SA,Outra,"Petróleo, Gás e Biocombustíveis","Petróleo, Gás e Biocombustíveis","Exploração, Refino e Distribuição",AZT ENERGIA,Básico Bolsa
BRAV3.SA,Outra,"Petróleo, Gás e Biocombustíveis","Petróleo, Gás e Biocombustíveis","Exploração, Refino e Distribuição",BRAVA,Novo Mercado
CSAN3.SA,Outra,"Petróleo, Gás e Biocombustíveis","Petróleo, Gás e Biocombustíveis","Exploração, Refino e Distribuição",COSAN,Novo Mercado
RPMG3.SA,Outra,"Petróleo, Gás e Biocombustíveis","Petróleo, Gás e Biocombustíveis","Exploração, Refino e Distribuição",PET MANGUINH,Básico Bolsa

In [23]:
# Transformar o DataFrame tickers_info em um arquivo csv para ser utilizado posteriormente
tickers_info.to_csv('../utils/gera_tikers/tickers_info.csv', index=True) # Index True para manter a coluna TICKER como index no arquivo csv

### Função para gerar o arquivo CSV para consulta dos símbolos resultantes no Yahoo Finance
A função `gerar_csv_tickers_validos` tem como objetivo criar um arquivo CSV contendo os tickers válidos para consulta no Yahoo Finance, juntamente com informações adicionais obtidas a partir do arquivo Excel "B3_Empresas_Setor_20260206.xlsx". O processo envolve a leitura do arquivo Excel, a filtragem dos tickers válidos, e a combinação das informações para gerar um arquivo CSV estruturado.

In [24]:
def gerar_df_b3_empresas_setor(caminho_arquivo: str, 
                                    planilha: str = 'Setor', 
                                    colunas_intervalo: str = 'B:H', 
                                    pula_linhas: int = 2, 
                                    numero_linhas: int = 370) -> pd.DataFrame:
    """
    Carrega e retorna um DataFrame com as informações de empresas e setores da B3.
    
    Esta função lê um arquivo Excel contendo dados de empresas listadas na Bolsa
    de Valores do Brasil (B3), com informações sobre setores econômicos,
    subsetores, segmentos de negociação e outros dados estruturais.
    
    Parâmetros
    ----------
    caminho_arquivo : str
        Caminho completo ou relativo do arquivo Excel contendo dados das empresas e setores.
        Exemplo: '../utils/gera_tikers/B3_Empresas_Setor_20260206.xlsx'
    
    planilha : str, optional
        Nome da aba/planilha no arquivo Excel (padrão: 'Setor').
        A planilha deve conter uma coluna chamada 'CÓDIGO' que será usada como índice.
    
    colunas_intervalo : str, optional
        Intervalo de colunas a ler no formato Excel (padrão: 'B:H').
        Exemplos válidos: 'A:E', 'B:H', 'C:F'.
    
    pula_linhas : int, optional
        Número de linhas iniciais a pular na leitura (padrão: 2).
        Útil para ignorar cabeçalhos ou informações adicionais no início do arquivo.
    
    numero_linhas : int, optional
        Número máximo de linhas de dados a ler (padrão: 370).
        Se o arquivo tiver menos linhas, todas serão lidas.
    
    Retorno
    -------
    pd.DataFrame
        DataFrame com a coluna 'CÓDIGO' definida como índice, contendo as seguintes
        informações estruturais:
        - BEEST (ou similar)
        - SETOR ECONÔMICO
        - SUBSETOR
        - SEGMENTO
        - NOME DE PREGÃO
        - SEGMENTO DE NEGOCIAÇÃO
        
        O índice do DataFrame conterá os códigos das empresas (ex: 'PETR', 'VALE', 'ITUB').
    """
    try:
        # Ler o arquivo Excel com os parâmetros especificados
        df_b3_empresas_setor = pd.read_excel(
            io=caminho_arquivo,
            sheet_name=planilha,
            usecols=colunas_intervalo,
            skiprows=pula_linhas,
            nrows=numero_linhas,
            index_col='CÓDIGO'  # Definir a coluna 'CÓDIGO' como índice do DataFrame
        )
        
        return df_b3_empresas_setor
    
    # Tratamento de exceções para garantir que erros sejam informativos
    except FileNotFoundError:
        raise FileNotFoundError(f"Arquivo não encontrado: {caminho_arquivo}")
    except ValueError as e:
        raise ValueError(f"Erro ao ler o arquivo Excel: {str(e)}")
    except Exception as e:
        raise Exception(f"Erro inesperado ao processar o arquivo: {str(e)}")


# Gerar o DataFrame de empresas e setores da B3
caminho_arquivo_b3 = "../utils/gera_tikers/B3_Empresas_Setor_20260206.xlsx"

df_b3_empresas_setor = gerar_df_b3_empresas_setor(
    caminho_arquivo=caminho_arquivo_b3,
    planilha='Setor',
    colunas_intervalo='B:H',
    pula_linhas=2,
    numero_linhas=370
)

In [25]:
# Exibir o DataFrame 
df_b3_empresas_setor.head()

,BEEST,SETOR ECONÔMICO,SUBSETOR,SEGMENTO,NOME DE PREGÃO,SEGMENTO DE NEGOCIAÇÃO
CÓDIGO,,,,,,
AZTE,Outra,"Petróleo, Gás e Biocombustíveis","Petróleo, Gás e Biocombustíveis","Exploração, Refino e Distribuição",AZT ENERGIA,Básico Bolsa
BRAV,Outra,"Petróleo, Gás e Biocombustíveis","Petróleo, Gás e Biocombustíveis","Exploração, Refino e Distribuição",BRAVA,Novo Mercado
CSAN,Outra,"Petróleo, Gás e Biocombustíveis","Petróleo, Gás e Biocombustíveis","Exploração, Refino e Distribuição",COSAN,Novo Mercado
RPMG,Outra,"Petróleo, Gás e Biocombustíveis","Petróleo, Gás e Biocombustíveis","Exploração, Refino e Distribuição",PET MANGUINH,Básico Bolsa
PETR,Escolhida,"Petróleo, Gás e Biocombustíveis","Petróleo, Gás e Biocombustíveis","Exploração, Refino e Distribuição",PETROBRAS,Nível 2

In [26]:
def gerar_csv_tickers_info(df_b3_empresas_setor, tickers_validos, caminho_saida_csv=None):
    """
    Gera um DataFrame com informações da B3 para os tickers válidos do Yahoo Finance
    e, opcionalmente, salva o resultado em um arquivo CSV.

    A função usa o DataFrame `df_b3_empresas_setor` (com índice em 'CÓDIGO') e
    combina as informações para cada ticker válido, utilizando os 4 primeiros
    caracteres do ticker como chave de busca.

    Parâmetros
    ----------
    df_b3_empresas_setor : pd.DataFrame
        DataFrame com informações da B3 e índice na coluna 'CÓDIGO'.
    tickers_validos : list
        Lista de tickers válidos do Yahoo Finance (ex: 'AZTE3.SA', 'BRAV3.SA').
    caminho_saida_csv : str, optional
        Caminho para salvar o CSV. Se None, não salva (padrão: None).

    Retorno
    -------
    pd.DataFrame
        DataFrame com tickers como índice e informações da B3 como colunas.
    """
    # Criar lista para armazenar dados
    tickers_info_list = []
    
    # Iterar sobre os tickers válidos
    for ticker in tickers_validos:
        # Extrair os 4 primeiros caracteres do ticker
        t = ticker[:4]
        # Localizar informações correspondentes no DataFrame
        info = df_b3_empresas_setor.loc[df_b3_empresas_setor.index.str.startswith(t)]
        # Para cada linha encontrada, adicionar o ticker como nova coluna
        for _, row in info.iterrows():
            row_dict = row.to_dict()
            row_dict['TICKER'] = ticker
            tickers_info_list.append(row_dict)
    
    # Criar DataFrame a partir da lista de dicionários
    tickers_info = pd.DataFrame(tickers_info_list)
    
    # Definir TICKER como índice do DataFrame
    tickers_info = tickers_info.set_index('TICKER')
    
    # Salvar como CSV se caminho foi fornecido
    if caminho_saida_csv:
        tickers_info.to_csv(caminho_saida_csv, index=True)
        print(f"Arquivo CSV salvo em: {caminho_saida_csv}")
    
    return tickers_info

In [27]:
# Gerar o DataFrame com informações dos tickers válidos e salvar como CSV
caminho_saida_csv = '../utils/gera_tikers/tickers_info.csv'
tickers_info = gerar_csv_tickers_info(df_b3_empresas_setor, tickers_validos_yf, caminho_saida_csv)

# Exibir o DataFrame com as informações dos tickers válidos
print("DataFrame com informações dos tickers válidos:")
print(tickers_info.head())

Arquivo CSV salvo em: ../utils/gera_tikers/tickers_info.csv
DataFrame com informações dos tickers válidos:
           BEEST                  SETOR ECONÔMICO  \
TICKER
AZTE3.SA   Outra  Petróleo, Gás e Biocombustíveis
AZTE11.SA  Outra  Petróleo, Gás e Biocombustíveis
BRAV3.SA   Outra  Petróleo, Gás e Biocombustíveis
CSAN3.SA   Outra  Petróleo, Gás e Biocombustíveis
RPMG3.SA   Outra  Petróleo, Gás e Biocombustíveis

                                  SUBSETOR                           SEGMENTO  \
TICKER
AZTE3.SA   Petróleo, Gás e Biocombustíveis  Exploração, Refino e Distribuição
AZTE11.SA  Petróleo, Gás e Biocombustíveis  Exploração, Refino e Distribuição
BRAV3.SA   Petróleo, Gás e Biocombustíveis  Exploração, Refino e Distribuição
CSAN3.SA   Petróleo, Gás e Biocombustíveis  Exploração, Refino e Distribuição
RPMG3.SA   Petróleo, Gás e Biocombustíveis  Exploração, Refino e Distribuição

          NOME DE PREGÃO SEGMENTO DE NEGOCIAÇÃO
TICKER
AZTE3.SA     AZT ENERGIA           Básico Bolsa
AZTE11.SA    AZT ENERGIA           Básico Bolsa
BRAV3.SA           BRAVA           Novo Mercado
CSAN3.SA           COSAN           Novo Mercado
RPMG3.SA    PET MANGUINH           Básico Bolsa